### ISSUE TITLE
In the Search Results web part,I can't able to add custom managed fields also unable to load any custom handlebars or custom JavaScript? is there any workaround? 

### ISSUE THREAD

**Issue by CMREDD** [microsoft-search/pnp-modern-search#1157] opened 2021-07-15 17:04 UTC
In the Search Results web part, I can't able to add custom managed fields also unable to load any custom handlebars or custom JavaScript?
is there any workaround? 
![Managed card fields](https://user-images.githubusercontent.com/50401427/125828229-33a4e16a-1cee-4077-99da-4625538b22ca.PNG)

**Comment by FranckyC** [comment] 2021-07-15 22:17
Hi @CMREDD, please use the issue template...We will need more information to help you:

- What version of PnP Modern Search are you using?
- When you say you can't load custom handlebars, can you share the template content you want to use?
- When you say managed fields, you mean SharePoint managed properties? What is the issue, you don't see them in the control? The values are empty when rendered?

Also, you can't write your own Javascript in template for secutiry reasons. This is by design.

**Comment by CMREDD** [comment] 2021-07-16 09:50
1.  I am working for pnp Modern Search WebPart V4.
2.  Please find the attached template.
3.  Can I able to add managed card fields? Please find attached file (Default given slots and handle bars here: Title, Tags, Location, ImagePreviewUrl, Author, File Extension, Date, URL etc...., Here can i able to add any custom managed field?)
![Manage card fields](https://user-images.githubusercontent.com/50401427/125928845-6849da55-6463-4ccd-9c67-4fd1126b4015.png)

**Comment by CMREDD** [comment] 2021-07-16 10:39
1. I am working for pnp Modern Search WebPart V4.
2. Please find the attached template.
3. Can I able to add managed card fields? Please find attached file (Default given slots and handle bars here: Title, Tags, Location, ImagePreviewUrl, Author, File Extension, Date, URL etc...., Here can i able to add any custom managed field?)
Kindly let me know 
![Manage card fields](https://user-images.githubusercontent.com/50401427/125935532-cf47f060-b3c8-469a-9d0f-1acfb5261713.png)
anybody whether this possible or not?

**Comment by FranckyC** [comment] 2021-07-20 15:49
You can't add your own fields here. These are placeholders on a card. However, in the value column, you can use fields values from your results using `{{item.<your_property>}}`.

For fields flagged with _Allow HTML_, you can use [web components](https://microsoft-search.github.io/pnp-modern-search/extensibility/web_components_list/) or any Handlebars logic with HTML makrup here. The output will be HTML. For other fields, the output will be plain text.

**Comment by wobba** [comment] 2021-07-25 10:54
@CMREDD does this solve your issue?

**Comment by pboard** [comment] 2022-07-01 04:52
> You can't add your own fields here. These are placeholders on a card. However, in the value column, you can use fields values from your results using `{{item.<your_property>}}`.
> 
> For fields flagged with _Allow HTML_, you can use [web components](https://microsoft-search.github.io/pnp-modern-search/extensibility/web_components_list/) or any Handlebars logic with HTML makrup here. The output will be HTML. For other fields, the output will be plain text.

In a version Prior to 4.5.4 (Feb 2022 source code), the onclick="window.toggle(event)" command in a Hyperlink or Button could be intercepted, with a bit of Javascript, and it could then be used to perform an action such as hiding / unhiding a page element using something like the following Javascript to show elements based on a SharePoint List ID, however with 4.5.4 which was just rolled out in our organization two weeks ago, this no longer works.

window.toggle = (e) => {
 // Prevent the actual action of linking somewhere
 e.preventDefault();
 const [,anchorId] = e.currentTarget.id.split('-');
 $('.nugget').hide();
 $(`#anchor-${anchorId}`).show();  
};

This could be set in a Custom Layouts template, in the Edit Results Template, and would execute fine.

<span class="template--listItem--title example-themePrimary">
 <a id="menu-{{itemAt (split (slot item @root.slots.PreviewUrl) '=') 1}}" href="" style="color:{{@root.theme.semanticColors.link}}" onclick="window.toggle(event)" >{{slot item @root.slots.Title}}</a>
</span>

Were we just lucky for a period of time that this worked? Or has something changed that has now broken this ability? maybe it was an oversite and shouldn't have worked before?

One other thing that changed in the 4.5.4 release we are now using is we used to have results from Lists returning data in Site Columns that had hyphens in the name, however with the 4.5.4, only Site Columns that don't have a Hyphen work. These site column based list columns can be used in Search Result templates to show specific columns of data in your results.

Eg if you had a Site Column added as a column to a list named My-Company-State, from 4.5.4 this no longer works, but if you rebuild it with a site column named MyCompanyState, that works.

**Comment by wobba** [comment] 2022-07-01 07:40
Injected javascript working was a bug which we fixed in v4.4.1. If you want to add javascript and logic then you need to develop a custom web component or remove css/script sanitization from the code base and build it yourself.

The web parts should be safe and secure to use with proper security governance.

**Comment by pboard** [comment] 2022-07-01 08:19
> Injected javascript working was a bug which we fixed in v4.4.1. If you want to add javascript and logic then you need to develop a custom web component or remove css/script sanitization from the code base and build it yourself.
> 
> The web parts should be safe and secure to use with proper security governance.

Thanks, I thought that might have been the case based on the above discussion. Just wanted to confirm that was true and not a bug :-)

**Closed** 2022-07-04 13:30 UTC
Labels: question
