### ISSUE TITLE
Documentation clarification question regarding {{unique}}

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#911] opened 2021-04-02 23:55 UTC
Hi, I'm having difficulties understanding what and how the {{unique}} handlebar helper works. I have a query that returns a list of names, some of which are listed multiple times, and I'd like to be able to eject the duplicates. I though {{unique}} sounded promising, but I've not been able to get it to work. Is this what it actually does? Or am I not understanding it's use. Can it not be used to adjust items retrieved during an {{#each}}?

I'm attempting to iterate through;
{#each items as |item|}}
   {{nameOWSTEXT}}
{/each}

My results looks like:
Jane Doe
Jane Doe
Sara Smith
Jane Doe

I'd love to nip that down to just the two unique entries. I've tried about a zillion different ways to insert {{#each (unique)}} into the equation with no success. If it is doable, I could really use an example. Is there anywhere I can be looking for more examples to pour over? It would be very helpful.

Thanks much!

**Comment by wobba** [comment] 2021-04-04 09:11
Don't have a sample at hand but if you only output one field you can try to use `pluck` https://github.com/helpers/handlebars-helpers#pluck. Another approach is `sortby`, and in the loop compare with the previous item and only render if it is different.

The better approach was if we exposed `collapsespec` as part of web part settings which would only return unique values, and you would not have to handle this as part of the UX loop.

**Comment by bryllyg** [comment] 2021-04-05 15:21
Thanks, I was looking at pluck and sortby too, yah! I'm getting the hang of it. Many thanks for the pointers and clarification.  I may add a feature request for collapsespec for future revs, that would be handy. Off to go whip it into shape!

**Comment by bryllyg** [comment] 2021-04-05 17:36
I did some more testing, and it looks like my problem may be that pluck and unique are not getting loaded. I get no results from my query, and if I F12 and look at the Console log, I see "Uncaught (in promise) ... Missing helper: "pluck""

![image](https://user-images.githubusercontent.com/2616432/113602069-00ee2580-95f7-11eb-8baa-3e2b768dc57a.png)

I've been able to use other helpers such as 'has' and 'lowercase', so I've been assuming I don't have to install anything extra to use all of the helpers listed here: https://github.com/helpers/handlebars-helpers. Am I incorrect?

**Comment by wobba** [comment] 2021-04-05 19:15
I'll recheck if they are included or not. We are using the latest version and I'll look at this and report back.

**Comment by bryllyg** [comment] 2021-04-09 20:54
Could I use {{getUnique items "<property>"}}? This doesn't throw an error, but all I get back is a bunch of zeros. Am I using this wrong, or is this not for filtering out dups? 

	{{#each items}}
			{{getUnique items "MyFieldOWSTEXT"}}<br/>
	{{/each}}

**Comment by bryllyg** [comment] 2021-04-13 23:02
Hi, just checking to see if anyone has a way to get these unique entries without using unique or pluck?

**Comment by wobba** [comment] 2021-04-14 14:18
@bryllyg That's the method indeed. Try to use it like this
```
{{#each (getUnique items "MyFieldOWSTEXT") as |item|}}
{{/each}}
```

**Comment by bryllyg** [comment] 2021-04-14 18:13
Excellent!

**Comment by bryllyg** [comment] 2021-06-29 22:56
Following up on the query in this thread about helpers that are not included in the build. I'd still like to get the additional handlebar helpers such as unique, pluck and first added to the 3.x (and 4 if they're not included). I'm running into a few cases right now where I could really use them.

**Comment by wobba** [comment] 2021-06-30 07:24
`unique` and `pluck` should be be in both v3 and v4. All of the ones listed except loggin, markdown and times should work as listed from v0.10.0 of handlebar helpers.

**Comment by wobba** [comment] 2021-10-14 12:43
Closing as unique and pluck is working as intended in recent v3/v4.

**Closed by wobba** 2021-10-14 12:43 UTC
Labels: documentation, v3
