### ISSUE TITLE
Bug/Question: Duplicate Refiners in the “Search Filters” webpart when you have a Term Translated in Different Languages

### ISSUE THREAD

**Issue by mahmoudhhassan** [microsoft-search/pnp-modern-search#510] opened 2020-10-07 10:42 UTC
**Version used**
Ex: 3.10

**Describe the bug**
Let’s say that you have a term in your term store called **“Car”** and you translated this in German to be **“Auto”**. And you have 2 authors one with default language English and the other one with default language German. The 2 users tagged 2 pages with the same Term “Car/Auto”. But as SP will display the correct translation for the term based on the user langue the first page will be tagged with Car and the other will be tagged with Auto which is the same term at the end.

Because SP search index save the exact term with the exact translation in the managed property the first page will be tagged with **“L0|#0f95d1fdf-781f-42f4-99f9-c656c1341b2e, Car”** and the second one will be tagged with **“L0|#0f95d1fdf-781f-42f4-99f9-c656c1341b2e, Auto”** as an example, and as you can see it will has the **same id but with different text**.

When you use the “Search Filters” you will find 2 Refiners items one for the Car and one for Auto and if you used the localization feature of the webpart and you are an English user you will find the 2 Refiners named Car as the webpart will localize the Auto refiner for you.

**Expected behavior**
Is there in any way to group these 2 refiners together and make them appear as a single refiner?! As at the end it’s the same term but with different translation?

**Comment by mahmoudhamed** [comment] 2020-10-07 10:45
@wobba Not sure if you can comment on this issue. It looks like its by design and this will need code change to group the 2 refiners together what do you think?

**Comment by perritoMedia** [comment] 2020-10-08 14:05
Yes I want a fix for this too.  

Basically my field, groups, is showing duplicate refiners for each of the following records but it should just show the Interns checkbox once.

L0|#509e7321-8f4c-4664-9ffc-f2e09d9d7a37|Interns
L0|#509e7321-8f4c-4664-9ffc-f2e09d9d7a37|Interns;
L0|#509e7321-8f4c-4664-9ffc-f2e09d9d7a37|Interns;L0|#f1222ba2-ac5f-4270-877a-d79469ec46f3|Leadership

![image-20201007-102538](https://user-images.githubusercontent.com/4068044/95469460-945fda00-0977-11eb-96b8-3020171931ce.png)

**Comment by wobba** [comment] 2020-10-09 14:34
I'm pretty sure the behavior should be and at least used to be that the term got stored using the default language label. Which crawled property/managed property mapping are you looking at @mahmoudhamed? And I'll try to set up and test myself.

**Comment by wobba** [comment] 2020-10-09 14:36
@perritoMedia your issue is related to how it's indexed, not how we handle it in search. We cannot/or should not collapse multiple values with trimming logic imo.

**Comment by wobba** [comment] 2020-10-09 15:03
@mahmoudhamed This is the behavior I see and is probably correct. I just haven't checked it.

The term label is indexed using the default language of the site where it's used. So in my case, even though my term store is default Norwegian, I get Norwegian labels stored (regardless of my user UX language), as the sites default language is Norwegian.

If you have multiple sites, with different default languages you will get this issue. Does what you see match this behavior?

**Comment by mahmoudhamed** [comment] 2020-10-09 15:08
@wobba Yes, this is maybe the case I thought its because of the author language DE the term is saved with this language. But maybe it make more sense because yes I have different sites with different default languages and the DE for example comes from a site with DE language. But with that have been said do you think we can solve this, or we will need to live with it?!

**Comment by wobba** [comment] 2020-10-09 15:18
@mahmoudhamed we could in theory add collapsing logic and have it work. I'll bring this up internally as well as we're adding refiners to Microsoft Search, and the problem would be the same most if you used a label only crawled property.

**Comment by mahmoudhamed** [comment] 2020-10-09 15:29
@wobba Okay, great thanks for pushing this forward!

**Comment by NiklasMollberg** [comment] 2020-11-03 13:00
Just to confirm the problem when we have one site with default language SE and all others are EN.
The content from Agriculture (SE site) doesn't look good.

![image](https://user-images.githubusercontent.com/73890214/97988260-f8da5180-1ddc-11eb-8233-5556de2871e7.png)

**Comment by wobba** [comment] 2023-05-27 12:31
v3 no longer maintained

**Closed by wobba** 2023-05-27 12:31 UTC
Labels: enhancement
