### ISSUE TITLE
Can't implement registered custom Handlebars helpers anywhere.

### ISSUE THREAD

**Issue by MKGy** [microsoft-search/pnp-modern-search#594] opened 2020-12-03 14:09 UTC
!! Check existing issues before logging new ones !!

**Version used**
feature/v4

**Describe the bug**
search-extensibility-demo has a default custom Hundlebar helper called 'myHelper'. When I try to call it on some values in searchResults I get the message "Error: Missing helper: "myHelper".

**To Reproduce**
1.   Clone feature/v4 branch
2.   Navigate to folder search-extensibility
3.   run npm i
4.   run gulp bundle
5.   run npm link
6.   Navigate to folder search-extensibility-demo
7.   run npm i
8.   run npm link @pnp/modern-search-extensibility
9.   run gulp bundle
10. run gulp bundle --ship
11. run gulp package --ship
12. add the solution to the global catalog
13. select the checkbox "Make this solution available to all sites in the organization"
14. register my manifest ID in the target Web Part instance
15. add a column for the details list layout 
16. make adjustment to column value by implementing the default custom Handlebars helper "myHelper"  

**Expected behavior**
By definition "myHelper" should convert  a string-value to lowercase.

**Screenshots**

![image](https://user-images.githubusercontent.com/64076713/101024645-b12e1d80-3574-11eb-9f74-6577b3aa8dd8.png)
![image](https://user-images.githubusercontent.com/64076713/101024799-e76b9d00-3574-11eb-9f7a-b3a8d13d74a9.png)
![image](https://user-images.githubusercontent.com/64076713/101024900-11bd5a80-3575-11eb-815f-a19ec8578c64.png)
![image](https://user-images.githubusercontent.com/64076713/101025234-95774700-3575-11eb-8527-c9bb6d7ad8d1.png)

**Desktop (please complete the following information):**
 - Browser : chrome, edge

**Additional context**
none

**Comment by FranckyC** [comment] 2020-12-04 18:33
Hi @MKGy, can you try with parenthesis `{{myHelper (slot @root.slots.Language)}}`. I'm not able to reproduce this issue :(. Also, please try with the latest v4 branch code. We had some issues with latest commits so it may explain.

**Comment by MKGy** [comment] 2020-12-07 10:13
I have tried with the latest v4 branch code and also used the syntaxes {{myHelper (slot @root.slots.Language)}} and {{myHelper slot @root.slots.Language}}
However, the problem still remains, namely that helper is missing.

**Comment by MKGy** [comment] 2020-12-07 12:38
I have created a new SharePoint Framework project of type 'Library' with yo @microsoft/sharepoint. I linked it with the  @pnp/modern-search-extensibility library. In the main entry point, I implemented the IExtensibilityLibrary interface and provided the necessary methods returning empty arrays  for those extensions that I don't need now. Inside the method registerHandlebarsCustomization() I registered my own custom Handlebars helper called "iliToUpper". Then I called this method from Column value (under "Managed columns")using {{iliToUpper (slot item @root.slots.Language)}}.   
Similarly I called the custom helper "myHelper" from search-extensibility-demo using {{myHelper (slot item @root.slots.Language)}}
I have registered the GUID of both extension libraries in my web part and saved it.
In the screenshoot below you can see the outcomes of the method calls  under the columns  iLiHelper and MyHelper respectively.

It seems neither the demo extensibility library nor my own extensibility library is working properly. Hence, it is not possible to call a custom Handlebars helper on a value.

****Screenshot ****
![image](https://user-images.githubusercontent.com/64076713/101350145-c5349080-388e-11eb-84d4-132c65cfc9e6.png)

**Comment by FranckyC** [comment] 2020-12-07 14:25
What if you use the helper in the main template instead of a column? Does it work?

**Comment by FranckyC** [comment] 2020-12-11 19:55
@MKGy Ok I think I know what is going on. You are probably using the v3 search results Web Part and not the v4...I tried to run your scenario from scratch and it works fine. Make sure you selected "PnP - Search Results" Web Part and not "Search Results". These are not the same. Let me know.

**Comment by FranckyC** [comment] 2020-12-11 20:05
> 
> 
> @MKGy Ok I think I know what is going on. You are probably using the v3 search results Web Part and not the v4...I tried to run your scenario from scratch and it works fine. Make sure you selected "PnP - Search Results" Web Part and not "Search Results". These are not the same. Let me know.

Ok nevermind, I thought according to the first screenshot it was the v3 due to the default sortable "Title" column but the scond screenshot looks like v4. @wobba @MakingThingsWorkToronto can you try to deploy and use the extensibility demo project. I'm not able to reproduce this issue.

**Comment by MKGy** [comment] 2020-12-16 14:36
@FranckyC  I put your suggestion into practice and it seems to work fine.
I did the following:

For webpart "General results"
1. select layout "Custom"
2. select layout option " 
1. inside this template create a div with an orange background
2. call the custom Handlebars.js helper "myHelper" from within this div as follows: 
                  <div id="test">{{ myHelper (slot item @root.slots.Language)}}</div>
![image](https://user-images.githubusercontent.com/64076713/102361910-0b3ad400-3fb4-11eb-8afe-3e5f32d9d782.png)


Note: the slot 'Language' is already added to Layout slots.
![image](https://user-images.githubusercontent.com/64076713/102359943-b6965980-3fb1-11eb-980d-7ca1a7e3aa97.png)
Also the value of this slot is activated
![image](https://user-images.githubusercontent.com/64076713/102360232-0bd26b00-3fb2-11eb-8a35-9f1d5754e6a9.png)

Outcome of "General results": This **worked fine** as you can see in the below screenshot  ***:

screenshot***
![image](https://user-images.githubusercontent.com/64076713/102358652-0bd16b80-3fb0-11eb-85d3-10840baad3b5.png)

**Comment by MKGy** [comment] 2020-12-16 14:41
The problem arises when I want to call the Handlebars.js halper from the Manage columns of  template "Detail List"

For webpart "Titles"
1.select layout "Details List"
2.select layout option "Manage columns"
![image](https://user-images.githubusercontent.com/64076713/102357943-3242d700-3faf-11eb-86b4-ff882f79c12d.png)
3.Edit handlebars expression to {{ myHelper (slot item @root.slots.Language)}}
![image](https://user-images.githubusercontent.com/64076713/102361234-4a1c5a00-3fb3-11eb-9601-5269140208c8.png)

Note: the slot 'Language' is already added to Layout slots.
![image](https://user-images.githubusercontent.com/64076713/102359689-65866580-3fb1-11eb-9f15-6fffae6356f9.png)
Also the value of this slot is activated
![image](https://user-images.githubusercontent.com/64076713/102360401-420fea80-3fb2-11eb-80f6-5a4ffe7e23f1.png)

Outcome of "Titles":
![image](https://user-images.githubusercontent.com/64076713/102362852-235f2300-3fb5-11eb-95ea-20a64e8d9324.png)

**Comment by tripleseven73** [comment] 2021-03-21 15:14
I ran into the same "Error: Missing helper: ..." problem and discovered it is caused by adding .a "PnP - Search Filters" Web Part to the page.

Steps to reproduce:

- add new blank modern site page
- optional: add two columns section layout
- add PnP Search Results Web Part (to left column of two columns section)
- configure PnP Search Results Web Part to the point that it is displaying results using detail list
- add manifest ID of custom handlebar library to PnP Search Results Web Part
- add column to detail list using a handlebar helper of custom handlebar library
- publish the page
- hit CTRL + F5 for full refresh
- verify handlebar helper is working
- add PnP Search Filters Web Part (to right column of two columns section)
- publish the page without configuring / connecting Search Filters Web Part
- hit CTRL + F5 for full refresh
- Search Results Web Part is displaying "Error: Missing helper: ..." in column using custom handlebar helper
- remove Search Filters Web Part
- publish the page
- hit CTRL + F5 for full refresh
- Search Results Web Part is again working as expected

Behavior observed on several pages in SP Online using PnP Modern Search 4.1.0 (March 2021)(latest version as of moment of writing).

Update:
In a site page with two Search Result Web Parts and one Search Filter Web Part, the "Error: Missing helper: ..." can be resolved by dragging the Search Filters Web Part to a different location on the page (e.g. by dragging is to the bottom of the page).

**Comment by ayblanchet** [comment] 2021-05-04 09:02
Hi,

I confirm, I still have the same error "Error: Missing helper" with or without searchFilters. It's impossible to use custom helper.
The extends librairy is correctly load, but the helper is not recover.

**Comment by wobba** [comment] 2021-05-24 16:18
@tripleseven73 I can repro and think it's related to web parts perhaps having the same handlebar instance/service key. @FranckyC do you have any ideas? Seems the web components are not getting the correct instance when running `this._serviceScope.consume<ITemplateService>(TemplateService.ServiceKey);` as the instance is missing the registered helpers.

**Comment by wobba** [comment] 2021-05-24 16:49
Fixed it by rearranging some code to ensure loading sequence is not causing race conditions :)

**Comment by wobba** [comment] 2021-05-25 19:11
Seems still an issue, just triggers less :(

**Comment by wobba** [comment] 2021-05-27 15:08
Added a hack workaround for now. Weird stuff.

**Closed by wobba** 2021-05-27 15:08 UTC
Labels: bug, v4

**Comment by FranckyC** [comment] 2021-06-23 19:05
Found the root cause. Should be OK for the next release.
