### ISSUE TITLE
Verticals WebPart - Active Link when using querystring variables

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#1528] opened 2021-11-16 15:45 UTC
**Version used**
4.4.1

**Describe the bug**
When using the Verticals WebPart with QueryString variables in the URL the active link is always the first vertical.

Vertical 1: https://<tenant>.sharepoint.com/sitepages/page.aspx?v=1 
Vertical 2: https://<tenant>.sharepoint.com/sitepages/page.aspx?v=2

In the above example even if the user clicks Vertical 2, it is Vertical 1 that remains as the active link (Underlined).

It would be nice if the active link changed onselect, so the user could easily see which vertical they have selected.

The only workaround I can see right now is to create a duplicate page for each vertical and perhaps change the order of the verticals. This seems to defeat the whole point of using a QueryString in the URL.

**Comment by wobba** [comment] 2021-11-16 17:33
It's not implemented in v4. Duplicate of #732

**Closed by wobba** 2021-11-16 17:33 UTC
