### ISSUE TITLE
Every other search preview image does not display an image

### ISSUE THREAD

**Issue by jensotto** [microsoft-search/pnp-modern-search#784] opened 2021-02-19 11:05 UTC
**Version used**
Ex: 4.00

**Describe the bug**
The search results preview image shows missing image for every other search result.

**To Reproduce**
Add a search result web part and set the layout to list. 
Connect a search box web part and perform a search that returns some docx files.

**Expected behavior**
Every preview image should render a proper document preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/13898671/108496514-72258380-72aa-11eb-8e8b-2f0ecb2055fd.png)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
Image src for working image:
https://<siteurl>/_api/v2.1/sites/90dd7a6a-87cd-4a3b-b7a0-753705119a38/lists/04da99a1-e95a-46b5-80ae-051b650f79cb/items/5d56f256-6422-452c-a073-16d00f050270/driveItem/thumbnails/0/large/content?preferNoRedirect=true

Image src property for failing image (I shortened down the base64 encoded string):
data:image/png;base64,iVBORw0KGgo....xIes1AAAAAElFTkSuQmCC

**Comment by wobba** [comment] 2021-02-19 11:08
Likely a duplicate of #689, can you test the dev branch?

**Comment by jensotto** [comment] 2021-02-19 11:10
Yes, seems like a duplicate. I didn't find that when searching for possible duplicates. Sorry for that. I'll try to see if I can test the dev branch, but it might take some time for me to do so unfortunately.

**Comment by jensotto** [comment] 2021-02-19 14:41
I tried to install it from the develop branch but I got this error in the search result web part.
![image](https://user-images.githubusercontent.com/13898671/108518415-d22b2280-72c8-11eb-9ad6-d9412b9b842e.png)

**Comment by MakingThingsWorkToronto** [comment] 2021-02-19 15:36
I changed the byPath method in the helpers > ObjectHelper to always return a string as follows:

     ```
/**
     * Get object proeprty value by its deep path.
     * @param object the object containg the property path
     * @param path the property path to get
     * @returns the property value if found, undefined otherwise
     */
    public static byPath(object: any, path: string): any  {

        if (path && object) {

            try {
                // Returns the value "as is". If it is an array, values will be separated by a comma (default delimiter for the toString() method)
                const value = jspath.apply(`.${path}`,object); // this can return an array.
                if(isArray(value)) return value.join(); // check for array and return as comma delimited string.
                return value; // not an array return value
            } catch (error) {
                // Case when unexpected string or tokens are passed in the path
                return null;
            }
                 
        } else {
            return undefined;
        }
    }
```

Should resolve the issue.

**Comment by wobba** [comment] 2021-02-20 14:18
@FranckyC this might relate to the change in this method for arrays.

**Comment by FranckyC** [comment] 2021-02-21 01:42
@wobba Yes, jsut forgot jsPath returns always an array.... I will update the method to deal will all types. @MakingThingsWorkToronto thanks for the hint!

**Comment by FranckyC** [comment] 2021-02-21 21:12
@jensotto should be fixed in the dev branch. Can you confirm?

**Comment by jensotto** [comment] 2021-02-22 06:22
@FranckyC Yes, the issue is now fixed.
@wobba dev branch fixed my issue.

**Closed** 2021-02-22 09:06 UTC
