### ISSUE TITLE
Filtering/removing people results or filtering by user group

### ISSUE THREAD

**Issue by mthanos7** [microsoft-search/pnp-modern-search#1069] opened 2021-06-11 16:51 UTC
**Version used**
Ex: 4.22

**Describe the bug**
This is less a bug and more asking for advice for how to handle unwanted people results. When Result Source ID is set to LocalPeopleResults, and the People layout is selected, there are many empty user rows that show up in the results alongside actual user results that display proper information (see users in screenshot with blacked out information). These are likely test accounts that were made for the site and are probably showing up as dead results because they don't have a representation in the Microsoft Graph. Is there functionality in the Search Results web part to filter these test users out or group results by certain Active Directory groups? Or if not, would you have advice on how to achieve this result outside of the web part functions?

**To Reproduce**
Add Search Results Web Part
Select LocalPeopleResults as Result Source ID;
Add * to query template;
Select People in available layouts;
Enable Show Persona Card on Hover
Hover over Persons with proper data showing (hover working correctly)
See blank test users with no data

**Expected behavior**
Looking for a way to filter out certain users not represented in the Microsoft Graph or filter by Active Directory user groups

**Screenshots**
![people](https://user-images.githubusercontent.com/22053481/121722715-a3250080-cab3-11eb-9e3b-f8003edddb3a.PNG)

**Desktop (please complete the following information):**
 - Brave browser

**Comment by wobba** [comment] 2021-06-11 18:24
You can exclude with KQL similar to https://www.techmikael.com/2018/01/excluding-sharepoint-online-service.html

You just need to find which property to use to exclude them. Do they have a convention, maybe exclude external accounts etc. (https://www.rlvision.com/blog/excluding-external-users-from-search-results-in-sharepoint-online/)

**Comment by wobba** [comment] 2021-06-16 17:45
You can add the KQL to the query, query template or to a custom result source (for SP provider). Where you add it is up to you and it ends up the same down stream anyways 🙂

**Comment by mthanos7** [comment] 2021-06-16 18:20
Thank you. Would you have a suggestion/explanation for why my test users are now showing up completely as blank rows with the "person icon" as seen in the above screenshot? Is it because they may not have representations in the Microsoft Graph? In the previous v4 version, the test users' names showed up in the results but now I can't see them. I was hoping to go through the users I want to exclude and pick up on any common naming convention I could add to the query but I can't see their names in the results now.

**Comment by wobba** [comment] 2021-06-17 11:33
@mthanos7 if your test users are in AAD, they should work. But hard to say what the issue is without seeing the response data and knowing the setup.

**Comment by jamesmallalieu** [comment] 2021-06-18 07:57
I am having the same issue. When the persona card is enabled, unlicensed accounts appear with just the head icon, when it is disabled, the account appears as per others. 

It looks like there is a way to remove inactive/disabled users from the results using the SPS-HideFromAddressLists managed property however a regular script might be required to ensure this value is set correctly within SharePoint (see [https://global-sharepoint.com/sharepoint-online/hide-disable-or-inactive-users-from-sharepoint-online-search/]).

**Comment by wobba** [comment] 2021-06-20 15:09
I'll close this as it relates to Graph Toolkit and how to ensure you include/exclude the people you want in search.

**Closed by wobba** 2021-06-20 15:09 UTC
Labels: question, v4
