### ISSUE TITLE
Webparts won't work on SharePoint mobile

### ISSUE THREAD

**Issue by haecker-felix** [microsoft-search/pnp-modern-search#749] opened 2021-02-05 11:10 UTC
**Version used**
4.0.0

**Describe the bug**
The `PnP Search Box` and `PnP Search Results` web parts won't load on SharePoint mobile. It doesn't matter if I use the SharePoint iOS app, or use the website directly in Safari. 

Logs:

```
SPLoaderError.loadComponentError]:
Failed to load component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Failed to load entry point from component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Error loading https://component-id.invalid/544c1372-42df-47c3-94d6-017428cd2baf_4.0.0
https://component-id.invalid/544c1372-42df-47c3-94d6-017428cd2baf_4.0.0 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.

INNERERROR:
Failed to load entry point from component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Error loading https://component-id.invalid/544c1372-42df-47c3-94d6-017428cd2baf_4.0.0
https://component-id.invalid/544c1372-42df-47c3-94d6-017428cd2baf_4.0.0 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.
CALLSTACK:
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_350bde6e6775e46d786febff91acc5c3.js:1:873039
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_350bde6e6775e46d786febff91acc5c3.js:1:1017270
t@[native code]
https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_350bde6e6775e46d786febff91acc5c3.js:1:1040614
https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_de-de_06fb90fbb103ba8a0bb1.js:1:66137
promiseReactionJob@[native code]


SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Failed to load entry point from component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Error loading https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.0.0
https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.0.0 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.

INNERERROR:
Failed to load entry point from component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Error loading https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.0.0
https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.0.0 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.
CALLSTACK:
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_350bde6e6775e46d786febff91acc5c3.js:1:873039
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_350bde6e6775e46d786febff91acc5c3.js:1:1017270
t@[native code]
https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_350bde6e6775e46d786febff91acc5c3.js:1:1040614
https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_de-de_06fb90fbb103ba8a0bb1.js:1:66137
promiseReactionJob@[native code] 
```

The pages are working without any problem on desktop (tested with Chromium Edge / Firefox) with the same user account. I'm not a guest user. 

**To Reproduce**
1. Open webpage with pnp modern search web parts included on iOS Safari / SharePoint iOS App

**Expected behavior**
Working web parts instead of error message :) 

**Desktop (please complete the following information):**
 - iOS SharePoint app
 - iOS Safari Browser

**Comment by wobba** [comment] 2021-02-05 14:40
Duplicate of #685

**Closed by wobba** 2021-02-05 14:40 UTC
