### ISSUE TITLE
Bug in Search Results Webpart

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#238] opened 2020-05-05 11:06 UTC
**Version used**
Version 3.12.0 - downloaded today (with the fixed version number)

**Describe the bug**
Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"A null value was found for the property named 'Direction', which has the expected type 'Edm.Int32[Nullable=False]'. The expected type 'Edm.Int32[Nullable=False]' does not allow null values."}}}

**To Reproduce**
I have used the workbench and added only the Search Results Webpart.
As Search query keywords I used test
On second page of the configuration no change.
On third panel initially the webpart still renders okay, but if i switch to People layout, the error t comes up.
Below the pictures i describe an other way to get to the error.
![Bug-V3 12-01](https://user-images.githubusercontent.com/62948158/81059557-eb491b00-8ed0-11ea-89ce-3b03a9faf714.PNG)
![Bug-V3 12-02](https://user-images.githubusercontent.com/62948158/81059571-eedca200-8ed0-11ea-87db-d69270e629d8.PNG)
![Bug-V3 12-03](https://user-images.githubusercontent.com/62948158/81059576-f13efc00-8ed0-11ea-8aab-3d352b8e8a06.PNG)

**To Reproduce**
Simple add the _Search Results Webpart_ to the workbench.
As **Search query keywords** use **test**
On second page of configuration panel enter as _Result source_ b09a7990-05ea-4af9-81ef-edfab16c4e31 ( Local People Results )
The error shows immediately up. If I save the configuration and reload the page, then it is rendered without of a error.

**Information of Workbench _Web Part Data - Modern Pages_**

[{"controlType":3,"id":"a061c8e4-b2a9-436b-a3c4-a9688793bc8b","position":{"zoneIndex":1,"sectionIndex":1,"controlIndex":1,"layoutIndex":1},"webPartId":"42ad2740-3c60-49cf-971a-c44e33511b93","webPartData":{"id":"42ad2740-3c60-49cf-971a-c44e33511b93","instanceId":"a061c8e4-b2a9-436b-a3c4-a9688793bc8b","title":"Search Results","description":"Displays search results","serverProcessedContent":{"htmlStrings":{},"searchablePlainTexts":{},"imageSources":{},"links":{}},"dynamicDataPaths":{},"dynamicDataValues":{"queryKeywords":"test"},"dataVersion":"1.0","properties":{"queryTemplate":"{searchTerms}","sortList":[{"sortField":"Created","sortDirection":1},{"sortField":"Size","sortDirection":2}],"selectedProperties":"Title,Path,Created,Filename,SiteLogo,PreviewUrl,PictureThumbnailURL,ServerRedirectedPreviewURL,ServerRedirectedURL,HitHighlightedSummary,FileType,contentclass,ServerRedirectedEmbedURL,ParentLink,DefaultEncodingURL,owstaxidmetadataalltagsinfo,Author,AuthorOWSUSER,SPSiteUrl,SiteTitle,IsContainer,IsListItem,HtmlFileType,SiteId,WebId,UniqueID,OriginalPath,FileExtension,NormSiteID,NormListID,NormUniqueID,AccountName,FirstName,LastName,Department,JobTitle,WorkPhone","enableQueryRules":false,"includeOneDriveResults":false,"showBlank":true,"showResultsCount":true,"webPartTitle":"","enableLocalization":true,"useDefaultSearchQuery":false,"resultTypes":[],"useExternalRefinersDisplay":false,"useExternalPaginationDisplay":false,"appliedRefiners":[],"refinersConfiguration":[],"sortableFields":[],"synonymList":[],"searchQueryLanguage":-1,"templateParameters":{"detailsListColumns":[{"name":"Title","value":"Title","useHandlebarsExpr":false,"minWidth":"80","maxWidth":"300","enableSorting":true,"isMultiline":false,"isResizable":true,"isResultItemLink":true},{"name":"Created","value":"{{getDate Created 'LL'}}","useHandlebarsExpr":true,"minWidth":"80","maxWidth":"120","enableSorting":false,"isMultiline":false,"isResizable":false,"isResultItemLink":false},{"name":"Summary","value":"{{getSummary HitHighlightedSummary}}","useHandlebarsExpr":true,"minWidth":"80","maxWidth":"300","enableSorting":false,"isMultiline":true,"isResizable":false,"isResultItemLink":false}],"showFileIcon":true,"peopleFields":[{"name":"Image Url","field":"imageUrl","value":"{{#with (split AccountName '|')}}/_layouts/15/userphoto.aspx?size=L&username={{[2]}}{{/with}}","useHandlebarsExpr":true,"supportHtml":false},{"name":"Primary Text","field":"text","value":"{{FirstName}} {{LastName}}","useHandlebarsExpr":true,"supportHtml":false},{"name":"Secondary Text","field":"secondaryText","value":"JobTitle","useHandlebarsExpr":false,"supportHtml":false},{"name":"Tertiary Text","field":"tertiaryText","value":"{{#with (split AccountName '|')}}{{[2]}}{{/with}}","useHandlebarsExpr":true,"supportHtml":false},{"name":"Optional Text","field":"optionalText","value":"WorkPhone","useHandlebarsExpr":false,"supportHtml":false}],"personaSize":14},"queryModifiers":[],"refinementFilters":"","paging":{"itemsCountPerPage":10,"pagingRange":5,"showPaging":true,"hideDisabled":true,"hideFirstLastPages":false,"hideNavigation":false},"selectedLayout":5,"defaultSearchQuery":"","resultSourceId":"b09a7990-05ea-4af9-81ef-edfab16c4e31"}},"emphasis":{},"reservedHeight":2170,"reservedWidth":727,"addedFromPersistedData":true}]

**Comment by luismanez** [comment] 2020-05-06 06:05
Think is this same bug https://github.com/microsoft-search/pnp-modern-search/issues/237

**Comment by wobba** [comment] 2020-05-06 13:31
Duplicate of #237

**Closed by wobba** 2020-05-06 13:31 UTC
Labels: bug
