### ISSUE TITLE
Need help on the usage of "Enable Localization" for filters on metadata fields with translated labels

### ISSUE THREAD

**Issue by nmtoblum** [microsoft-search/pnp-modern-search#786] opened 2021-02-19 15:41 UTC
**Version used**
Ex: 4.0.0

**Describe the bug**
We have a managed metadata field called "ContentLanguage" (single select) that is available and filled on many pages. The term set used there has terms with translated labels. We want to use this field as a refiner/filter.  
Initially we used "ows_ContentLanguage" (mapped to "RefinableString08") for the filter, but we had many duplicates in the filters. 

According to the documentation for "Enable Localization" I mapped then "ows_taxId_ContentLanguage" to "RefinableString09" and also configured a filter for "**Auto**RefinableString09" as seen here:  
![image](https://user-images.githubusercontent.com/18660238/108524995-ec1c3380-72cf-11eb-90a6-21e8ca8149d7.png)
![image](https://user-images.githubusercontent.com/18660238/108524096-f5f16700-72ce-11eb-846a-8dd0c0c22b18.png)

The result is as shown here:
![image](https://user-images.githubusercontent.com/18660238/108524409-48328800-72cf-11eb-8e4f-454d1c9c83a2.png)

For "ows_ContentLanguage/RefinableString08" we see duplicates, but also Translations. For "ows_taxId_ContentLanguage/RefinableString09" we see duplicates, but way less results what I find a bit strange because the total number should correlate with both properties. No results to "**Auto**RefinableString09".

"Enable Localization" is active in the results web part.

**To Reproduce**
See above

**Expected behavior**
No duplicate filter items should show up.

**Screenshots**
See above

**Desktop (please complete the following information):**
Tested with chrome, new edge.

**Additional context**
First I need to understand if this is some kind of misconfiguration on my side or something is wrong with the web parts for this special case. Maybe you could help me on this. If you need further informations, let me know.

Greetings
Tobias

**Comment by FranckyC** [comment] 2021-02-22 01:05
Hi @nmtoblum, for the translations, we actually use the `ows_taxId_xxx` crawled propreties simply because they contains IDs of the underlying term. With the ID, we are able to get the term label in the current UI language. FYI, the `ows_xxx` properties only contain the label of the term **at the time the item was updated and according to the current UI language**. It means if an user with current UI language "English" updates an item, the property value text will be "English". However if an other user with an other UI language save the same item, the valu won't be "English" but the label for his current UI language. For the search engine and `ows_xxx` properties, these are different refiner values despite they are actually the same.

Now, when you use `RefinableString09`, you clearly have duplicated terms in your term store with the same labels. We use IDs here and IDs are supposed to be unique. The different refiner counts may also suggest they have actually different IDs . I suggest you to verify in your term store what terms are duplicated. Also a good way to identify this is by refining your results with those tags and inspect the term id for each item.

Hope it helps.

**Comment by nmtoblum** [comment] 2021-02-22 09:49
Hi @FranckyC,

thank you for the clarification on how these crawled properties for managed metadata fields work. That's what I also guessed, but I didn't find definitive information on this. So I think I could forget about `ows_xxx / RefinableString08` as these won't work with translation and go for the `ows_taxId_xxx` approach.

I had a look on what the search request returns for `RefinementResults`.
This is what is returned for the Refiner:

<details>
 <summary>RefinementResults (click to expand)</summary>

```json
{
  "Entries": [
    {
      "RefinementCount": "621",
      "RefinementName": "GTSet|#8a7a2fdf-cfc8-4076-9bf8-1e09a39bed6d",
      "RefinementToken": "\"ǂǂ47545365747c2338613761326664662d636663382d343037362d396266382d316530396133396265643664\"",
      "RefinementValue": "GTSet|#8a7a2fdf-cfc8-4076-9bf8-1e09a39bed6d"
    },
    {
      "RefinementCount": "451",
      "RefinementName": "GP0|#1ea342dd-9592-4fc1-8828-f57a47eb3c60",
      "RefinementToken": "\"ǂǂ4750307c2331656133343264642d393539322d346663312d383832382d663537613437656233633630\"",
      "RefinementValue": "GP0|#1ea342dd-9592-4fc1-8828-f57a47eb3c60"
    },
    {
      "RefinementCount": "432",
      "RefinementName": "L0|#01ea342dd-9592-4fc1-8828-f57a47eb3c60|German",
      "RefinementToken": "\"ǂǂ4c307c233031656133343264642d393539322d346663312d383832382d6635376134376562336336307c4765726d616e\"",
      "RefinementValue": "L0|#01ea342dd-9592-4fc1-8828-f57a47eb3c60|German"
    },
    {
      "RefinementCount": "153",
      "RefinementName": "GP0|#3c184007-bca8-49fa-9b23-161a7ed89a11",
      "RefinementToken": "\"ǂǂ4750307c2333633138343030372d626361382d343966612d396232332d313631613765643839613131\"",
      "RefinementValue": "GP0|#3c184007-bca8-49fa-9b23-161a7ed89a11"
    },
    {
      "RefinementCount": "149",
      "RefinementName": "L0|#03c184007-bca8-49fa-9b23-161a7ed89a11|English",
      "RefinementToken": "\"ǂǂ4c307c233033633138343030372d626361382d343966612d396232332d3136316137656438396131317c456e676c697368\"",
      "RefinementValue": "L0|#03c184007-bca8-49fa-9b23-161a7ed89a11|English"
    },
    {
      "RefinementCount": "19",
      "RefinementName": "L0|#01ea342dd-9592-4fc1-8828-f57a47eb3c60|Deutsch",
      "RefinementToken": "\"ǂǂ4c307c233031656133343264642d393539322d346663312d383832382d6635376134376562336336307c44657574736368\"",
      "RefinementValue": "L0|#01ea342dd-9592-4fc1-8828-f57a47eb3c60|Deutsch"
    },
    {
      "RefinementCount": "14",
      "RefinementName": "GP0|#6a0da469-a3aa-4b64-8970-6617c4429a18",
      "RefinementToken": "\"ǂǂ4750307c2336613064613436392d613361612d346236342d383937302d363631376334343239613138\"",
      "RefinementValue": "GP0|#6a0da469-a3aa-4b64-8970-6617c4429a18"
    },
    {
      "RefinementCount": "12",
      "RefinementName": "L0|#06a0da469-a3aa-4b64-8970-6617c4429a18|French",
      "RefinementToken": "\"ǂǂ4c307c233036613064613436392d613361612d346236342d383937302d3636313763343432396131387c4672656e6368\"",
      "RefinementValue": "L0|#06a0da469-a3aa-4b64-8970-6617c4429a18|French"
    },
    {
      "RefinementCount": "4",
      "RefinementName": "L0|#03c184007-bca8-49fa-9b23-161a7ed89a11|Englisch",
      "RefinementToken": "\"ǂǂ4c307c233033633138343030372d626361382d343966612d396232332d3136316137656438396131317c456e676c69736368\"",
      "RefinementValue": "L0|#03c184007-bca8-49fa-9b23-161a7ed89a11|Englisch"
    },
    {
      "RefinementCount": "3",
      "RefinementName": "GP0|#e7c4fb20-a3a6-423f-9950-841a673ad3be",
      "RefinementToken": "\"ǂǂ4750307c2365376334666232302d613361362d343233662d393935302d383431613637336164336265\"",
      "RefinementValue": "GP0|#e7c4fb20-a3a6-423f-9950-841a673ad3be"
    },
    {
      "RefinementCount": "2",
      "RefinementName": "L0|#06a0da469-a3aa-4b64-8970-6617c4429a18|Französisch",
      "RefinementToken": "\"ǂǂ4c307c233036613064613436392d613361612d346236342d383937302d3636313763343432396131387c4672616e7ac3b67369736368\"",
      "RefinementValue": "L0|#06a0da469-a3aa-4b64-8970-6617c4429a18|Französisch"
    },
    {
      "RefinementCount": "2",
      "RefinementName": "L0|#0e7c4fb20-a3a6-423f-9950-841a673ad3be|Spanish",
      "RefinementToken": "\"ǂǂ4c307c233065376334666232302d613361362d343233662d393935302d3834316136373361643362657c5370616e697368\"",
      "RefinementValue": "L0|#0e7c4fb20-a3a6-423f-9950-841a673ad3be|Spanish"
    },
    {
      "RefinementCount": "1",
      "RefinementName": "L0|#0e7c4fb20-a3a6-423f-9950-841a673ad3be|Spanisch",
      "RefinementToken": "\"ǂǂ4c307c233065376334666232302d613361362d343233662d393935302d3834316136373361643362657c5370616e69736368\"",
      "RefinementValue": "L0|#0e7c4fb20-a3a6-423f-9950-841a673ad3be|Spanisch"
    }
  ],
  "Name": "RefinableString09"
}
```
</details>

This is, what is shown in the filters section for this result:
![image](https://user-images.githubusercontent.com/57751598/108688160-e2751480-74f7-11eb-9f7f-1fa9cbfb949d.png)

It looks as if the filters pick up only the results with `L0|#0`, not the ones with `GP0|#` that have the same term GUID. Do you have an idea where these originate from? Could these be safely ignored? It looks like the count for GP0 is always the sum of all counts for the L0 of a term.

But there are also two L0 with the same term GUID that appear as different entries in the filters:
- "L0|#03c184007-bca8-49fa-9b23-161a7ed89a11|English"
- "L0|#03c184007-bca8-49fa-9b23-161a7ed89a11|Englisch"

Both are translated in the filters to "Englisch", which is OK, because my UI language is set to german. But I think they shouldn't appear as different filters.

I hope that makes a bit clearer what happens here.

Greetings
Tobias

**Comment by wobba** [comment] 2021-02-28 17:18
@nmtoblum You get two values back because of the default language used on the sites differ. I'll tag this as an enhancement as we would need to add dedupe logic to join them into one in the UX.

**Comment by nmtoblum** [comment] 2021-03-01 14:33
@wobba Makes sense! I couldn't verify if the default language is different in this case, but as the GUID of both refiners is the same, it should be possible to dedupe them, I guess.
Thank you for taking care of it.

**Comment by MakingThingsWorkToronto** [comment] 2021-04-09 02:21
See #794. My inclination is we should be able to create pre-processed labels to apply via a custom filter templates. This could be  possible (and performant) if handlebars helpers were accessible to the filter template. Additionally, would solve other use cases like combining filters. My experience with V4 is custom helpers are not accessible within the filter template, nor are custom web components, and it is unclear if this is by design, or within the plans (or what mods would be acceptable to make it work). Giving a push here. Great work on v4.

**Comment by wobba** [comment] 2021-04-09 15:17
Making web components and custom helpers available in the filter wp should be doable - and a good solution.

**Comment by wobba** [comment] 2021-07-14 13:25
Closed as using custom helpers/components is tracked in #794

**Closed by wobba** 2021-07-14 13:25 UTC
Labels: enhancement, v4
