### ISSUE TITLE
Search results randomly failed with error code

### ISSUE THREAD

**Issue by Leighton365** [microsoft-search/pnp-modern-search#1914] opened 2022-03-08 12:42 UTC
### Check existing issues before logging new ones
If you are not using the latest version, triage your issue with the latest version before logging as we won't provide patches to older versions.

### Issues related to data mapping, e.g. SharePoint columns to crawled properties to managed properties should be asked in the discussion section.

**For any question regarding Web Parts usage, please use the ["Discussions"](https://github.com/microsoft-search/pnp-modern-search/discussions) tab instead of creating a new issue.**.

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 4.5

**Describe the bug**
We are seeing an error when searching in SharePoint using the PnP Search Web Parts.
Frequently, and randomly, the following message appears:
Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

I have attached a debug output of the error.

**To Reproduce**
1. Type in a search phrase.
2. See if issue occurs
3. if not, try adding refin
[PnP - Search with Error.txt](https://github.com/microsoft-search/pnp-modern-search/files/8206193/PnP.-.Search.with.Error.txt)
ers
4. Continue changing refiners or entering new search phrases.

**Expected behavior**
I would expect search results to be shown without any error messages

**Screenshots**

**Desktop (please complete the following information):**
Chrome
Edge

**Additional context**

**Comment by FranckyC** [comment] 2022-03-08 19:47
Duplicate of https://github.com/microsoft-search/pnp-modern-search/issues/675

**Closed by FranckyC** 2022-03-08 19:47 UTC
Labels: API
