### ISSUE TITLE
Filter on RefinableDecimal doesn't work well

### ISSUE THREAD

**Issue by FlorianVr** [microsoft-search/pnp-modern-search#2541] opened 2022-11-15 10:41 UTC
Version used:4.6.1.0

**Describe the bug**
I use a content type which contains specific properties for a project, especially amount properties in Number format.
I did a mapping between my properties Amount and a refinableDecimal property in order to use it in the web part "PNP - Search Results"
The displaying on  the web part "Result" is ok, but when I try to filter Amount values through web part "PNP - Search filters", the behavior is very strange. Indeed, if I select the range "1000 up to 6000", the web part return values outside the selected range.
If the amount value stored in my document Set has no decimal part, else the behavior seems ok.

**To Reproduce**
1. Do a mapping betwen a number property and refinableDecimal property
2. Add the refinableDecimal property in your PnP - Search result web part, and configure it to display the Refinabledecimal value
3. Configure PNP-Search filters web part to allow filtering on the RefinableDecimal property
4. Add several document set with different values of Amount (minus, integer, decimal, ...)
5. Select a range of value and notice the result

**Expected behavior**
To have documentSet corresponding to the selected filter (amount range)

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by wobba** [comment] 2022-11-15 21:06
Can you test this with classic web parts and see if the behavior is the same or not?

**Comment by FlorianVr** [comment] 2022-11-18 15:03
Hello,
What do you mean by "classic web part"? Do you talk about the web part named "Highlighted content"?

**Comment by wobba** [comment] 2022-11-18 17:22
I'm talking about the search web parts on classic SharePoint pages like if you go to https://tenant.sharepoint.com/search and search.

**Comment by datindy** [comment] 2023-02-20 05:02
I had the same issue, and followed the suggestion from @wobba above.  I can confirm that the issue exists in the classic web parts as well, so this is seemingly not a PnP modern search issue.

I had a currency column, mapped it to RefinableDecimalXX and was getting the behaviour described above.  I changed the mapping of the column to RefinableIntXX, and it worked fine.   Posting this here for anyone that runs into the same issue.

**Comment by wobba** [comment] 2023-02-21 16:25
Closing due to API issue and not web part issue.

**Closed** 2023-02-21 16:25 UTC
Labels: Needs: Triage, v4
