### ISSUE TITLE
Search Verticals are not correctly selected in the UI when using query string parameters to jump to a specific vertical

### ISSUE THREAD

**Issue by tandrasi** [microsoft-search/pnp-modern-search#3627] opened 2024-03-14 09:15 UTC
**Version used**
4.10.2

**Describe the bug**
When using a query string in the URL for the jumping to a given vertical, the vertical doesn't visually get selected in UI (but it is selected in the backend).

For example, when going to "/SitePages/Search.aspx?v=people", my web parts that should display when the "people" vertical is selected are indeed shown, but the **people vertical does not get underlined and bolded**.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to a preconfigured search page with search verticals;
2. Ensure search verticals are configured correctly based on the desired query string parameter ("v" by default);
3. Change the URL to include a query string parameter pointing to any configured vertical (i.e. "?v=people" or "&v=people");
4. Notice that the UI doesn't reflect that the desired vertical is selected, even though it actually is in the backend (seen through the visibility of the other web parts should only display when that particular vertical is selected).

**Expected behavior**
I expect that the vertical being passed as a parameter is selected in the UI via an underline and bolding of the vertical text.

**Screenshots**
The search verticals are configured to use "v" as the query string parameter:
<img width="317" alt="image" src="https://github.com/microsoft-search/pnp-modern-search/assets/72114492/9d3e0c7c-ab45-4a02-aa8b-8a3d890ef093">

My URL bar has the following /SitePages/Search.aspx?v=people and we can see that the "people" web parts are displayed, but the "people" vertical is not selected in the UI:
<img width="1032" alt="image" src="https://github.com/microsoft-search/pnp-modern-search/assets/72114492/8256f08b-eb6d-4ebe-83cb-2cd03e30861d">

**Desktop (please complete the following information):**
 - Edge (latest)

**Additional context**
This happens against all my verticals, along all sites and tenancies. This was a feature that used to work in previous versions!

**Comment by patrikhellgren** [comment] 2024-03-14 10:15
Dupe of #3452. Fixed in version [4.11 Pre-release](https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.11.0).

**Closed** 2024-03-14 16:06 UTC
