### ISSUE TITLE
V4.1 WebPart Error in SharePoint Mobile App iOS

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#913] opened 2021-04-06 06:47 UTC
**Version used**
Ex: 4.1

**Describe the bug**
The PnP Modern Search Results webparts are not loading in the latest version of the Microsoft SharePoint Mobile App on iOS. Reporting a "Failed to Load URL" error.

**Expected behavior**
WebParts should load

**Screenshots**
![image](https://user-images.githubusercontent.com/48433526/113669760-7bc94600-96b4-11eb-9361-7208b64a58f1.png)

IOS SharePoint Mobile App v4.27.1

**Comment by Tanddant** [comment] 2021-04-06 13:31
Does it load on desktop? - are you able to copy the entire stack trace?

**Comment by myatix** [comment] 2021-04-06 15:01
@Tanddant Yes it loads fine on the Desktop client. I haven't tried it on Mac OSX (Safari) or Android...

Stack trace below:

TECHNICAL DETAILS

[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/m365x439370.sharepoint.com/sites/AppCalalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-results-web-part_2b3177bc954c8cd497dd148ba416edb6.js' for resource 'modern-search-results-web-part' in component '544c1372-42df-47c3-94d6-017428cd2baf' (pnpSearchResultsWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/m365x439370.sharepoint.com/sites/AppCalalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-results-web-part_2b3177bc954c8cd497dd148ba416edb6.js' for resource 'modern-search-results-web-part' in component '544c1372-42df-47c3-94d6-017428cd2baf' (pnpSearchResultsWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

CALLSTACK:
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-gb_9831b43b1890dd1a0691283c30593273.js:65:19899
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-gb_9831b43b1890dd1a0691283c30593273.js:65:117990
t@[native code]
https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-gb_9831b43b1890dd1a0691283c30593273.js:65:155359
https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_2ebb0419bb86e53022fa.js:1:66000
promiseReactionJob@[native code]

**Comment by myatix** [comment] 2021-04-06 15:06
This looks to me like an issue with access to the Public CDN but do we need to configure something specific for the Mobile App to work? I didn't have this issue with the PnP Modern Search v4.0?

**Comment by myatix** [comment] 2021-04-07 07:34
I have now enabled the public CDN on my test tenant but this hasn't resolved the issue yet. Perhaps we have to wait a little longer.

If this is a requirement for the PnP Modern Search WebPart it should be documented.

PublicCdnEnabled                              : True
PublicCdnAllowedFileTypes               : CSS,EOT,GIF,ICO,JPEG,JPG,JS,MAP,PNG,SVG,TTF,WOFF
PublicCdnOrigins                              : {}

**Comment by wobba** [comment] 2021-04-07 17:43
Duplicate of #685

**Closed by wobba** 2021-04-07 17:43 UTC
