### ISSUE TITLE
Too many search results when using owstaxid filter field

### ISSUE THREAD

**Issue by h-h-o** [microsoft-search/pnp-modern-search#1824] opened 2022-02-11 15:41 UTC
**Version used**
v4.5.4

**Describe the bug**
After updating to v4.5.4 Search Results returns too much results when using an owstaxid based filter field.

I'm using owstaxid fields for filtering because this is a multi-language environment. Before updating to v4.5.4, when selecting a filter value, the correct number of results was returned, but now some additional results are returned. This is also visible in the filter selection (see screenshot 1 below), where Value1 was selected as filter value.

In addition I noticed that the URL filtering has changed which seems relatd to this issue.
Before upgrading to v4.5.4, the URL filter format was like this:
`f=[{"filterName":"owstaxidFieldName","values":[{"name":"Value1","value":"\"ǂǂlongnumber01\"","operator":0}],"operator":"and"}]`
After the upgrade, it looks like this:
`f=[{"filterName":"owstaxidFieldName","values":[{"name":"Value1","value":"or(\"ǂǂlongnumber02\",\"ǂǂlongnumber01\",L0|#GUID)","operator":0}],"operator":"or"}]#`
So an OR clause has been added with 2 extra values (one long number and one GUID) and operator has change from AND to OR.
The old URL filter format still works, but shows a different problem: the filter value is no longer recognized (see screenshot 2) and appears duplicated. But the number of returned results is correct

**To Reproduce**
1. Add a Term Set to the term Store (multi-language)
2. Link the Term Set to a custom column
3. Use it on some SharePoint data (in our case a mix of pages and documents)
4. Create a managed property (RefinableString) linked to the field
5. Setup a PnP Modern Search page with a Search Results and Search Filter web part
6. Add the owstaxidFieldName as a filter in the Filter web part
7. Select one of the values
8. Incorrect number of results is returned

**Expected behavior**
The correct (number of) results is returned based on the selected filter value

**Screenshots**
Screenshot 1
![image](https://user-images.githubusercontent.com/84455064/153613596-cbe22871-ad5a-406e-bbfd-4a4a218d8fac.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/84455064/153621130-3b1b0603-3f70-4b0f-8962-358a05c8910e.png)

**Desktop (please complete the following information):**
 - Windows (Edge and Firefox)

**Additional context**
We need to use the owstaxid fields because it is a multilanguage environment.
The problem occurs for all languages.

**Comment by FranckyC** [comment] 2022-02-13 12:41
Duplicate of #1797

**Closed by FranckyC** 2022-02-13 12:41 UTC
