### ISSUE TITLE
Search Results Web Part : Unable to navigate to 3rd/4th web part properties panel

### ISSUE THREAD

**Issue by brianpmccullough** [microsoft-search/pnp-modern-search#2412] opened 2022-10-05 13:42 UTC
**Version used**
Ex: 4.7

**Describe the bug**
Using Search Results web part, clicking through to the 3rd or 4th page of web part properties is not possible.  From second page, when clicking Next to navigate to 3rd page, it takes back to 1st page/panel.  Also console errors are displayed.

This is a new issue as we had users configuring this as recently as Friday, September 30, 2022 (today being Wednesday, October 5, 2022).

I thought it might be an issue with the SPO/SPFx infrastructure, but was able to create a simple 1.15 webpart with 4 property panel pages and am able to navigate to them.

4.6.1 is deployed to the Tenant App Catalog in this environment, but please note that 4.7 version of Modern Search Web Parts deployed to Site Collection App Catalog, so 4.7 is being used in this case.

**To Reproduce**
1. Ensure 4.7 Modern Search Web Parts are deployed to Site Collection App Catalog.
2. Add a Search Results web part to a page.
3. Attempt to navigate to the 3rd page of web part properties
4. Note the errors in console.

**Expected behavior**
Be able to navigate to 3rd and 4th page of web part properties.

**Screenshots**
![image001 (3)](https://user-images.githubusercontent.com/8305245/194075136-80c2dd15-6955-4ecc-a39c-0783050ea625.png)

![image002](https://user-images.githubusercontent.com/8305245/194075499-41065e3d-11e6-4022-9939-58fb2c3dda5a.png)

**Desktop (please complete the following information):**
 - Browser Chrome/Edge

**Additional context**
N/A

**Comment by arunakshi** [comment] 2022-10-05 14:35
I am also facing this issue with version 4.7. It was working fine for us yesterday. This issue appeared for us today only.

**Comment by Georg-Trixl** [comment] 2022-10-05 15:24
Same issue as well with Version 4.8.0 Beta 1
Error in Console, when clicking on Next (to page 3) : 

sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69 TypeError: Cannot set properties of undefined (setting '0')
    at Vt (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:28922)
    at uc (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:97983)
    at Xc (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:114143)
    at ad (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:115158)
    at sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:123087
    at gc (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:101087)
    at t.unmountComponentAtNode (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:123073)
    at t.componentWillUnmount (chunk.property-pane-component_none_ebbbdfff738361243578.js:1:13226)
    at hs (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:93065)
    at Ds (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:94855)

sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69 Uncaught TypeError: Cannot set properties of undefined (setting '0')
    at Vt (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:28922)
    at uc (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:97983)
    at Xc (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:114143)
    at ad (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:115158)
    at sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:123087
    at gc (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:101087)
    at t.unmountComponentAtNode (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:123073)
    at t.componentWillUnmount (chunk.property-pane-component_none_ebbbdfff738361243578.js:1:13226)
    at hs (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:93065)
    at Ds (sp-pages-assembly_en-gb_c870ae1704a834050a792d80919d5e25.js:69:94855)

**Comment by wobba** [comment] 2022-10-05 20:15
Curious if something has changed on the SPFx side on mount/unmount. Haven't been able to repro myself yet.

**Comment by wobba** [comment] 2022-10-05 20:16
Duplicate of #2405

**Closed by wobba** 2022-10-05 20:16 UTC
