### ISSUE TITLE
"Hmm.. looks like this file doesn't have a preview we can show you." on list items

### ISSUE THREAD

**Issue by Gennady-G** [microsoft-search/pnp-modern-search#1052] opened 2021-06-07 16:36 UTC
**Version used**
4.1.0.0

**Describe the bug**
Hi! I have a list with sample items

![b1-2021-06-07_203115](https://user-images.githubusercontent.com/5569346/121056376-310c9d00-c7cf-11eb-81c8-aa753427da4a.png)

And Modern Search WebParts, version 4. So I search list item title, and want to jump to display form of the item. But instead I get  this error, when I click on result link

![b22-2021-06-07_203413](https://user-images.githubusercontent.com/5569346/121056815-a7a99a80-c7cf-11eb-8969-dff9a9a47496.png)

![bbb3-2021-06-07_203534](https://user-images.githubusercontent.com/5569346/121056932-c740c300-c7cf-11eb-967b-6d87c0990c58.png)

**Desktop (please complete the following information):**
 - Browser Chrome **Canary** Version 93.0.4535.0 (Official Build) canary (64-bit)

**Comment by wobba** [comment] 2021-06-07 19:08
Duplicate of #945, fixed in v4.2

**Closed by wobba** 2021-06-07 19:08 UTC
