### ISSUE TITLE
Default vertical querystring parameter no longer working

### ISSUE THREAD

**Issue by nygarm1** [microsoft-search/pnp-modern-search#3454] opened 2024-01-15 20:34 UTC
**Version used**
4.10.1

**Describe the bug**
Vertical selection using the v query string parameter is not working in version 4.10.0.  
Example: <tenanturl> /sites/<sitename>/SitePages/SearchPage.aspx?v=Documents

The search result web parts set to "Display data only when the following vertical is selected" are working appropriately and reflect the vertical selected by the query string parameter. The verticals web part itself, however, does not reflect the currently selected vertical.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Build a search page with verticals web part and two or more search result web parts.
2. Configure two or more verticals with unique tab names and tab values. Is hyperlink = False (unchecked).
3. Configure two or more search results web parts such that they are connected to their respective vertical.  Give them a title reflective of the vertical.
4. Ensure version 4.9.3 of the PnP modern search web parts is installed.
5. Observe that query string parameter selection works as expected.
6. Install version 4.10.1 of the PnP modern search web parts 
7. Observe that query string parameter selection does not work as expected.
**Expected behavior**
Using query string parameters to select verticals should be reflected in the correct tab being marked as selected. For example: ?v=Documents should underline the Documents regardless of it's position in the tab list.

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/28449025/d6286a78-cb31-4b27-8ff7-97a3db27bc35)

**Desktop (please complete the following information):**
 - Chrome browser

**Comment by wobba** [comment] 2024-01-15 21:50
Duplicate of #3452

**Closed by wobba** 2024-01-15 21:50 UTC
