### ISSUE TITLE
Edit properties pane doesn't show more then 2 pages

### ISSUE THREAD

**Issue by Mgie77** [microsoft-search/pnp-modern-search#2414] opened 2022-10-06 08:29 UTC
**Version used**
Version: 4.8.0

This started from no where like a week ago.
When opening one of the following web parts, the paging always go between 1 to 2 and then 1 again: search result web part and filter web part.
Strangely enough - it doesn't happen in search box web part
This was tested both in Chrome and in Edge

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to edit page
2. Click on edit web part on the search result 
3. Clicking on "Next" after the second page it will get me back to the first page
4. No error is displayed on the page but there is an error after investigating the code - Important notice -I'm not a developer so this is kind of Klingon to me :)
5. Another weird behaviour -  if on the second properties page and clicking on "Available Layouts" on the second page makes everything in the properties go poof

**Expected behaviour**

**Screenshots**
first page seems to be fine
![image](https://user-images.githubusercontent.com/52484663/194258612-770c950c-74ad-4118-823b-798ee0636cab.png)

second page looks ok and working
![image](https://user-images.githubusercontent.com/52484663/194259189-56a15d3f-4ab0-4546-80f5-a28c51e98c0c.png)

clicking on "Next" will bring me back to the first configuration page:
![image](https://user-images.githubusercontent.com/52484663/194259453-0d6b792d-b263-47de-a407-cb0ab7bb8135.png)

Error in the console investigation:
![image](https://user-images.githubusercontent.com/52484663/194261615-bfe862e5-aaeb-49ee-804d-36504d036b1f.png)

Clicking on "Available Layouts" on the second page makes everything vanish:
![image](https://user-images.githubusercontent.com/52484663/194260471-684faa0b-41a4-4848-856d-8cdbb21beb86.png)

After clicking:
![image](https://user-images.githubusercontent.com/52484663/194260714-a5106079-8856-44a8-b002-b84bf055c87f.png)

**Desktop (please complete the following information):**
 - Chrome and Edge

**Comment by Jeroen00** [comment] 2022-10-06 10:02
This all of a sudden happens in our environment too. Cannot get to page 3 or 4! Version 4.6.1.0

**Comment by hpreis** [comment] 2022-10-06 10:50
I made the same experience: can not see/access 2 of the 4 Web Part configuration property pane pages: Connections & Extensibility
I have an old site with PnP Search 4.5.4.0, it works, but I can not edit parameters on page 3 and 4.
Updated to 4.8.0.0 and same incorrect behaviour.

**Comment by nogratonreup** [comment] 2022-10-06 13:21
Same thing for me, Cannot get to page 3 or 4! with Version 4.6.1.0 , upgrade to 4.7 same problem , first saw the problem Yesterday ( 05/10/2022)

**Comment by viveksbhat** [comment] 2022-10-06 23:26
I am experiencing the exact same problem. I am using the version 4.7. Not able to connect Search results web part with none of the other web parts. Spent the whole day trying to figure out the problem. But looking at this thread it appears to be part of another MS update. I have another site where I had previously configured all the setup and the search is working fine there. Just not able to configure a new page.

**Comment by phoob** [comment] 2022-10-07 05:52
Same here – tried both 4.7 and 4.8 beta on a developer tenant.

**Comment by wobba** [comment] 2022-10-09 12:39
Duplicate of #2405

**Closed by wobba** 2022-10-09 12:39 UTC
