### ISSUE TITLE
3 of 4 missing in PropertyPane

### ISSUE THREAD

**Issue by Parmstig** [microsoft-search/pnp-modern-search#2437] opened 2022-10-11 17:05 UTC
**Version used**
Version 4.7

**Describe the bug**
Page 3 of 4 webpart propertypane is missing, console reports "TypeError: Cannot set properties of undefined (setting '0')"

**To Reproduce**
1. Edit webpart
2. Click thru 1 -> 4

**Expected behavior**
See page 3

**Screenshots**

**Desktop (please complete the following information):**
Tested on several browsers, several computers

**Additional context**
There is a warning about a file that dont seem to exist in source DevTools failed to load source map: Could not load content for https://publiccdn.sharepointonline.com/****.sharepoint.com/sites/appcatalog/ClientSideAssets/a751ed7d-abc4-47c3-96d1-29272b2dac58/en-us.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Page 3 have been visible, after a little while it is just gone

**Comment by wobba** [comment] 2022-10-11 17:44
Duplicate of #2405, and resolution in https://github.com/SharePoint/sp-dev-docs/issues/8483#issuecomment-1273494688

**Closed by wobba** 2022-10-11 17:44 UTC
