### ISSUE TITLE
Search Results webparts not working in Mobile devices only

### ISSUE THREAD

**Issue by sithender1** [microsoft-search/pnp-modern-search#755] opened 2021-02-08 10:37 UTC
__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: V4

**Describe the bug**
We have multiple search results web parts on the Home page of a SharePoint site. The webparts are working as expcted when we access them on the browser from desktop/laptop. 

however, on the same site when we access on the IPhone, the webparts are not working, Giving an error.

I downloaded SPPKG file directly from the below link and uploaded my site collection Catalog.

https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.0.0

**To Reproduce**
1. Add the Search results webpart
2. Configure the properties
3. Test in Desktop Broswer
4. Test in Mobile 

**Expected behavior**
The Webpart should work in IPhone too.

**Screenshots**
![Searchwepart](https://user-images.githubusercontent.com/73110460/107207760-b56c3080-6a26-11eb-9843-5c5ff20dc2eb.JPG)

Mobile View

![Issue](https://user-images.githubusercontent.com/73110460/107208276-61158080-6a27-11eb-89ba-bbd494eb838f.png)
![issue 2](https://user-images.githubusercontent.com/73110460/107208491-aa65d000-6a27-11eb-975a-466615616ea2.png)

**Desktop (please complete the following information):**
 -Desktop Chrome, Safari

**Additional context**

**Comment by wobba** [comment] 2021-02-08 11:29
Duplicate of #639 and #685

**Closed by wobba** 2021-02-08 11:29 UTC
