### ISSUE TITLE
Search Result pages doesn`t display proper image.

### ISSUE THREAD

**Issue by Kostadin-cmd** [microsoft-search/pnp-modern-search#1604] opened 2021-12-07 08:41 UTC
Version used
3.16

Describe the bug
We have issue with Modern pnp Search Result web part v3.16
We are trying to display news pages from different site. The pages are displayed but the images are not displaying. (Please find the attached screenshot). This problem comes only to one specific site. Week ago it was working properly. It usually takes the header image of the page, but for some reason it stop working.

To Reproduce

1. Add a search results in a page.
2. Create a search query with PromotedState2 and Content type News Page
3. Create a News Page in the same site 
4. Add a header image of the page and publish it
5. In the Search Result web part The image doesn`t appear. (Pl

Expected behavior
The Header image of the News page should appear in Search Results Boxes.

Screenshots
![Search Result](https://user-images.githubusercontent.com/78485292/144995513-8280dcb6-036a-4450-a05a-cccf93cf469c.PNG)

**Comment by wobba** [comment] 2021-12-07 09:31
I don't have repro with the latest v3 https://github.com/microsoft-search/pnp-modern-search/releases/tag/v3.22.0. It it suddenly happened, then it's a data/API issue, not web part issue. Could be related to #1579.

**Comment by PzKfWg** [comment] 2021-12-07 18:18
Same thing happening here. Worked for a year. Suddenly, yesterday, we started getting site icons for some thumbnails. I did a full reindex and now every thumbnail has the site icon instead of the document preview/picture.

**Comment by schneika** [comment] 2021-12-08 15:27
Same here on all my tenants. Thumbail Preview always show the Site Logo instead of the Content Thumbail.

**Comment by wobba** [comment] 2021-12-08 19:58
Closing as duplicate of #1579.

**Closed by wobba** 2021-12-08 19:58 UTC
Labels: Needs: Triage, v3

**Comment by ajitsingh370** [comment] 2023-09-05 02:40
Hi All,

I am also facing this issue. Is there any ETA for this issue?

**Comment by kasperbolarsen** [comment] 2023-09-05 08:38
> Hi All,
> 
> I am also facing this issue. Is there any ETA for this issue?

Please don't comment on a closed case. Either commend on the open case or create a new
