### ISSUE TITLE
Layout Type Adaptive Card displays Missing slots warning

### ISSUE THREAD

**Issue by leichtin** [microsoft-search/pnp-modern-search#4038] opened 2024-10-11 09:07 UTC
**Version used**
Ex: 4.13.1

**Describe the bug**
Warning "The following slots have not been configured: Id" when changing to Adaptive Cards layout.
Webpart then does not display anything.

**To Reproduce**
1. Insert PnP Search Webpart
2. Search query {searchTerms} * (just to get everything as a test)
3. On page 2 select available Layout "Adaptive Card"
4. Warning "The following slots have not been configured: Id" is shown

**Expected behavior**
When using adaptive cards layout, mandatory standard fields should alredy be mapped.

**Screenshots**
<img width="231" alt="Screenshot 2024-10-11 110534" src="https://github.com/user-attachments/assets/fd557922-a75c-436c-8b5e-ad8de90daa21">

**Desktop (please complete the following information):**
 - tested in Chrome & Edge
 - Win10 machine

**Additional context**
Changing line 50 in results template from $root.slots['IId']))[0]} to $root.slots['ItemId']))[0]} removes the warning but doing the same in a custom json still displays the warning "The following slots have not been configured:" but without the missing field.

**Comment by marcoschmucker** [comment] 2024-10-11 09:16
We have the same issue with 4.13.1 - cannot be used, @wobba

**Comment by jblueml** [comment] 2024-10-15 14:13
In my opinion the missing slot warning works as intended: there's a reference to a slot named "Id" in the (default) AC-layout-template "List" and there's no (default) slot named "Id").
![image](https://github.com/user-attachments/assets/02c9b15c-d615-44df-9e6b-eec5435b292b)

@wobba
The question is rather, whether this 'id' attribute for the items-collection is really necessary in this standard layout template. I've tested this with a AC-layout-template without this line and it worked for me (with version 4.12.2).

**BUT:** 
There seems to be a general problem with adaptive-card-rendering in version 4.13.1, which leads to the misbehaviour described by @leichtin and @marcoschmucker.

Simply switching the template-type to "Adaptive Cards" in a freshly added results-webpart leads to not changing and rendering the default results-layout "List" and the following error in the browser console is logged:
![image](https://github.com/user-attachments/assets/fd01822d-8847-4a88-8ab9-e3d0ccee1507)

I saw, in TemplateService.ts, that packages for adaptive card-handling (adaptivecards, adaptive-expressions, adaptivecards-templating) are imported on demand. 

Could that be a packaging-issue finally?
![image](https://github.com/user-attachments/assets/a6dcd76a-d707-4e23-a50a-58a6725ea3ab)

**Comment by jblueml** [comment] 2024-10-31 13:37
@wobba: 
I did some further investigation on this issue today 'cause of some lazy minutes 😉.

It seems that adaptive cards-rendering has been broken since commit [0a663fe](https://github.com/microsoft-search/pnp-modern-search/commit/0a663fe8005a68a885ced112255f116d44db7a3c#diff-a0f8af5ff889ee35ca8d9fee9bfe6cfe2a792f4d1b7a3eaeb66bedd633a86efb).
With this commit, the package-versions of "adaptive-expressions" and "adaptivecards" have been updated to newer ones (4.22.1 > ^4.23.0 respectively 3.0.2 > ^3.0.4).

For the sake of interest I've switched back to the previous versions of these packages in my dev-environment which led to adaptive cards layouts suddenly being rendered correctly again.

Can you confirm this?

**Comment by wobba** [comment] 2024-11-08 22:00
Think I may be able to resolve it based on information from https://github.com/pnp/sp-dev-fx-controls-react/issues/1876

**Comment by wobba** [comment] 2024-11-09 14:28
Fixed with #4089

**Closed by wobba** 2024-11-09 14:28 UTC
Labels: bug, Needs: Triage
