### ISSUE TITLE
PnP - Search Filters: Filter field dropdown not available

### ISSUE THREAD

**Issue by simonpierre-giro** [microsoft-search/pnp-modern-search#1214] opened 2021-08-17 14:38 UTC
Good Day,

If I want to configure the PnP - Search Filters, when I customize filters the dropdown to select fields is not available:

![image](https://user-images.githubusercontent.com/79323996/129746422-3049c0f4-795a-407b-b84d-1e5f362dec81.png)

Curiously enough, if I type in directly the field name, it will work.

![image](https://user-images.githubusercontent.com/79323996/129746170-b1323728-bf2e-46e6-bc80-6c7b8e34cfc5.png)

I have admin permissions.

**Comment by simonpierre-giro** [comment] 2021-08-17 17:32
Adding to

**Comment by simonpierre-giro** [comment] 2021-08-17 17:33
Not too sure why but dropdown ended up appearing. Case closed.

**Comment by simonpierre-giro** [comment] 2021-08-18 12:41
It's really weird, sometimes I have the dropdown, sometimes not. I can't tell what makes this happen, as I use same machine, same browser, same account when trying to configure the same web part.

This morning the dropdown is not there, it was yesterday evening. It wasn't yesterday afternoon, so the displaying issue is intermittent

![image](https://user-images.githubusercontent.com/79323996/129899657-f4a304a8-5929-4e3f-9d6a-b8c994740b54.png)

**Comment by FranckyC** [comment] 2021-08-18 23:48
Hi @simonpierre-giro, the dropdown values are deduced from the results currently displayed in the connected Search results Web Part. If you have 0 results, you have 0 value ;) that's why. Anyway this list is likely here to help you to choose a filter field and **doesn't list all possible properties you can use here**.. That's why you can add your own value here.

I close this one as it is not a bug. 

PS: Next time, please use the issue template. Merci!

**Closed by FranckyC** 2021-08-18 23:48 UTC

**Comment by simonpierre-giro** [comment] 2021-08-19 11:49
Ah that explains. Template issue? OK will look for it, sorry it's m y first time on Github, I'm not familiar.

Merci à toi Franck, bon travail ces web parts!
