### ISSUE TITLE
Filter issue with localization enabled

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#2072] opened 2022-05-08 19:05 UTC
**Version used**
Ex: 4.6.1.0

**Describe the bug**
Filter does not always correctly apply on search result for a managed property using localization.

Search result is using localization. I have a RefinableString04 mapped to a managed metadata column ows_taxId. In the template I'm using the AutoRefinableString04 managed properties. In th search results terms are correctly translated.
However, in the search filter, I'm using RefinableString04 as a filter, the translated value correctly displays but when I apply the filter, the search results are not always correctly filtered.

**To Reproduce**

Use a term set with translated value
Add a managed metadata column mapped to this term set to a library
Add some documents and set with different terms
Use a RefinableString managed property mapped to the ows_taxId of the added column.
Create a page and add pnp search result web part. Set query to return only documents for the libary url. Add the newly created managed property to the selected properties. Enable localization
Using the detail list layout, add a column using expression {{AutoRefinableStringXX}}
Should see the value of RefinableStringXX correctly translated.

Add a PNP search filter
Add the RefinableStringXX as a filter. Link to the search results web part. Do the same thing with the search result web part (specify it is using this filter web part).
Values in the filter web part will display translated value of RefinableStringXX correctly.

However, using a value in the filter will not always correctly filters the results.

**Expected behavior**
Only results with the selected value should be returned

**Screenshots**
![image](https://user-images.githubusercontent.com/11309224/167311785-bfcc5c30-0cbd-4638-ae4b-f6b2b3e91ebd.png)
![image](https://user-images.githubusercontent.com/11309224/167311793-3acb0913-c515-4183-b36c-c3061489aa71.png)

**Desktop (please complete the following information):**
 - Browser Edge latest release

**Comment by wobba** [comment] 2022-05-09 11:47
Do you have a sample request JSON for the request made you can share? That helps troubleshooting this.

**Comment by coupalm** [comment] 2022-05-09 12:44
Here are more screenshots.

No filter applied:
![image](https://user-images.githubusercontent.com/11309224/167412059-bbf53b20-1e8c-4a9d-ae5b-c97ddfdf7b83.png)

Select first term in the filter list:
![image](https://user-images.githubusercontent.com/11309224/167412177-e705c8ef-d362-40c5-9a7f-88bc3d126edd.png)

Select second term in the filter
![image](https://user-images.githubusercontent.com/11309224/167412311-c6f7638f-bfe3-442e-be2f-ae00e4ebdf4a.png)

Select third term
![image](https://user-images.githubusercontent.com/11309224/167412386-cb58f09b-22de-4b4e-9396-faf36c9454b2.png)

**Comment by mbice** [comment] 2022-05-11 22:45
Hi,

I had logged a similar issue #1797 that I think might be related. The one I raised is still not resolved in the latest release and from what I can gather the SharePoint search API has an issue when passing both a hex encoded and a string parameter into an OR refinement filter query. Even through the search query tool I could reproduce this behavior. Either all the parameters to the or() query need to be hex encoded or all strings. Possibly a search API bug?

**Comment by eduardpaul** [comment] 2022-05-12 10:58
Same issue here! When we remove localization it works fine with all values L0,GP0,... but with localization it returns combined results. @mbice we are trying to verify what you are suggesting but seems correct.

**Comment by wobba** [comment] 2022-05-12 11:09
Maybe we should decode the hex values, and keep the `GP0|#id` and `L0|#id` parts only, stripping the label name. Then we don't need to append the string version at the end either.

**Comment by coupalm** [comment] 2022-05-14 12:29
For my understanding, is the issue caused by a change/bug with values returned by managed metadata? It looks like it is also creating issue with the modern content query web part when filtering on managed metadata properties….

**Comment by FranckyC** [comment] 2022-05-22 19:18
@coupalm could it be just your results are tagged with both terms? According to refinement value for the term "Energy" the values `L0|#0ae13bdfc-fe6f-4072-b011-d54b149888d1|Energy` and `GP0|#ae13bdfc-fe6f-4072-b011-d54b149888d1` are used to narrow results so only one term is targeted with this specific ID. Can you inspect the value of the property `SujetTaxId` in your results in debug mode see if it makes sense?

**Comment by mbice** [comment] 2022-05-24 21:14
@wobba the only way I can ever get RefinementFilters to work using taxonomy managed properties (taxId ones, not string based ones) is to use RefinementTokens and have them hex encoded. For example, if I have a term with label "People", GUID "5a9678f6-00ff-4447-933f-71df1ee509d1", and mapped to RefinableString50:

The following refinement filter works (hex encoded "L0|#05a9678f6-00ff-4447-933f-71df1ee509d1|People" and "GP0|#5a9678f6-00ff-4447-933f-71df1ee509d1" as parameters):

RefinableString50:or("ǂǂ4c307c233035613936373866362d303066662d343434372d393333662d3731646631656535303964317c50656f706c65","ǂǂ4750307c2335613936373866362d303066662d343434372d393333662d373164663165653530396431")

The following does NOT work (i.e. it returns a bunch of results that don't match the refinement):

RefinableString50:or("ǂǂ4c307c233035613936373866362d303066662d343434372d393333662d3731646631656535303964317c50656f706c65","ǂǂ4750307c2335613936373866362d303066662d343434372d393333662d373164663165653530396431",string("L0|#5a9678f6-00ff-4447-933f-71df1ee509d1"))

As soon as the parameters are mixed (string and hex encoded) the query returns non-matching pages.. Kind of feels like a search API bug, to me.. But if that's intended API behavior then your suggestion to not mix and match the parameter types makes sense. However, there might be a valid use case for having that string parameter (string("L0|#5a9678f6-00ff-4447-933f-71df1ee509d1")) that @FranckyC can elaborate more on? Perhaps if it's a Tax ID field where we know only hex encoded will work we never pass in a string() parameter as part of that OR() RefinementFilters parameter?

Thanks!

**Comment by eduardpaul** [comment] 2022-05-25 07:40
#2110 is what we are using to patch production at the moment. We haven't tested all the edge cases, but it is aligned with this thread.

**Comment by Rachel-0107** [comment] 2022-05-27 08:59
I have the same problem that you face.
Is there any solution that you suggest?
I am sorry but I do not realize how should I refine and where .
Could you give me more detail?

**Comment by FranckyC** [comment] 2022-05-28 20:40
Made a fix with PR #2119. As suggested by @wobba, the combination that seems to work in every case is `or(GP0|#<termId>,L0|#<termId>)` so without the HEX encoding and skipping the original value with language specific label Also, remember it has to comply with this scenario: https://microsoft-search.github.io/pnp-modern-search/usage/search-filters/#use-indexed-property-bag-properties-with-taxonomy-values

**Closed by FranckyC** 2022-05-28 20:40 UTC
Labels: Needs: Triage, v4

**Comment by mbice** [comment] 2022-05-30 17:30
@FranckyC @wobba thanks the PR.

One thing I am noticing, though, is that URLs previously generated with the refiners that had the hex encoded values in them are no longer working. Many of our clients bookmark pre-refined page URLs. If we upgrade them to a newer package with these changes those refiners still apply correctly, but it doesn't properly show up in the refiner web part.

e.g. Here is what loading up a page with the old URL format from 4.5.1 package with the latest package off develop branch.

![image](https://user-images.githubusercontent.com/985283/171038451-00eea293-62c4-40b1-8c85-85bc664c17cb.png)

Would it be possible to have the hex encoded refiners from those previously generated URLs still supported? Or will we need to have users re-generate their bookmarks using the new URL format that uses the string-based values? Ideally both would work.

Thanks again for all your time on this one!
