### ISSUE TITLE
The "DynamicData" object cannot be used because it has been disposed

### ISSUE THREAD

**Issue by PooLP** [microsoft-search/pnp-modern-search#31] opened 2019-12-06 06:59 UTC
## Category

- [x] Bug

Hi,
I have a weird bug on first release tenant. 
I haven't tested on GA tenant.
I tested only with Chrome.
It's last release of pnp-modern-search (3.8)

## Expected or Desired Behavior

If you have many page who use pnp-modern-search webparts and if you navigate between her with partial load you have this error in console :

`The "DynamicData" object cannot be used because it has been disposed`

Yesterday, I also had this error that makes crash this webparts, but I do not reproduce it this morning :

`Source has already been initialized`

## Steps to Reproduce

- open chrome console
- create two page and configure pnp-modern-search with all search webpart (searchbox, refiners ...)
- create two nav access in header nav bar
- navigate several times alternately between these two pages
- see the console

Thanks

**Comment by FranckyC** [comment] 2019-12-08 11:40
Hi @PooLP, thanks for submitting this issue. When this issue occurs, does it break the connections between Web Parts on the page?

**Comment by FranckyC** [comment] 2019-12-08 13:12
Ok I'm able to reproduce it. I'll see what could be the cause. Thanks.

**Comment by FranckyC** [comment] 2019-12-10 17:37
@PooLP Should resolved by #34 . Can you confirm?

**Closed by FranckyC** 2019-12-10 17:37 UTC

**Comment by PooLP** [comment] 2019-12-11 07:42
I'm confirm, it's resolved!

**Comment by cpluceDev** [comment] 2020-11-09 17:10
this happens when navigating from modern search pnp web parts and OOTB Microsoft(Modern) search from suite bar  https://github.com/microsoft-search/pnp-modern-search/issues/537

**Comment by waynel2** [comment] 2020-11-19 05:28
Hi there,

Just wondering if there has been any further troubleshooting or if anyone can assist to resolve the above issue?

A colleague of mine has just raised the same issue under under thread (https://github.com/microsoft-search/pnp-modern-search/issues/560 ) hence if anyone has any ideas on how to resolve this it would be great to hear from you!

Thanks

Wayne

**Comment by wobba** [comment] 2020-11-19 15:49
@cpluceDev @waynel2 should be fixed in the dev branch now.

**Comment by waynel2** [comment] 2020-11-19 23:17
@wobba - that's for the heads up.  I'm only a BA though will let our developers know so hopefully they can deploy the latest version.
