### ISSUE TITLE
PnP Search Results v4.4.1 not loading extensibility libraries unless browser cache is refreshed.

### ISSUE THREAD

**Issue by BinhKhuu** [microsoft-search/pnp-modern-search#1768] opened 2022-01-28 04:04 UTC
##### Version used
4.4.1

##### Describe the bug
Search Results webpart is not loading extensibility library on regular page refreshes but will load when browser cache is refreshed with CTRL + F5.

Looking at the network traffic GetClientSideComponents returns an empty array [] for the target manifest.
looking at the ExtensibilityService an error is thrown in loadExtensibilityLibraries and resolves(undefined) and component is not loaded.

```
Cannot read properties of undefined (reading 'isInternal')
    at e.loadComponent (sp-pages-assembly_en-au_21ebdd37d8a28977ecf8b01b7bbaef98.js:71:57126)
    at sp-pages-assembly_en-au_21ebdd37d8a28977ecf8b01b7bbaef98.js:71:57712
```

On cache refresh GetClientSideComponents returns the target manifest and the extension is loaded correctly.
loadExtensibilityLibraries is able to resolve.

##### To Reproduce
1. Configure Search Results Webpart extensibility configuration with target manifestID
2. Inspect network traffic for GetClientSideComponents on CTRL + F5 browser refresh
3. Inspect network traffic for GetClientSideComponents on regular page refresh.

##### Expected behaviour
Library extensions loaded and search results rendered using the custom components.

##### Desktop (please complete the following information):
Chrome Version 97.0.4692.99 (Official Build) (64-bit)

##### Additional context

Network on Cache Clear
![image](https://user-images.githubusercontent.com/17061411/151483823-d729c887-b3d6-4bbe-81f8-a1bc26b95504.png)

Network on regular refresh
![image](https://user-images.githubusercontent.com/17061411/151483906-35ad972b-b49b-4ca4-95ca-4670edb4b6a4.png)

**Comment by wobba** [comment] 2022-01-28 08:18
Can you retest with v4.5.3, if still an issue we can look into it.

**Comment by jhholm** [comment] 2022-01-28 08:57
I can reproduce this with 4.5.3. Everything worked ok a few days ago. Starting to receive errors now and I get the same exact issues with the GetClientSideComponents API call. Ctrl-F5 seems to work for some odd reason as specified above.

**Comment by mahmoudhhassan** [comment] 2022-01-28 09:00
@wobba It looks like this affecting also other versions we are using V3 old version (3.10v) and it has the same issue. I think it maybe related to call signature. I have an OOB call that is working with this payload:
{"components":[{"id":"f1006a38-983e-4851-ba4a-70a12aaf94b8",**"version":"0.1.0"**}],"project":"b6917cb1-93a0-4b97-a84d-7cf49975d4ec"}

While the MSW payload looks like:
{"components":[{"id":"2501f2fd-d601-4da4-a04d-9f0bd85b1f54"}],"project":"b6917cb1-93a0-4b97-a84d-7cf49975d4ec"}

not sure if sending without version is the root cause?

**Comment by jhholm** [comment] 2022-01-28 09:03
I already tried adding the version number in the call explicitly with my custom pnp-modern-search build without any help.

**Comment by wobba** [comment] 2022-01-28 09:07
Do we think this is an SPFx issue, or wrong pattern for loading in the web parts?

**Comment by patrikhellgren** [comment] 2022-01-28 09:13
This could be related to SharePoint/sp-dev-docs#7664. There is at least one [comment](https://github.com/SharePoint/sp-dev-docs/issues/7664#issuecomment-1022475281) that mentions having issues with loading library components. I would say this is most likely not related to Modern Search webparts.

**Comment by till-llit** [comment] 2022-01-28 10:13
can reproduce this issue since this morning in 2 tenants (standard + targeted release).

![image](https://user-images.githubusercontent.com/91128746/151528748-758fb3d0-d56e-488f-af79-ee3850ce8caf.png)

CTRL+F5 is "healing" the issue for one reload. 

Another custom SPFX Solution is broken in our environments in the same moment, looks like a global service degradation in the SPFx Runtime

**Comment by wobba** [comment] 2022-01-28 10:46
I'll close this one, and people can track a resolution via https://github.com/SharePoint/sp-dev-docs/issues/7664.

**Closed by wobba** 2022-01-28 10:46 UTC
Labels: Needs: Author Feedback, v4

**Comment by jhholm** [comment] 2022-01-28 12:59
I managed to circumvent this for now, by adding the extensibility library as a dependency on an application customizer that was already in use on the site and thus loading it before the extensibility is loaded dynamically by PnP Modern search. Hacky, but fixed the issue for me.

**Comment by wobba** [comment] 2022-01-30 12:15
Seems like something should change in SPFx, as depending on an app customizer being earlier in the chain seems the wrong approach.

**Comment by jhholm** [comment] 2022-01-31 07:26
Yeah, I would not recommend my "solution" for other than getting things to work for now, before this is fixed behing the scnes.
