### ISSUE TITLE
No settings show up under SharePoint Search v4.7

### ISSUE THREAD

**Issue by lraspbe** [microsoft-search/pnp-modern-search#2303] opened 2022-08-22 19:20 UTC
**Version used**
4.7

**Describe the bug**
When I clicked on "SharePoint Search",  it's blank for the settings.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome

![image](https://user-images.githubusercontent.com/59847213/186001598-dc6a1aeb-bfd1-4898-acd8-5c94c72653e5.png)

**Comment by wobba** [comment] 2022-08-22 19:46
Newly installed? Did you refresh? Using CDN? Any errors in the network tab in your browser?

(need more information to assess what the issue is :)

**Comment by lraspbe** [comment] 2022-08-22 19:50
Yes, it is newly installed and yes, refreshed and rebooted the laptop. Looks like it’s blocked?

***@***.***

[Guilford County Home Page]<https://www.guilfordcountync.gov/>
Li Raspberry    ,       MCP, MCTS
Web/Internet Developer
Information Technology
Guilford County Government
201 West Market Street, Greensboro, NC 27401
336-641-5763<tel:336-641-5763>
***@***.******@***.***> | www.guilfordcountync.gov<https://www.guilfordcountync.gov/>
[Facebook]<https://www.facebook.com/GuilfordCounty>
[Twitter]<https://twitter.com/GuilfordCounty>
[YouTube]<https://www.youtube.com/channel/UC0vr_BWqPJ3H9faV2VjVCmA>

**Comment by lraspbe** [comment] 2022-08-22 19:53
Should I grant permission to API access?

[Guilford County Home Page]<https://www.guilfordcountync.gov/>
Li Raspberry    ,       MCP, MCTS
Web/Internet Developer
Information Technology
Guilford County Government
201 West Market Street, Greensboro, NC 27401
336-641-5763<tel:336-641-5763>
***@***.******@***.***> | www.guilfordcountync.gov<https://www.guilfordcountync.gov/>
[Facebook]<https://www.facebook.com/GuilfordCounty>
[Twitter]<https://twitter.com/GuilfordCounty>
[YouTube]<https://www.youtube.com/channel/UC0vr_BWqPJ3H9faV2VjVCmA>

**Comment by wobba** [comment] 2022-08-22 19:54
I know it can take time for assets to be served 100% right after install of SPFx. I would maybe give it an hour at best, depending on how CDN or not has been set up. So it's a SPFx issue, not web part issue. Could be more prominent as we split the package into many smaller .js files to ensure faster/optimal loading.

I'll close it for now, and if it doesn't work after 1-2h, I would re-upload the sppkg over the existing one and publish it. And see if that resolves it.

**Closed by wobba** 2022-08-22 19:54 UTC
Labels: Needs: Triage, v4

**Comment by wobba** [comment] 2022-08-22 19:55
If you're just using the SP provider, there is no need to grant API permissions (unless you want to use the people cards from the Graph toolkit)
