### ISSUE TITLE
Add pagination in custom spfx renderer extension

### ISSUE THREAD

**Issue by jbesson73** [microsoft-search/pnp-modern-search#475] opened 2020-09-16 16:41 UTC
First of all, thank you for this very helpful webpart that works like a charm

**Version used**
3.15.1

**Describe the bug**
We have created a custom renderer and after the migration to the last version, the pagination not works anymore (because the pagination webpart has been removed).
Unfortunately, we don't know how to add by code this component directly in the method "public render()".
If somebody got an idea, we will be extremely grateful.

**Comment by wobba** [comment] 2020-09-16 18:16
Duplicate of #221

**Closed by wobba** 2020-09-16 18:16 UTC
