### ISSUE TITLE
Managed card fileds dont save changes after update to 4.7

### ISSUE THREAD

**Issue by MarinBuric** [microsoft-search/pnp-modern-search#2376] opened 2022-09-21 08:37 UTC
**Version used**
4.7 
Updated from 4.3

**Describe the bug**
In the Search Results web part, under Layouts, I cannot edit Managed card field, for example in field area "Title" I want to add "TEST" before the slot item. After I hit the Save button changes are lost.

Even if I change raw properties it doesn't show.

**To Reproduce**
1. edit the Search Results button
2. go to 2nd page
3. under Layout options select Managed card fields
4. click the pen icon, and change the value under Title
5. click Save

**Expected behavior**
It should write "TEST" before "Title"

**Screenshots**
editing card field:
![pnpsearch1](https://user-images.githubusercontent.com/52964255/191454913-8e1a8dce-7f66-4f0a-8b57-2f2ab04b3bd9.png)

change is not saved in search results
![pnpsearch2](https://user-images.githubusercontent.com/52964255/191454974-0ba548e7-2885-4bd4-9030-95a09b58c16a.png)

editing raw properties doesn't help
![pnpsearch3](https://user-images.githubusercontent.com/52964255/191456222-0781430e-200c-44c9-b79c-eccd509e7d7d.png)

**Desktop (please complete the following information):**
 - Edge

**Comment by heinrich-ulbricht** [comment] 2022-09-22 14:55
Hitting this issue as well. You can enter what you want, the changes are not saved.
My workaround so far: edit the result type and hard code the values there, bypassing the managed card field config.

**Comment by Dominik-KV** [comment] 2022-09-22 15:36
Confirming this issue also. Selected "Cards" from "Handlebars/ HTML", need to change managed card fields because of tags without separation between if two tags are assigned to my search result item, try to change it, save it, checking if it is saved - it is not.

**Comment by wobba** [comment] 2022-09-25 11:14
Can you try with v4.8-beta?

**Comment by MarinBuric** [comment] 2022-09-26 07:35
> Can you try with v4.8-beta?

It works now with 4.8-beta. All my customizations are back now.
![Screenshot 2022-09-26 092614](https://user-images.githubusercontent.com/52964255/192217591-d6213490-0e2a-4ae2-9029-81960399cb0d.png)

Location: CSS and anchor - to behave as Authorative News
Tags: each Tag is a link to the Search results page with a URL fragment, so that can be used as a filter

**Comment by wobba** [comment] 2022-09-26 14:20
Your last comment on `SPSiteUrl` is hard to understand. Are you requesting it on the search query? Are you getting values back for in the results? And if so, where is it not working where it should have worked?

**Comment by MarinBuric** [comment] 2022-09-28 07:15
OK., sorry for that, here are the details:

I'm talking about the behavior of the "Location" placeholder in the Managed card fields. And this is without my customizations.

When used in the Handlebars expression - SPSiteUrl is empty 
![Screenshot 2022-09-28 085117](https://user-images.githubusercontent.com/52964255/192708591-a1a99498-a8f4-48d8-a982-4696f391a820.png)

then in the Results web part, this link has an empty href attribute

![Screenshot 2022-09-28 085534](https://user-images.githubusercontent.com/52964255/192709296-4313ef08-a7ed-4145-b437-b0b98a4a530b.png)

When it's used as a value it returns the site URL
![Screenshot 2022-09-28 085011](https://user-images.githubusercontent.com/52964255/192708606-b170cbdd-550f-4386-a7dd-1bdb30f35049.png)

and then in the Results, it looks like this
![Screenshot 2022-09-28 085901](https://user-images.githubusercontent.com/52964255/192709985-6cdd67c1-a45c-4d4e-8280-bb367848f711.png)

**Comment by FranckyC** [comment] 2022-09-28 18:57
Hi @MarinBuric, I'm not able to reproduce this issue. What if you use the expression `<a href="{{item.SPSiteUrl}}">{{item.SPSiteUrl}}</a>`?

**Comment by MarinBuric** [comment] 2022-09-29 07:03
@FranckyC - same behavior, no value. That is happening on the website KBase that I'm preparing for production (internal, not client)

But - then I added the PNP Modern Search app to a clean website that didn't have it before. And it works as expected.

On the website where it doesn't work, PNP Modern Search was upgraded from 4.3 to 4.7 and 4.8.beta - so maybe there are some conflicts. I would appreciate it if you can't find some workaround or I'll have to recreate it from the scratch.

**Comment by wobba** [comment] 2022-10-03 10:41
@MarinBuric I propose you export the web part config from the web part pane, look at the JSON in an editor and try to spot anything weird with it. If you see anything weird, then fix it, and re-import.

**Comment by MarinBuric** [comment] 2022-10-05 07:58
@wobba - tried that, didnt see anything weird. So I removed the app from the site content and added it back. And {{SPSiteUrl}} value was ok.

But then - in the Search Results web part I only have 2 pages of properties instead of 4.
![20221004_123440](https://user-images.githubusercontent.com/52964255/193798336-202e9e60-8c4a-4615-8b92-958db9fc7550.gif)

And it's happening also on clean new web site.

But also I've found that App in Apps for SharePoint has State (?) disabled, but Enabled is true.. 
![Screenshot 2022-10-05 095617](https://user-images.githubusercontent.com/52964255/194009598-cb3063b3-608e-4efa-8d0f-1eedc45196c9.png)
And I can find any info about what State field means.

**Comment by wobba** [comment] 2022-10-09 10:21
The issue you see is the one reported at #2405

**Comment by MarinBuric** [comment] 2022-10-13 10:38
Problems with the search web part properties pageing are due to bug in react. It works with React 17.0.1  #2405

**Comment by MarinBuric** [comment] 2022-10-14 10:01
@wobba - the original problem ([1st post](https://github.com/microsoft-search/pnp-modern-search/issues/2376#issue-1380550454)) still exists. Editing managed card field doesn't save changes. Version 4.8.0.beta1

**Comment by AbbasRashidi** [comment] 2023-01-04 13:25
Hi, just a quick feedback.
I had the original problem (1st post) with 4.7. After reading this issue, I have installed 4.8.0 today and the problem is solved from my point of view. the other problem with paging etc., I could not reproduce.

Regards and happy new year.

**Comment by MarinBuric** [comment] 2023-01-05 09:48
@AbbasRashidi thank you for the info. I've installed 4.8 and it really works fine, all my customizations work as intended. The paging problem inside web part properties also works fine.


@wobba - now you can close this bug :)

**Closed** 2023-01-08 12:53 UTC
Labels: bug, Needs: Author Feedback, v4
