### ISSUE TITLE
PNP Search Web Part  for people search for some users managed property RefinableString is not getting data for some users we are getting data.

### ISSUE THREAD

**Issue by tmsavitha** [microsoft-search/pnp-modern-search#3745] opened 2024-05-15 18:16 UTC
PNP Search Web Part is not showing all of the details for users Profile. Some users are presenting fine and loading the Office and Assistant data for their profiles and others are not.
PNP webpart is pulling all user profile from all Geographical  locations, only 2 attributes which are
managed property RefinableString is not being pulled.

**Comment by kasperbolarsen** [comment] 2024-05-15 21:06
Can you verify the data returned by the API by running the same query in either SP Editor or SharePoint search query tool?

**Comment by tmsavitha** [comment] 2024-05-16 22:15
Checked with SharePoint Search query tool. Data for RefinableString   'Office and Assistant' data are not returned for other Geographical locations. but for North America it is returning data.

**Comment by kasperbolarsen** [comment] 2024-05-17 18:30
OK, so it is an API issue, not related to PnP Modern search. 

@wobba do you know if this is by design or a known issue?

**Comment by kasperbolarsen** [comment] 2024-05-22 07:35
My recommendation is to replicate the mapping in each geo, reindex the people search using the script, and check if that solved the issue

**Comment by tmsavitha** [comment] 2024-05-22 17:52
Please explain how to replicate the mapping in each geo?

**Comment by kasperbolarsen** [comment] 2024-05-23 05:25
Ensure that the RefinableStrings you are using h's the same mapping in each geo/tenant.

**Comment by kasperbolarsen** [comment] 2024-06-08 15:40
@tmsavitha can we close this issue?

**Comment by wobba** [comment] 2024-06-09 11:37
@tmsavitha you access SharePoint admin on each GEO URL. Closing due to inactivity.

**Closed by wobba** 2024-06-09 11:37 UTC
