### ISSUE TITLE
Can't use filters on owstaxidmetadataalltagsinfo since upgrading to v4.7.0 

### ISSUE THREAD

**Issue by felix-antoine-dion** [microsoft-search/pnp-modern-search#2212] opened 2022-07-07 17:55 UTC
**Version used**
4.7.0

**Describe the bug**
I was using verison 4.6.1 and upgraded to 4.7.0. After the upgrade, all works fine except for the **PnP - Search Filters** when filtering on a **owstaxidmetadataalltagsinfo** value which always returns 0 result in the "PnP - Search Results".

All other RefinableString* used in the **PnP - Search Filters** works as expected.

I've played around with the localisation switch, tried to use **Tags** or **Autoowstaxidmetadataalltagsinfo** instead of owstaxidmetadataalltagsinfo but I always get 0 result.

I then decided to create a brand you page with default **PnP - Search Filters** and  **PnP - Search Results**, configured minimaly to filter on owstaxidmetadataalltagsinfo. I thought maybe it was an upgrade issue, the config schema from one version to the other could be incompatible, but it doesn't seem to be.

**To Reproduce**
1. Create a French (**1036**) SharePoint Communication site
2. Make sure you have a couple of documents tagged with some values in the **Enterprise keywords** property.
3. In a new SharePoint page, add a **PnP - Search Results** and a **PnP - Search Filters** 
4. Configure the **PnP - Search Results** with these parameters (all the others being default):
  ```json
  {
    "documentationLink": "https://microsoft-search.github.io/pnp-modern-search/",
    ...
    "dataSourceProperties": {
      "queryTemplate": "*",
      ...
      "enableLocalization": true,
    ...
    }
    ...
    "useFilters": true,
    "filtersDataSourceReference": "WebPart.544c1372-fb1d-4e96-bc1e-31fd66979667.933a3ebc-00ff-4c9c-91d1-d4d9efc88234:pnpSearchFiltersWebPart"
  }
   ```
5. Configure the **PnP - Search Filters** with these parameters (all the others being default):
  ```json
{
  "documentationLink": "https://microsoft-search.github.io/pnp-modern-search/",
  ...
  "dataResultsDataSourceReferences": [
    "WebPart.544c1372-42df-47c3-94d6-017428cd2baf.9dac0af5-3393-4d92-8663-a51f7ac46a22:pnpSearchResultsWebPart"
  ],
  ...
  "filtersConfiguration": [{
    "uniqueId": "4b6045ad-dcc9-48a9-b809-d224ee7eddc9",
    "displayValue": "Keywords",
    "filterName": "owstaxidmetadataalltagsinfo",
    "maxBuckets": null,
    "selectedTemplate": "CheckboxFilterTemplate",
    "type": "Refiner",
    "expandByDefault": null,
    "showCount": null,
    "isMulti": null,
    "operator": "and",
    "sortBy": "ByName",
    "sortDirection": "Ascending",
    "sortIdx": 1
    }
  ],
  ...
}
  ```
6. Publish the page
7. Verify that the **PnP - Search Results** displays some results
8. Select any filter from the Keywords values in the **PnP - Search Filters**
9. Note that the **PnP - Search Results** displays 0 result.

**Expected behavior**
Results should be more than 0.

**Screenshots**
None

**Desktop (please complete the following information):**
 Edge (chromium), Chrome

**Additional context**

**Comment by FranckyC** [comment] 2022-07-13 17:50
Hi @felix-antoine-dion, I'm able to filter using the `owstaxidmetadataalltagsinfo` property with the latest version. However, I get an other issue maybe related. Can you try to set a value for "# of values" filter setting (like 50)?

If it still does not work can you inspect the query `postquery` in the network request browser tab and review the value sent for the 'Refiners' property?

**Comment by yngrdyn** [comment] 2022-07-25 19:54
Any news on this? I'm not able to filter by **owstaxidmetadataalltagsinfo**

**Comment by felix-antoine-dion** [comment] 2022-07-25 23:22
@yngrdyn, unfortunately no. I will try to find some time this week to downgrade to version 4.6.1 and see if I get the same post request. Hopefully something will be different between the two versions that would explain the problem we encounter right now.

**Comment by FranckyC** [comment] 2022-07-27 20:01
@felix-antoine-dion I'm not able to reprodcue the issue but here are the things you can do to narrow down the possible causes:
- Try without the "enable localization" flag enabled. If it works, this is an issue with the localization process.
- Try using a different term set as the Enterprise keywords.
- Try to use a custom `RefinableStringXX` property mapping the `ows_taxId_xxx` crawled property and use this one as filter.
- Try to use Search Query Tool and pass the `owstaxidmetadataalltagsinfo:or(GP0|#1db725b5-d201-41f5-bdf0-ae7f9a031611,L0|#1db725b5-d201-41f5-bdf0-ae7f9a031611)` as refinement filters and `owstaxidmetadataalltagsinfo(filter=50/0/*,sort=name/ascending)` as refiners.

**Comment by felix-antoine-dion** [comment] 2022-07-27 21:27
@FranckyC , thanks for the troubleshooting tips. Here's what I've got:

> * Try without the "enable localization" flag enabled. If it works, this is an issue with the localization process.

This seems to be the problem, if I disable this flag, the filtering returns values as expected. This does not fix my problem though because the  Filter labels are screwed up.
![image](https://user-images.githubusercontent.com/3137001/181374769-2a49a418-797c-4e44-8331-64e4280225ec.png)

> * Try using a different term set as the Enterprise keywords.

Other termsets mapped to other RefinableStringXX work as expected. The owstaxidmetadataalltagsinfo is the only one I use that seems to have this issue.

> * Try to use a custom `RefinableStringXX` property mapping the `ows_taxId_xxx` crawled property and use this one as filter.

I've mapped the properties, I'll give you some news on friday morning to see what happens

> * Try to use Search Query Tool and pass the `owstaxidmetadataalltagsinfo:or(GP0|#1db725b5-d201-41f5-bdf0-ae7f9a031611,L0|#1db725b5-d201-41f5-bdf0-ae7f9a031611)` as refinement filters and `owstaxidmetadataalltagsinfo(filter=50/0/*,sort=name/ascending)` as refiners.

0 result...

Thanks again for your time and your help.

FA

**Comment by felix-antoine-dion** [comment] 2022-07-28 16:30
I was able to try 2 other things:

> * Try to use a custom RefinableStringXX property mapping the ows_taxId_xxx crawled property and use this one as filter

I get the same 0 result.

The other test I've done is to configure the 4.6.1 version of the webpart and compared the postquery. Here are the différences between the 2 queries:

- version 4.7.0
+ version 4.6.1

```json
{
    "request": {
      "__metadata": {
        "type": "Microsoft.Office.Server.Search.REST.SearchRequest"
      },
      ....
      "Properties": {
        "results" : [
          ...
          {
            "Name": "ListId",
            "Value": {
-              "StrVal": "c6cc49e4-e34b-4e59-a0ac-9f033646950b",
+              "StrVal": "d23a95c6-0918-47af-bfe0-85157dc10944",
              "QueryPropertyValueTypeIndex": 1
            }
          },
          {
            "Name": "ListItemId",
            "Value": {
-              "StrVal": "154",
+              "StrVal": "22",
              "QueryPropertyValueTypeIndex": 1
            }
          }
       ],
     }
    ...
+   "Querytext": "",  
    ...
"RefinementFilters": {
        "results": [
-          "owstaxidmetadataalltagsinfo:or(GP0|#bcb213a5-21bb-4e37-acc7-a34fa0949c56,L0|#bcb213a5-21bb-4e37-acc7-a34fa0949c56)"
+          "owstaxidmetadataalltagsinfo:or(\"ǂǂ4c307c233062636232313361352d323162622d346533372d616363372d6133346661303934396335367c42756c6c6574696e20492f5020657420666f75726e69737365757273206469726563747320657420617574726573\",\"ǂǂ4750307c2362636232313361352d323162622d346533372d616363372d613334666130393439633536\",string(\"L0|#bcb213a5-21bb-4e37-acc7-a34fa0949c56\"))"
        ]
      },
  }
}
```

I suspect that the problem lies in the **RefinementFilters**'s value which are quite formatted/encoded differently.

Any clue why this happens ?

FA

**Comment by FranckyC** [comment] 2022-07-28 20:14
Thanks for the very detailled information! I'll investigate why the new format does not work as it should be

**Comment by FranckyC** [comment] 2022-07-28 20:15
Can you try to use Search Query Tool and use ` owstaxidmetadataalltagsinfo:or("GP0|#bcb213a5-21bb-4e37-acc7-a34fa0949c56","L0|#bcb213a5-21bb-4e37-acc7-a34fa0949c56")"` as refinemente filters expression (same but with quotes on values) ?

**Comment by felix-antoine-dion** [comment] 2022-07-29 14:05
I tried the query but I still get 0 result.

I "brute forced" different other queries and I stumbled upon that [article](https://nometi.ngontinh24.com/article/query-variables-in-sharepoint-server-sharepoint-server).  There is a passage in the article talking about adding a 0 to the guid, so I tried these refinement filters (with and without quotation marks and without the "--> <--"): 
* owstaxidmetadataalltagsinfo:or("GP0|--><ins>0</ins><--bcb213a5-21bb-4e37-acc7-a34fa0949c56","L0|#--><ins>0</ins><--bcb213a5-21bb-4e37-acc7-a34fa0949c56")
* owstaxidmetadataalltagsinfo:or(GP0|-><ins>0</ins><--bcb213a5-21bb-4e37-acc7-a34fa0949c56,L0|#--><ins>0</ins><--bcb213a5-21bb-4e37-acc7-a34fa0949c56)

... and these work and return the results I'm looking for.

What would be the next steps for me and how can I help to fix this ?

FA

**Comment by FranckyC** [comment] 2022-07-29 14:51
Thanks for flagging this, I didn't en realize the '0' was missing acutally so it explains :D. Let me review the code and fix it, you've done already a great job of investigation!

**Comment by felix-antoine-dion** [comment] 2022-07-29 16:42
@FranckyC, thank you for your time

**Comment by FranckyC** [comment] 2022-08-01 21:58
Thanks @yngrdyn Yes I see where the issue is. I'll fix it in the next release but I need to check for other impacts first. Stay tuned ;)

**Comment by FranckyC** [comment] 2022-08-04 13:54
@felix-antoine-dion this should be fixed in the next release. Actlually, only L0 values need the '0' character to prefix the term GUID. Thanks for the investigation again!

**Closed by FranckyC** 2022-08-04 13:54 UTC
Labels: bug, working on it, v4

**Comment by felix-antoine-dion** [comment] 2022-08-22 16:01
@FranckyC, could you tell when you plan to next release? Absolutly no pressusre, I'll make some decisions based on the target date.
Thanks again.

**Comment by FranckyC** [comment] 2022-08-22 16:57
There will be a release in September. No precise date however. Thanks!
