### ISSUE TITLE
Please let me know how to configure QueryString Parameters in URL and How to use Filters deep links

### ISSUE THREAD

**Issue by SrinivasVeepuri** [microsoft-search/pnp-modern-search#1304] opened 2021-09-16 12:04 UTC
**Is your feature request related to a problem? Please describe.**
I would like to get Query String parameters which are selected from PNP Modern Filters, so please let me know the process.

**Describe the solution you'd like**
I thought "Filters deep links" will work but don't know how to use 

**Describe alternatives you've considered**
I have no any idea on alternative ways

**Additional context**
Please let me know the solutions asap to achieve this task, have an high dependence on this task.

**Comment by Laul0** [comment] 2021-09-16 19:42
Hi @SrinivasVeepuri,

Do you wish to show the performed PnP Modern Search request?

Thanks to the Debug mode of the data visualizer, you can find under the `Filters` node, the applied filter(s).

Hoping this answer will help you 🙂

**Comment by SrinivasVeepuri** [comment] 2021-09-17 03:46
sorry, still I am not clear on this answer, could you let me know How tp reach you to understand more this issue.

Thanks,
Srinivas,
+91-9949712782

**Comment by wobba** [comment] 2021-09-19 17:07
Closing as it's not following the issue templates. Deep linking for filters is not implemented in v4. Duplicate of #1095

**Closed by wobba** 2021-09-19 17:07 UTC
Labels: type:incomplete-submission
