### ISSUE TITLE
Filters in panel showing blank

### ISSUE THREAD

**Issue by Tanddant** [microsoft-search/pnp-modern-search#866] opened 2021-03-16 07:43 UTC
**Version used**
4.0.0

**Describe the bug**
When setting up the search filters, using vertical or horizontal layout works great, but switching to panel results in a blank panel with no filters.

**To Reproduce**
Setup a search page with search results and filters.
Create a filter on filetype and set filters to layout vertical, and a * as search query for the results.
Verify that you can see the filter and it's working as intented.
Change the layout of the filters to panel, when you open the panel you'll see a blank panel.

**Expected behavior**
I would expect to see the possible filters in the panel.

**Screenshots**
I have a quick video instead: https://youtu.be/yx2go80pUNU

**Desktop (please complete the following information):**
 Windows 20H2 (OS Build 19042.867)
 Chrome Version 89.0.4389.82 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by FranckyC** [comment] 2021-03-16 13:51
Duplicate of #835. Will be fixed in the next release.

**Closed by FranckyC** 2021-03-16 13:51 UTC
