### ISSUE TITLE
Search Results WebPart: KQL query does not support optional querystring parameter

### ISSUE THREAD

**Issue by svermaak** [microsoft-search/pnp-modern-search#1230] opened 2021-08-23 07:14 UTC
**Is your feature request related to a problem? Please describe.**
https://github.com/microsoft-search/pnp-modern-search/issues/512

**Describe the solution you'd like**
Support for v4 to strip QueryString query from search if QueryString is empty

**Describe alternatives you've considered**
Only option that works at the moment is sending a * as the QueryString

**Additional context**
https://github.com/microsoft-search/pnp-modern-search/issues/512

**Comment by wobba** [comment] 2021-08-23 16:39
Closed as duplicate of #512

**Closed by wobba** 2021-08-23 16:39 UTC

**Comment by svermaak** [comment] 2021-08-23 22:18
This is not a duplicate. #512 is for v3, this is for v4

**Comment by wobba** [comment] 2021-08-29 12:09
Being fixed by #1231
