### ISSUE TITLE
PNP Search Breaks when URL changes on SharePoint site

### ISSUE THREAD

**Issue by mauricework** [microsoft-search/pnp-modern-search#1612] opened 2021-12-08 21:59 UTC
**Version used**
Version: 4.4.1

**Describe the bug**
When doing a Change a Site Address (https://docs.microsoft.com/en-us/sharepoint/change-site-address.) the PNP Search Results web parts work intermittently (sometimes returns results and sometimes does not - probably happening as things are indexed is my best guess).  Need to update the links in the PNP Search Results to the new address to resolve the problem.  Not sure if this is by design or a bug?

**To Reproduce**
Follow the steps in Microsoft's document to change the site address of a site that you are searching a library on.
Test Search
Wait a few days (or reindex)
Test Search again.

**Expected behavior**
After doing the URL change we experience a broken site.  What would happen is initially no results show up when page is first loaded.  We then enter a search term.  Nothing returns.  Click the X to clear the search box and then results would show up.

**Screenshots**
Sorry did not take any.

**Desktop (please complete the following information):**
Chome and Edge.

**Comment by wobba** [comment] 2021-12-10 12:00
Changing site URL's is outside the scope of these web parts. If you are using site URL's in the web part, you have to manually update them if the move does not fix 3p web parts. So out of scope and "by design".

**Closed by wobba** 2021-12-10 12:00 UTC

**Comment by mauricework** [comment] 2021-12-13 16:10
I thought that might be the answer…lol…but figured I would ask.  I will forward to the team mate that encountered the issue.
