### ISSUE TITLE
Search Result Webpart: Managed Properties with Dashes can't be retrieved

### ISSUE THREAD

**Issue by andikrueger** [microsoft-search/pnp-modern-search#2355] opened 2022-09-13 13:44 UTC
**Version used**
Ex: 4.7.0

**Describe the bug**
We have a managed property with a name, that contains dashes: "CustomerName-PropertyType-Name" This managed property holds information an can be seen within the debug view of a search result web part. As soon as we try to visualize this managed property within a table layout, there is no value returned.

**To Reproduce**
1. Create a new managed property with name, that contains dashes: "This-is-a-awesome-name-for-some-testing" (retrievable)
2. Add a mapping, so that this prop holds information
3. Add a search result webpart to a site and find a suitable query
4. Add the managed property to the return values
5. Add this prop to the table

See nothing...

**Expected behavior**
Regardless of the name, the values should be returned.

**Desktop (please complete the following information):**
 - Browser latest edge

**Comment by wobba** [comment] 2022-09-13 15:35
I would stay with A-Z,a-z,0-9 and no special characters. Makes life easier.

**Comment by andikrueger** [comment] 2022-09-13 16:28
Great idea. I will elaborate it.

**Comment by wobba** [comment] 2022-09-13 17:37
@FranckyC The issue is if you have a prop with hyphens in slots. It works find if you use it directly in a template. So workaround if using slots is to create an alias without hyphens and use that in the slots mapping and also in the list of props to fetch.

**Comment by wobba** [comment] 2023-05-29 10:24
Fixed with #3034

**Closed by wobba** 2023-05-29 10:24 UTC
Labels: bug, v4
