### ISSUE TITLE
Spelling check not working in pnp search

### ISSUE THREAD

**Issue by INRLDX** [microsoft-search/pnp-modern-search#2373] opened 2022-09-20 12:16 UTC
**Version used**
v4.0

**Describe the bug**
When using incorrect spelling in the querytext, i am not getting suggestion for spelling,

**To Reproduce**
1. Go to 'pnp modern search web part page'
2. Type the wrong querytext in querybox e.g. accountt
3. click on search button
4. no suggestion visible

**Expected behavior**
Should get a suggestion with Did you mean:  account

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
enableSuggestion and enableModification are set to true

**Comment by FranckyC** [comment] 2022-09-20 19:12
Hi @INRLDX I guess you are using Microsoft Search. I'm able to reproduce your issue, it is because the same keywords is sent as both `queryText` and `queryTemplate`. @wobba it seems when the keyword is in the query template, it does not trigger the spelling suggestions.

Until we figure out a solution, you can remove the query template value in the Web Part settings (at least the token `{searchTerms}` or `{inputQueryText`}). As a blank value, you can simply add a white space and save, it should do the trick.

**Comment by FranckyC** [comment] 2022-09-20 19:15
And also, there is no 'Did you mean' feature by default. You have to process it manually from the response in your template:

![image](https://user-images.githubusercontent.com/5659122/191344834-06804a0c-a4dd-44a6-928d-f021d0ca086f.png)

**Comment by INRLDX** [comment] 2022-09-21 04:34
For using Did you mean feature, i am not getting alteredQueryTokens object for searchtext- accountt, but i am getting for accounts, can you let me know why is that happening.

![image](https://user-images.githubusercontent.com/110467696/191414919-bc774e60-6966-45f9-bef7-d601142b66a4.png)

getting alteredQueryTokens when using accounttt

![image](https://user-images.githubusercontent.com/110467696/191415051-6d835292-69a5-4dbc-894e-f7618ec223dd.png)

**Comment by wobba** [comment] 2022-09-25 10:43
I would say it's by design not to spellcheck terms spelled out in the query template, as this is an end-user feature and should work on user input.

**Comment by INRLDX** [comment] 2022-09-26 04:33
@wobba - can you please let me know why the difference in response, when both spellings are incorrect, accountt and accounttt. [Response Screenshot](https://github.com/microsoft-search/pnp-modern-search/issues/2373#issuecomment-1253192735)

**Comment by wobba** [comment] 2022-09-26 14:26
What makes sense to us as humans in terms of giving suggestions does not always match algorithms. So no good reason why one suggest and the other does not. It's an API issue we cannot control with the web parts.

**Comment by FranckyC** [comment] 2022-09-28 19:03
Close this one as it is an API issue. @INRLDX you should post your feedback directly from this page https://learn.microsoft.com/en-us/graph/search-concept-speller

**Closed by FranckyC** 2022-09-28 19:03 UTC

**Comment by Jeroen00** [comment] 2022-12-05 16:25
Can someone (@FranckyC ?) please explain what should work and what is not possible due to API limits? What I am looking for is similar to question from @INRLDX : I would like the PnP Search Results to suggest and include results for alternative spellings of the keyword in the same way as the SharePoint standard search page works. For example:

![image](https://user-images.githubusercontent.com/42589264/205688535-11b966cf-8cb9-424b-ba25-4226d6a35491.png)

So it automatically includes alternative spellings because there are results for this. 

How to achieve this in PnP Search? Customer won't accept that our custom search center looks better but the included results are more limited than the default SharePoint search.

**Comment by wobba** [comment] 2022-12-05 17:39
@Jeroen00 you can use the query extension method in 4.8 or use the SPFx query modifier in SPFx v1.16 if you are using the header search box.
