### ISSUE TITLE
PnP Modern Search V4 - Issue with .url file types  "ShortcutUrl"

### ISSUE THREAD

**Issue by jameelrrs** [microsoft-search/pnp-modern-search#1765] opened 2022-01-28 02:43 UTC
Hi, We have been using PnP Modern Search WebPart V3 and planning to migrate to V4.  Now that we have been using .url files in one of the libraries and was working fine with V3 property "ShortcutUrl" in the Search Results template.  However, the same is not found on V4 version.  Are we missing anything here?  Is there some managed property or config to be enabled?  Please help

_Originally posted by @jameelrrs in https://github.com/microsoft-search/pnp-modern-search/issues/271#issuecomment-1023832762_

**Comment by wobba** [comment] 2022-02-08 19:30
Duplicate of #1761

**Closed by wobba** 2022-02-08 19:30 UTC
