### ISSUE TITLE
Search Box Query String Issue

### ISSUE THREAD

**Issue by gristy58** [microsoft-search/pnp-modern-search#20] opened 2019-11-26 04:59 UTC
Hello,

I have the Search Box configured as so

![image](https://user-images.githubusercontent.com/37768717/69600648-57da0700-1061-11ea-8388-e06ac339ebcf.png)

This works great until you type something with a space like credit cards

instead of getting put in the URL as credit%20cards it is being put in as credit%2520cards

Therefore the expected refinement later on with this query string is failing.

**Comment by beavisnz** [comment] 2019-12-03 21:35
There is a similar issue with the Search Navigation component too, the query parameter is getting encoded twice.

**Comment by FranckyC** [comment] 2019-12-11 07:56
@gristy58 @beavisnz  I can't reproduce this behavior. I mean I see a similar encoding in the URL but the keywords are pricked up correctly by the search box WP afterwards. @gristy58 what do you mean by:

> Therefore the expected refinement later on with this query string is failing.

**Comment by gristy58** [comment] 2019-12-11 08:01
Hello

Because the new page loads with the extra encoding passed from the search box and the search results webpart does not strip this out searchs that include a space do not return correct results.

I had to make my own search box without the encoding bug to fix the issue but would rather use this one whent he encoding bug is fixed.

**Comment by gristy58** [comment] 2019-12-11 21:46
I am actually using the query string in react content query I just remember as search contents does not include rich text. This may be why you cannot replicate with the search results web part. Regardless it would be good to get this bug fixed

**Comment by jhholm** [comment] 2020-01-10 17:55
I am able to reproduce this with 3.7.0 and 3.8.0 and found a possible fix for this.
SearchBoxContainer.tsx
**Row 343**: searchUrl.searchParams.append(this.props.queryStringParameter, urlEncodedQueryText);
**Change to**: searchUrl.searchParams.append(this.props.queryStringParameter, queryText);

I guess the issue could be that the decoding is also done twice within modern search webparts. While targeting the query to SharePoint Modern Search, the double encoding breaks the search.

**Comment by jhholm** [comment] 2020-01-10 17:56
Thus this should require more changes as I haven't tested the decoding part yet in pnp-modern-search webparts.

**Comment by jhholm** [comment] 2020-01-10 18:01
This is my configuration for a Search box to target Modern Search
![image](https://user-images.githubusercontent.com/13876124/72175044-cab9fa00-33e3-11ea-99b0-49be2f781e4f.png)

**Comment by FranckyC** [comment] 2020-01-12 22:28
Thanks for submitting this issue, I will do some tests on my side and see what I can do about this. Sorry for the delay, it is a busy time ;)

**Comment by FranckyC** [comment] 2020-01-20 18:25
Should be resolved by #63 . Feel free to checkout the develop branch and test.

**Closed by FranckyC** 2020-01-20 18:25 UTC
