### ISSUE TITLE
Search Result webpart configuration "3 of 4" step can't access. Cannot set properties of undefined

### ISSUE THREAD

**Issue by twodul** [microsoft-search/pnp-modern-search#2405] opened 2022-10-03 04:27 UTC
**Version used**
Ex: 4.7

**Describe the bug**

On the search result web part configuration property pane, 
1 of 4 : next button working so can see the 2nd page
2 of 4 : when I click next button it go to "1 of 4" page not "3 of 4" page.
I can't set up available connection from 3rd page configuration.

It works fine with my test tenant environment and this issue happens only on our production environments.

I got below JavaScript error when I click next button.
<img width="685" alt="image" src="https://user-images.githubusercontent.com/42230798/193501568-8d9676e5-fc36-4343-a74e-8e62ebf08d7f.png">
I attached the console log messages. [SearchResultsPropertyPannelErrorLog.txt](https://github.com/microsoft-search/pnp-modern-search/files/9702178/SearchResultsPropertyPannelErrorLog.txt)

<img width="205" alt="image" src="https://user-images.githubusercontent.com/42230798/193501813-1a9d943f-ca5d-4320-a56b-4ec613d0ec56.png">

**Comment by wobba** [comment] 2022-10-03 10:38
1. tenant app catalog or site catalog?
2. add to all sites or added to one site?
3. use of public CDN or not?
4. any errors in the network tab?
5. how long after you uploaded/added the web parts did you get the error?
6. any other SPFx solution on the page?

Right after uploading/updating SPFx web parts it's common that they don't load right away.

**Comment by twodul** [comment] 2022-10-03 11:48
1. site collection app catalog not tenant app catalog
2. tick all site for site collection app catalog
3. public cdn
4. will check tommorrow
5. strait away and also checked 30 mins later as well
6. no
*  I tried v3 and same error happen from "3 of 4" step next button so can't access "4 of 4" page on v3 result web part property pane.

**Comment by tandrasi** [comment] 2022-10-04 02:07
I have the same issue on my end. I just got back from illness/holiday so it's been at least 2 weeks since I've used this webpart. Prior to this, we were using 4.7.0 without issue until I discovered this today - cannot access page 3 or 4.

I just even tried the latest 4.8 beta and it's the same. given that @twodul has tested v3, I feel there's some strange tenancy change that has happened to back-end functionality. I'm in Australia.

From my perspective:

**1. tenant app catalog
2. add to all sites
3. public CDN
4. no errors in the network tab, but the same error in the console when trying to paginate:**

![image](https://user-images.githubusercontent.com/72114492/193719087-ef07881a-6230-4227-b097-d4747054f95a.png)


**5. after at least 1.5 months with 4.7.0.
6. no**

**Comment by samg365** [comment] 2022-10-04 04:54
I've experienced the same. Can't finish configuring. 
Note different tenant that was working fine also on 4.7.0, has also stopped being able to navigate to tab 3 and 4.

**Comment by mrstrong79** [comment] 2022-10-04 06:29
Yep, same issue  here....

**Comment by ktownpete** [comment] 2022-10-04 07:24
I have the same issue. 
As @twodul mentioned, it works fine in the my sandbox-tenant which is kind of strange.
What I can see in the network tab in chrome, in the production tenant it seems to send data to https://dc.services.visualstudio.com/v2/track four times when trying to navigate to page 3. That does not happen in my sandbox tenant.

**Comment by HawkOn1** [comment] 2022-10-04 09:44
Same issue here.

**Comment by maximilien-raes** [comment] 2022-10-04 12:36
Same issue here. I tryed to revert to version 4.3.0 that was working on another tenant (sandbox tenant) but it keep the error on the production tenant : I can't go to step 3 and 4 of the wepart config.

**Comment by FranckyC** [comment] 2022-10-04 12:59
I'm not able to reproduce on my tenant :/. At first glance, it seems to be a SPFx/Dynamic data related issue as we didn't update anything on this specific page for a long time. Do you see any error in the SharePoint debug console (CTRL+F12?) by any chance? Also, do you have this issue without any connection between Web Parts (like Search Results or Search Filters alone)?

Thanks!

**Comment by maximilien-raes** [comment] 2022-10-04 13:08
Like @tandrasi  , I have an error in the browser console when I try to go to the step 3 of configuration  : 
![image](https://user-images.githubusercontent.com/54863194/193826886-b7e37553-aa91-48d0-80fe-17fa505d0467.png)

On the screenshot, this is a webpart that I linked to a PnP Filter Webpart, but the same error occur on a new SharePoint page when adding the Search Results webpart without any connections : when trying to move to step 3, there is an error in the console and I fall back to page 1.

**Comment by maximilien-raes** [comment] 2022-10-04 13:38
Yes 
![image](https://user-images.githubusercontent.com/54863194/193834159-9994807e-8ed8-4cd9-ba5b-aa263901b5b1.png)

**Comment by FranckyC** [comment] 2022-10-04 13:44
Seems to be a SPFx issue. Can you raise the same here https://github.com/SharePoint/sp-dev-docs/issues? Thanks! Also, you can dig into the error by clicking on the file name in the error message in the console and see if there is any relevant code that could help to understand the cause.

**Comment by SPKarsh** [comment] 2022-10-04 23:26
I'm getting the same issue. However, until yesterday it was working perfectly. 
![image](https://user-images.githubusercontent.com/115048762/193948610-b12290fa-4450-41d0-aa7b-5191c43d0e08.png)

**Comment by tandrasi** [comment] 2022-10-05 01:40
> Seems to be a SPFx issue. Can you raise the same here https://github.com/SharePoint/sp-dev-docs/issues? Thanks! Also, you can dig into the error by clicking on the file name in the error message in the console and see if there is any relevant code that could help to understand the cause.

@FranckyC - The fact that it affects only 2/4 of the webparts, tells me there is something else going on - I don't think it's a universal property pane issue or something with SPFx. As others have reported, it has worked fine until just a day ago (regardless of version used). 

As I've commented above, here are the web parts and what's happening to them. As you can see, you can indeed access pages 3 and 4 on the **PnP - Search Box** web part, but not the filter or results web parts:

> * PnP - Search Filters (issues, **cannot paginate to the 3rd page of the properties**)
> * PnP - Search Results (issues, **cannot paginate to 3rd of 4th page of the properties**)
> * PnP - Search Box (no issues, _**can paginate to all 4 pages of properties**_)
> * PnP - Search Verticals (no issues, can paginate to both pages of properties)

**Comment by Kanamo** [comment] 2022-10-05 13:19
Same issue here.

**Comment by Frau87** [comment] 2022-10-05 13:29
> I'm getting the same issue. However, until yesterday it was working perfectly. ![image](https://user-images.githubusercontent.com/115048762/193948610-b12290fa-4450-41d0-aa7b-5191c43d0e08.png)

Same Here

**Comment by Aikiman101** [comment] 2022-10-05 15:04
Exactly the same issue here, was working fine yesterday (04/10/22) but not working now.
Tried: 
- creating new page, 
- creating new page on a different site
- getting another team member to try. 

Steps 3&4 aren't available under any of these scenarios

**Comment by kewick** [comment] 2022-10-05 15:26
Same issue here with same error logs in the console. It worked all morning yesterday for me and then I created a few Managed Properties and thought it was tied to something I did there but see it's likely an unrelated bug. Echoing the comment below.

> Same issue here. Does anyone know any kind of temporarily solution?

**Comment by FranckyC** [comment] 2022-10-06 02:00
It definitely seems to be an issue introduced by SPFx regarding dynamic data. I tried to reproduce it in 3 tenants but didn't get this behavior so I can't really implement a fix for now.

**Comment by brianpmccullough** [comment] 2022-10-06 02:51
from #2412 

Version used
Ex: 4.7

Describe the bug
Using Search Results web part, clicking through to the 3rd or 4th page of web part properties is not possible. From second page, when clicking Next to navigate to 3rd page, it takes back to 1st page/panel. Also console errors are displayed.

This is a new issue as we had users configuring this as recently as Friday, September 30, 2022 (today being Wednesday, October 5, 2022).

I thought it might be an issue with the SPO/SPFx infrastructure, but was able to create a simple 1.15 webpart with 4 property panel pages and am able to navigate to them.

4.6.1 is deployed to the Tenant App Catalog in this environment, but please note that 4.7 version of Modern Search Web Parts deployed to Site Collection App Catalog, so 4.7 is being used in this case.

To Reproduce
Steps to reproduce the behavior:

Ensure 4.7 Modern Search Web Parts are deployed to Site Collection App Catalog.
Add a Search Results web part to a page.
Attempt to navigate to the 3rd page of web part properties
Note the errors in console.
Expected behavior
Be able to navigate to 3rd and 4th page of web part properties.

Screenshots
image001 (3)

image002

Desktop (please complete the following information):

Browser Chrome/Edge
Additional context
N/A

**Comment by tandrasi** [comment] 2022-10-06 03:25
Created the issue here on the SPFx repo as @FranckyC recommended: https://github.com/SharePoint/sp-dev-docs/issues/8483

**Comment by Georg-Trixl** [comment] 2022-10-06 06:56
We got the problem on tenant with Targeted Release and on tenant with Standard Release.

**Comment by h0lle** [comment] 2022-10-06 08:14
Same issue in our tenant (Standard Release)

**Comment by ekdegerman** [comment] 2022-10-06 15:23
Posted this same comment on the generic issue:
This recently started happening to us too. After another issue we faced today, I realized that it seems the common denominator for the tenants it happens in is that SharePoint is now using React 17. Tenants still using 16.13.1 still work fine. Hope this can help give a clue...
![image](https://user-images.githubusercontent.com/56835119/194353352-14be14e7-4008-416b-801c-d5a81b3d0746.png)

**Comment by viveksbhat** [comment] 2022-10-06 23:41
I am experiencing the exact same problem. I am using the version 4.7. 

Not able to connect Search results web part with none of the other web parts. I have another site where I had previously configured all the setup and the search is working fine there. If I try to edit I cant navigate 3rd and 4th property steps but it continues to work as the connection was setup previously.

Hope to see some resolution soon.

**Comment by 14Data** [comment] 2022-10-07 01:12
I am experiencing the exact same problem. I am using version 4.7.
It was working OK and is now failing as per other comments above.

**Comment by phoob** [comment] 2022-10-07 05:55
Same here ☹️

**Comment by moudhafersalhi** [comment] 2022-10-07 16:03
same with me. i tested on three tenants and only one of them is working. And on the two others it was working few days ago

**Comment by wobba** [comment] 2022-10-09 12:35
Is everyone who experience this using CDN?

**Comment by moudhafersalhi** [comment] 2022-10-09 12:50
> Is everyone who experience this using CDN?

Good point! The customer where it was working, wasn’t using cdn

**Comment by wobba** [comment] 2022-10-09 13:04
If it's CDN related I think it's a SPFx issue - and I don't use CDN on my dev tenant to ensure loading of the right files quicker.

**Comment by ekdegerman** [comment] 2022-10-10 06:50
> Is everyone who experience this using CDN?

Yes, we are using the public CDN, but it is enabled both for the working tenants and the failing ones. Only the ones where SharePoint Online started using react 17.0.1 are failing, the ones where it is still using 16.13.1 (ironically all of the targeted release dev tenants) still work fine with CDN enabled.

**Comment by wobba** [comment] 2022-10-10 07:04
@ekdegerman seems an issue should be logged at sp-dev-docs then if react 17 is causing this somehow. Is it purely a React 17 issue, or in combination with CDN is the question. Btw, do you know an easy way to check the react version used in a tenant?

**Comment by maximilien-raes** [comment] 2022-10-10 07:20
On my side, I'm not using CDN but I have this issue. It's probalby a React 17 issue yes.

**Comment by ekdegerman** [comment] 2022-10-10 07:30
> @ekdegerman seems an issue should be logged at sp-dev-docs then if react 17 is causing this somehow. Is it purely a React 17 issue, or in combination with CDN is the question. Btw, do you know an easy way to check the react version used in a tenant?

I mentioned the same the generic sp-dev-doc issue linked above and Alex tagged it with react-17, so they should be aware. The way I found it when we were having issues with one of our components was to use the React Developer Tools extension in Chrome or Edge. It adds a Components tab to the browser developer tools showing the component structure. Just click any component in the structure and it will show what version of react-dom it is rendered by: 
![image](https://user-images.githubusercontent.com/56835119/194816812-0d4bf092-b379-462f-b905-eb172c896333.png)

**Comment by omarelanis** [comment] 2022-10-10 10:21
Same issue noticed here on a tenant, running v17.0.2
![image](https://user-images.githubusercontent.com/35841910/194844960-021a25d0-36ba-43b6-85f2-6058c2efb7a6.png)

Considering SPFx since version 1.13.0 up to the current 1.15.2 version is only meant to support REACT version v16.13.1 should SharePoint have been upgraded?

Could this cause issues for other SPFx solutions and builds?

**Comment by Jeroen00** [comment] 2022-10-10 10:26
I can also confirm that on tenant with React 16.13.1 the issue does not occur but on tenant with version 17.0.1 it does.

**Comment by baldj** [comment] 2022-10-10 12:40
Does anyone know any temporary alternative to be able to access said pages 3 and 4? Thank you

**Comment by GerritGoudsmit** [comment] 2022-10-10 13:34
We have the same issue. On our tenant we have the REACT version 17.0.1. We have older pages with an older REACT version; there the issue does not appear.

**Comment by karinebosch** [comment] 2022-10-10 14:54
I have the same issue. 
I don't use a CDN.
It worked properly 2 weeks ago.
When I export the webpart properties, I can't see anything about available connections in the json. I attach the file as reference.
Is it possible to get a complete json so that I can try to configure a page programatically?
[pnpsearchresults-config-json.txt](https://github.com/microsoft-search/pnp-modern-search/files/9746969/pnpsearchresults-config-json.txt)

**Comment by imorrish** [comment] 2022-10-10 21:48
@karinebosch You can get the web part properties from a page that had the web part fully configured. Using PnP PowerShell
$content = (Get-PnPListItem -List SitePages -Fields "Title","CanvasContent1").FieldValues
$content.CanvasContent1

**Comment by samg365** [comment] 2022-10-11 04:19
@imorrish does that mean we could push configuration with PnP PowerShell too?
If you do know how to do that it would be great if you could point me in the right direction.
Thanks

**Comment by karinebosch** [comment] 2022-10-11 05:49
@imorrish.  Thanks! But  I attached my file with web part properties. I want someone from the team with a correctly working web part to do the same, to have a complete file that I can use to update my page programmatically in the hope to get my page working properly.

**Comment by karinebosch** [comment] 2022-10-11 05:51
@samg365 If I can lay my hands on a complete file with web part properties and I can make it work with CSOM, I'll provide you with my code.

**Comment by GerritGoudsmit** [comment] 2022-10-11 09:07
Obviously a rollback takes place. Different tenants have now a previous REACT version (16.13.1). The pages 3 and 4 are again available.

**Comment by CinziaTara** [comment] 2022-10-11 09:14
I have the same issue in my dev Tenant; my SharePoint is using React 17.0.1 too

**Comment by ekdegerman** [comment] 2022-10-11 09:17
It has been confirmed in the generic issue that a fix should be rolling out in the next 2 weeks: https://github.com/SharePoint/sp-dev-docs/issues/8483#issuecomment-1273494688

**Comment by wobba** [comment] 2022-10-11 17:45
I'll close this one then, and thanks to those who pushed this issue with SPFx :)

**Closed by wobba** 2022-10-11 17:45 UTC
Labels: v4, SPFx

**Comment by edarroudi** [comment] 2022-10-12 10:31
@wobba wouldn't it be better to let this issue open until it is really fixed for all tenants? You'll have to close several new issues until then. If this stays open, the users will find this issue faster due to the "is:issue is:open " filter...

**Comment by harshdamaniahd** [comment] 2022-10-12 10:45
> Obviously a rollback takes place. Different tenants have now a previous REACT version (16.13.1). The pages 3 and 4 are again available.

how can i check version of react?

**Comment by Jeroen00** [comment] 2022-10-12 12:29
> > Obviously a rollback takes place. Different tenants have now a previous REACT version (16.13.1). The pages 3 and 4 are again available.
> 
> how can i check version of react?

https://github.com/microsoft-search/pnp-modern-search/issues/2405#issuecomment-1272890833

**Comment by baldj** [comment] 2022-10-13 09:48
Hello,

I tested it today and access to pages 3 and 4 works. It's OK!!!

I've looked at the REACT render and it's 17.0.1.

Could it be that Microsoft has made some additional change that affected the component?

![2022-10-13_11h10_39](https://user-images.githubusercontent.com/40060333/195564117-8630d387-ba0f-48ca-9a83-e56487c6357f.png)

**Comment by dschenkd** [comment] 2022-10-13 09:48
> > Obviously a rollback takes place. Different tenants have now a previous REACT version (16.13.1). The pages 3 and 4 are again available.
> 
> how can i check version of react?
Easiest way to check (browser devtools console):
`window.React.version`

Unfortunately the only we can tell is that the version gets changed sometimes.

**Comment by CinziaTara** [comment] 2022-10-13 10:21
It works again for me too, with react 17.0.1

**Comment by edarroudi** [comment] 2022-10-13 10:55
Yeah, i have different tenants, works in 17.0.1 and 16.13.1 tenants

**Comment by kewick** [comment] 2022-10-13 17:44
Working for me as of this morning but React version now displaying 16.3.1 where yesterday it was 17.0.1. So surprised to see others versions did not roll back. But happy to see we are back in business. Thanks folks!
