### ISSUE TITLE
Correlation Error

### ISSUE THREAD

**Issue by paylord** [microsoft-search/pnp-modern-search#1268] opened 2021-09-07 01:13 UTC
**Version used**
4.3

**Describe the bug**
Search results throws a 500 correlation error if file extension is included in search box.

**To Reproduce**
1. Add Search Box to page
2. Add Search Results to page
3. Set source for Search Results to Search Box
4. Save page
5. Query for quoted file name including extension - eg "Test 2.docx" or "Test 2.xlsx"

**Expected behavior**
Either find or not find results.

**Screenshots**
![PnP500](https://user-images.githubusercontent.com/8131698/132268406-fa311aa8-cab7-46e6-b933-b46419fae9ee.png)

**Desktop (please complete the following information):**
 - Browser - Chrome

**Additional context**
Seems to be the same for the usual file extensions but does not throw the error for an unknown extension such as "Test 2.d".
Also note that it does not seem to fail if it is not quoted - eg Test 22.docx

**Comment by wobba** [comment] 2021-09-07 18:44
Duplicate of #1262

**Closed by wobba** 2021-09-07 18:44 UTC

**Comment by paylord** [comment] 2021-09-07 20:57
@wobba meh sorry - missed that one!
