### ISSUE TITLE
Issue while configuring Search result webpart

### ISSUE THREAD

**Issue by Narasireddy447** [microsoft-search/pnp-modern-search#234] opened 2020-05-05 06:18 UTC
Have downloaded to solution files and ran npm install command and i got all the node_modules. after that i have build the solution successfully,
i started workbench and while configuring the search result web part, getting following error
"Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"A null value was found for the property named 'Direction', which has the expected type 'Edm.Int32[Nullable=False]'. The expected type 'Edm.Int32[Nullable=False]' does not allow null values."}}}"

please help me if i am missing anything?

**Comment by Georg-Trixl** [comment] 2020-05-05 07:14
I got the same problem - but i started yesterday already with deeper analysis, to narrow down the problem. A to describe how the development team can reproduce this error. Still working on it - but now I have to go into 2 meetings. Maybe in 2 -3 hours  I have the whole description.

**Comment by wobba** [comment] 2020-05-05 08:20
For any SPFx project, use the hosted workbench at: https://tenant.sharepoint.com/sites/mysites/_layouts/15/workbench.aspx 

Always a better experience. Let me know if this helps? I have updated the docs as well to reflect this approach in https://github.com/microsoft-search/pnp-modern-search/commit/9b3a458490312cd9eae964b6e80cba3b0873baba

**Comment by Georg-Trixl** [comment] 2020-05-05 08:51
Okay @wobba got everything to reproduce the error on the simplest way. I hope that helps everyone to deal with it - or maybe there is something wrong on our tenant. 

**Version used**
Version 3.12.0 - downloaded today (with the fixed version number)

**Describe the bug**
Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"A null value was found for the property named 'Direction', which has the expected type 'Edm.Int32[Nullable=False]'. The expected type 'Edm.Int32[Nullable=False]' does not allow null values."}}}

**To Reproduce**
I have used the workbench and added only the _Search Results Webpart_. 
As _Search query keywords_ I used **test**
On second page of the configuration no change.
On third panel initially the webpart still renders okay, but if i switch to People layout, the error that @Takeda-scrm-O365-VJE0880 also described comes up.
Below the pictures i describe an other way to get to the error.
![Bug-V3 12-01](https://user-images.githubusercontent.com/62948158/81048023-d7df8500-8ebb-11ea-9202-c1e4b2fce97b.PNG)
![Bug-V3 12-02](https://user-images.githubusercontent.com/62948158/81048041-dd3ccf80-8ebb-11ea-9a0f-e1945d529b97.PNG)
![Bug-V3 12-03](https://user-images.githubusercontent.com/62948158/81048048-e0d05680-8ebb-11ea-92fc-0beaf49ec231.PNG)

**To Reproduce**
Simple add the Search Results Webpart to the workbench.
As _Search query keywords_ use **test**
On second page of configuration panel enter as Result source b09a7990-05ea-4af9-81ef-edfab16c4e31 ( _Local People Results_ )
The error shows immediately up. If I save the configuration and reload the page, then it is rendered without of a error.

**Information of Workbench _Web Part Data - Modern Pages_**

[{"controlType":3,"id":"a061c8e4-b2a9-436b-a3c4-a9688793bc8b","position":{"zoneIndex":1,"sectionIndex":1,"controlIndex":1,"layoutIndex":1},"webPartId":"42ad2740-3c60-49cf-971a-c44e33511b93","webPartData":{"id":"42ad2740-3c60-49cf-971a-c44e33511b93","instanceId":"a061c8e4-b2a9-436b-a3c4-a9688793bc8b","title":"Search&nbsp;Results","description":"Displays&nbsp;search&nbsp;results","serverProcessedContent":{"htmlStrings":{},"searchablePlainTexts":{},"imageSources":{},"links":{}},"dynamicDataPaths":{},"dynamicDataValues":{"queryKeywords":"test"},"dataVersion":"1.0","properties":{"queryTemplate":"{searchTerms}","sortList":[{"sortField":"Created","sortDirection":1},{"sortField":"Size","sortDirection":2}],"selectedProperties":"Title,Path,Created,Filename,SiteLogo,PreviewUrl,PictureThumbnailURL,ServerRedirectedPreviewURL,ServerRedirectedURL,HitHighlightedSummary,FileType,contentclass,ServerRedirectedEmbedURL,ParentLink,DefaultEncodingURL,owstaxidmetadataalltagsinfo,Author,AuthorOWSUSER,SPSiteUrl,SiteTitle,IsContainer,IsListItem,HtmlFileType,SiteId,WebId,UniqueID,OriginalPath,FileExtension,NormSiteID,NormListID,NormUniqueID,AccountName,FirstName,LastName,Department,JobTitle,WorkPhone","enableQueryRules":false,"includeOneDriveResults":false,"showBlank":true,"showResultsCount":true,"webPartTitle":"","enableLocalization":true,"useDefaultSearchQuery":false,"resultTypes":[],"useExternalRefinersDisplay":false,"useExternalPaginationDisplay":false,"appliedRefiners":[],"refinersConfiguration":[],"sortableFields":[],"synonymList":[],"searchQueryLanguage":-1,"templateParameters":{"detailsListColumns":[{"name":"Title","value":"Title","useHandlebarsExpr":false,"minWidth":"80","maxWidth":"300","enableSorting":true,"isMultiline":false,"isResizable":true,"isResultItemLink":true},{"name":"Created","value":"{{getDate&nbsp;Created&nbsp;'LL'}}","useHandlebarsExpr":true,"minWidth":"80","maxWidth":"120","enableSorting":false,"isMultiline":false,"isResizable":false,"isResultItemLink":false},{"name":"Summary","value":"{{getSummary&nbsp;HitHighlightedSummary}}","useHandlebarsExpr":true,"minWidth":"80","maxWidth":"300","enableSorting":false,"isMultiline":true,"isResizable":false,"isResultItemLink":false}],"showFileIcon":true,"peopleFields":[{"name":"Image&nbsp;Url","field":"imageUrl","value":"{{#with&nbsp;(split&nbsp;AccountName&nbsp;'|')}}/_layouts/15/userphoto.aspx?size=L&amp;username={{[2]}}{{/with}}","useHandlebarsExpr":true,"supportHtml":false},{"name":"Primary&nbsp;Text","field":"text","value":"{{FirstName}}&nbsp;{{LastName}}","useHandlebarsExpr":true,"supportHtml":false},{"name":"Secondary&nbsp;Text","field":"secondaryText","value":"JobTitle","useHandlebarsExpr":false,"supportHtml":false},{"name":"Tertiary&nbsp;Text","field":"tertiaryText","value":"{{#with&nbsp;(split&nbsp;AccountName&nbsp;'|')}}{{[2]}}{{/with}}","useHandlebarsExpr":true,"supportHtml":false},{"name":"Optional&nbsp;Text","field":"optionalText","value":"WorkPhone","useHandlebarsExpr":false,"supportHtml":false}],"personaSize":14},"queryModifiers":[],"refinementFilters":"","paging":{"itemsCountPerPage":10,"pagingRange":5,"showPaging":true,"hideDisabled":true,"hideFirstLastPages":false,"hideNavigation":false},"selectedLayout":5,"defaultSearchQuery":"","resultSourceId":"b09a7990-05ea-4af9-81ef-edfab16c4e31"}},"emphasis":{},"reservedHeight":2170,"reservedWidth":727,"addedFromPersistedData":true}]

**Comment by Takeda-scrm-O365-VJE0880** [comment] 2020-05-05 09:29
> Okay @wobba got everything to reproduce the error on the simplest way. I hope that helps everyone to deal with it - or maybe there is something wrong on our tenant.
> 
> **Version used**
> Version 3.12.0 - downloaded today (with the fixed version number)
> 
> **Describe the bug**
> Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"A null value was found for the property named 'Direction', which has the expected type 'Edm.Int32[Nullable=False]'. The expected type 'Edm.Int32[Nullable=False]' does not allow null values."}}}
> 
> **To Reproduce**
> I have used the workbench and added only the _Search Results Webpart_.
> As _Search query keywords_ I used **test**
> On second page of the configuration no change.
> On third panel initially the webpart still renders okay, but if i switch to People layout, the error that @Takeda-scrm-O365-VJE0880 also described comes up.
> Below the pictures i describe an other way to get to the error.
> ![Bug-V3 12-01](https://user-images.githubusercontent.com/62948158/81048023-d7df8500-8ebb-11ea-9202-c1e4b2fce97b.PNG)
> ![Bug-V3 12-02](https://user-images.githubusercontent.com/62948158/81048041-dd3ccf80-8ebb-11ea-9a0f-e1945d529b97.PNG)
> ![Bug-V3 12-03](https://user-images.githubusercontent.com/62948158/81048048-e0d05680-8ebb-11ea-92fc-0beaf49ec231.PNG)
> 
> **To Reproduce**
> Simple add the Search Results Webpart to the workbench.
> As _Search query keywords_ use **test**
> On second page of configuration panel enter as Result source b09a7990-05ea-4af9-81ef-edfab16c4e31 ( _Local People Results_ )
> The error shows immediately up. If I save the configuration and reload the page, then it is rendered without of a error.
> 
> **Information of Workbench _Web Part Data - Modern Pages_**
> 
> [{"controlType":3,"id":"a061c8e4-b2a9-436b-a3c4-a9688793bc8b","position":{"zoneIndex":1,"sectionIndex":1,"controlIndex":1,"layoutIndex":1},"webPartId":"42ad2740-3c60-49cf-971a-c44e33511b93","webPartData":{"id":"42ad2740-3c60-49cf-971a-c44e33511b93","instanceId":"a061c8e4-b2a9-436b-a3c4-a9688793bc8b","title":"Search Results","description":"Displays search results","serverProcessedContent":{"htmlStrings":{},"searchablePlainTexts":{},"imageSources":{},"links":{}},"dynamicDataPaths":{},"dynamicDataValues":{"queryKeywords":"test"},"dataVersion":"1.0","properties":{"queryTemplate":"{searchTerms}","sortList":[{"sortField":"Created","sortDirection":1},{"sortField":"Size","sortDirection":2}],"selectedProperties":"Title,Path,Created,Filename,SiteLogo,PreviewUrl,PictureThumbnailURL,ServerRedirectedPreviewURL,ServerRedirectedURL,HitHighlightedSummary,FileType,contentclass,ServerRedirectedEmbedURL,ParentLink,DefaultEncodingURL,owstaxidmetadataalltagsinfo,Author,AuthorOWSUSER,SPSiteUrl,SiteTitle,IsContainer,IsListItem,HtmlFileType,SiteId,WebId,UniqueID,OriginalPath,FileExtension,NormSiteID,NormListID,NormUniqueID,AccountName,FirstName,LastName,Department,JobTitle,WorkPhone","enableQueryRules":false,"includeOneDriveResults":false,"showBlank":true,"showResultsCount":true,"webPartTitle":"","enableLocalization":true,"useDefaultSearchQuery":false,"resultTypes":[],"useExternalRefinersDisplay":false,"useExternalPaginationDisplay":false,"appliedRefiners":[],"refinersConfiguration":[],"sortableFields":[],"synonymList":[],"searchQueryLanguage":-1,"templateParameters":{"detailsListColumns":[{"name":"Title","value":"Title","useHandlebarsExpr":false,"minWidth":"80","maxWidth":"300","enableSorting":true,"isMultiline":false,"isResizable":true,"isResultItemLink":true},{"name":"Created","value":"{{getDate Created 'LL'}}","useHandlebarsExpr":true,"minWidth":"80","maxWidth":"120","enableSorting":false,"isMultiline":false,"isResizable":false,"isResultItemLink":false},{"name":"Summary","value":"{{getSummary HitHighlightedSummary}}","useHandlebarsExpr":true,"minWidth":"80","maxWidth":"300","enableSorting":false,"isMultiline":true,"isResizable":false,"isResultItemLink":false}],"showFileIcon":true,"peopleFields":[{"name":"Image Url","field":"imageUrl","value":"{{#with (split AccountName '|')}}/_layouts/15/userphoto.aspx?size=L&username={{[2]}}{{/with}}","useHandlebarsExpr":true,"supportHtml":false},{"name":"Primary Text","field":"text","value":"{{FirstName}} {{LastName}}","useHandlebarsExpr":true,"supportHtml":false},{"name":"Secondary Text","field":"secondaryText","value":"JobTitle","useHandlebarsExpr":false,"supportHtml":false},{"name":"Tertiary Text","field":"tertiaryText","value":"{{#with (split AccountName '|')}}{{[2]}}{{/with}}","useHandlebarsExpr":true,"supportHtml":false},{"name":"Optional Text","field":"optionalText","value":"WorkPhone","useHandlebarsExpr":false,"supportHtml":false}],"personaSize":14},"queryModifiers":[],"refinementFilters":"","paging":{"itemsCountPerPage":10,"pagingRange":5,"showPaging":true,"hideDisabled":true,"hideFirstLastPages":false,"hideNavigation":false},"selectedLayout":5,"defaultSearchQuery":"","resultSourceId":"b09a7990-05ea-4af9-81ef-edfab16c4e31"}},"emphasis":{},"reservedHeight":2170,"reservedWidth":727,"addedFromPersistedData":true}]

**Comment by Takeda-scrm-O365-VJE0880** [comment] 2020-05-05 15:10
any workaround for the below issue.
"Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"A null value was found for the property named 'Direction', which has the expected type 'Edm.Int32[Nullable=False]'. The expected type 'Edm.Int32[Nullable=False]' does not allow null values."}}}"

**Comment by wobba** [comment] 2020-05-05 15:27
@FranckyC

**Comment by luismanez** [comment] 2020-05-06 08:05
and this one also seems due to https://github.com/microsoft-search/pnp-modern-search/issues/237

**Comment by wobba** [comment] 2020-05-06 13:15
Duplicate of #237

**Closed by wobba** 2020-05-06 13:15 UTC
Labels: bug
