### ISSUE TITLE
PnP Search Box web part doesn't load on iPhone

### ISSUE THREAD

**Issue by ollij** [microsoft-search/pnp-modern-search#1005] opened 2021-05-18 08:06 UTC
**Version used**
4.1.0

**Describe the bug**
Search Box Web Part fails to load on iPhone Edge with the following error message:

[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Failed to load entry point from component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Error loading https://relative-path.invalid/tslib as "tslib" from https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.1.0
Unable to load script https://relative-path.invalid/tslib

INNERERROR:
Failed to load entry point from component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Error loading https://relative-path.invalid/tslib as "tslib" from https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.1.0
Unable to load script https://relative-path.invalid/tslib
CALLSTACK:
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-home-assembly_fi-fi_eafb63fcaaa60086f3a176abc49d3437.js:65:19853
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-home-assembly_fi-fi_eafb63fcaaa60086f3a176abc49d3437.js:65:117815
t@[native code]
https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-home-assembly_fi-fi_eafb63fcaaa60086f3a176abc49d3437.js:65:155632
https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_fi-fi_f36466c71405b672f34a.js:1:66043
promiseReactionJob@[native code]

**To Reproduce**
1. Install PnP Modern Search V4
2. Add and configure PnP Search Box Web part to a page in SharePoint
3. Open the page in iPhone Edge browser

**Expected behavior**
Search Box Web Part loads normally.

**Desktop (please complete the following information):**
 - Browser iPhone Edge

**Additional context**
Works perfectly well on desktop browsers.

**Comment by wobba** [comment] 2021-05-18 09:34
Duplicate of #685

**Closed by wobba** 2021-05-18 09:34 UTC
