### ISSUE TITLE
Filter/Refiner panel not displaying filtered fields

### ISSUE THREAD

**Issue by smitman3405** [microsoft-search/pnp-modern-search#720] opened 2021-01-28 20:08 UTC
I've added terms to the term store and created managed metadata columns to those items in the SitePages library.  I've tagged some pages with the terms via page properties but I'm not getting any results in the Filters webpart.  I've even gone as far as mapping the fields in the Managed Properties in Search in SPO Admin (RefinableString00).
I've also tried adding a choice column to the list but that choice field does not show up in the choices when setting up the custom filters in the Filters Webpart.
I'm using the latest PNP Modern Search release.  
What am I missing???

![image](https://user-images.githubusercontent.com/10451710/106192080-b75a0800-6179-11eb-85c3-2dc8e4c7374b.png)
![image](https://user-images.githubusercontent.com/10451710/106192272-f25c3b80-6179-11eb-85f9-d94ebd8f1abd.png)
![image](https://user-images.githubusercontent.com/10451710/106192361-13bd2780-617a-11eb-9fc7-7e3edaf872f1.png)
![image](https://user-images.githubusercontent.com/10451710/106192515-49621080-617a-11eb-9cbf-a25c7748ad9b.png)

**Comment by FranckyC** [comment] 2021-01-29 01:10
Hi @smitman3405, in the filter configuration, you must use `RefinableString00` as the filter field name. The screenshot you provided indicates this is not the case.  It the value doesn't appear in the dropdown, type it manually in the field and press "Enter".

**Comment by smitman3405** [comment] 2021-01-29 10:59
Thank you!!!  I never thought to type in the value, I thought I'd only have access to the ones in the drop down.

Now I have another question.  Do you know how to modify the search results template so just the values of the taxonomy items show and not the L0|#<guid>|
![image](https://user-images.githubusercontent.com/10451710/106266939-0003d680-61f7-11eb-9f3b-4c096ded00ee.png)

I'm guessing the Value#<guid> in the refiners is because I was including the actual ows_taxid_System_x0020_Tags in the crawl.  I've removed that and need to wait for the data to be crawled again before it will disappear.
![image](https://user-images.githubusercontent.com/10451710/106267021-16119700-61f7-11eb-9cf3-22f892196fc3.png)

**Comment by wobba** [comment] 2021-01-29 16:23
Closing as original question is answered. Label vs guid is covered in docs and other issues.

**Closed by wobba** 2021-01-29 16:23 UTC

**Comment by sympmarc** [comment] 2021-04-06 18:40
@wobba I just ran into the label vs. GUID issue for taxomony fields, and I can't find anything in the docs to help me fix it. I know I've solved it before, but I'm coming up empty this time. Could you provide a link?

Managed Property:
![image](https://user-images.githubusercontent.com/1295627/113761943-09715980-96e6-11eb-8eb6-3c8efb3a3385.png)

PnP Filters:
![image](https://user-images.githubusercontent.com/1295627/113761499-87813080-96e5-11eb-8cce-b8d8c804475d.png)

PnP Search Results:
![image](https://user-images.githubusercontent.com/1295627/113761610-a7b0ef80-96e5-11eb-9ebe-f55de9cd5b4e.png)

**Comment by wobba** [comment] 2021-04-07 18:17
I agree it could be better explained, but mentioned for v3 at https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#miscellaneous-taxonomy-values-dynamic-translation 

v4 covers it at https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/#source-configuration under `Enable localization`.

In v4 using a custom handlebars template and string splitting could also work.

**Comment by sympmarc** [comment] 2021-04-07 20:03
Thanks! Adding auto before owstaxidmetadataalltagsinfo in the slots

![image](https://user-images.githubusercontent.com/1295627/113926647-6dfde880-97ba-11eb-88a9-a088991f9630.png)

fixes the List display:

![image](https://user-images.githubusercontent.com/1295627/113926780-9dacf080-97ba-11eb-8306-c442b730d4a6.png)

I guess the questions then becomes: why would anyone ever *not* want to just see the label there?

**Comment by wobba** [comment] 2021-04-07 20:37
Good question and haven't looked into that part of the templates. Maybe @FranckyC can shed some light.

**Comment by sympmarc** [comment] 2021-04-07 20:55
I think you're technically on vacation, so thanks for the help here.

**Comment by FranckyC** [comment] 2021-04-08 12:58
Hi @sympmarc 

> I guess the questions then becomes: why would anyone ever not want to just see the label there?

At the time in v3, we updated the translation process to let developers to use the raw term GUIDs instead of translating the value every time in the JSON response, for example, to be able to process values using a web component or a custom Handlebars helper. With v4, and for the default scenario maybe, we could just set the 'Auto' property prefix for the "Tags" slot to avoid confusion. However, the 'owstaxidmetadataalltagsinfo' mapping is simply an example as people would unlikely use this value in a real world scenario.

> Also, the tags have links like the following:
> https://[tenant].sharepoint.com/SitePages/Policy-Center.aspx#United%20States:'United%20States'
> That doesn't accomplish anything. Is it a bug?

This is not a bug. It is intended to work with a search box/search results in the same or other page using the 'URL Fragment' as source. This way, users could "refine" by term labels (or even connect Web Parts together). Again, it is more like an example. Maybe I could add comment in the template to explain possible usage.

**Comment by sympmarc** [comment] 2021-04-08 13:16
I think there's a bunch of value locked in these Web Part that people can't reasonably fathom in the current documentation. I would love to try to help, but I need to understand things first!

Some of this could be scenario-based: for example, "I want to build a page showing content with refiners that are Managed Metadata columns". That sort of thing doesn't fit into the "documentation" model, but it is what will make these Web Parts even more useful.

**Comment by FranckyC** [comment] 2021-04-08 13:28
That would be awesome of course. We can create a "Tutorials" or "Scenarios" section in the documentation with step by step + videos. If you already have scenarios in mind, you can already add them to the documentation. We will help for the configuration/technical part for sure.
