### ISSUE TITLE
PnP - Search Results - People cards triggers issue where the site/page reloads 2-3 times

### ISSUE THREAD

**Issue by thosjo95** [microsoft-search/pnp-modern-search#3915] opened 2024-08-20 07:43 UTC
### Follow the template below or we will have to delete this request!!
We can assist a lot faster if you provide the following information:

**Version used**
4.9.3

**Describe the bug**
Where ever on my SharePoint Sites and pages I have the PnP - Search Results (Person Card) added, and the result returns  the site refreshes and prompts a user logon 2-3 times before coming stable.

I have a screen recording of the issue here: [https://likeitas-my.sharepoint.com/:v:/g/personal/thomas_like-it_no/EeqRcRy0BxxLpdnSLh9tDZMB1nxXQOrMxgwdrGEqtaQjAA?e=NZZCbf](url)

First I thought this was only on pages/sites where the search results gave >30 people/user profiles. But after running diagnostics, it happens everywhere the people cards are being used.

I've tried using multiple browsers, and the same seems to happen. I've not configured any special/out of ordinary properties or slots for the data source.

Please note that I've been using the PnP - Search results in many other scenarios in my environment like document and site handling, but that's working 100% fine. I've never had this issue with that.

I've ran the [Use the Page Diagnostics tool for SharePoint Online - Microsoft 365 Enterprise | Microsoft Learn](https://learn.microsoft.com/en-us/microsoft-365/enterprise/page-diagnostics-for-spo?view=o365-worldwide) and it gives me some worrying results. The amount of requests (API) on the pages/sites the PnP search results with people cards is returning profiles is around 45-55. 

**Screenshots**
The red flags are (from a page/site) with around 7600 search results (user profiles/people cards):
Some issues regarding to CDN. Seen this one on other sites without any problem as well, and I don't think it related to the issue.
![image](https://github.com/user-attachments/assets/13c71129-17cf-4937-b652-16f31bdadb21)

![image](https://github.com/user-attachments/assets/0673e30a-34ea-4665-bbbb-beaea6b0122c)
![image](https://github.com/user-attachments/assets/5f918355-c487-4a47-a863-e83ab82d8cb8)
![image](https://github.com/user-attachments/assets/082107c3-e543-4c68-a3c5-2130d767a8f6)
![image](https://github.com/user-attachments/assets/f0b69d76-a185-4048-bd9f-d90f8ccf4a8e)
![image](https://github.com/user-attachments/assets/5f37a2d6-87a0-43cb-8a38-975293f8b9d6)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to any page/site on my Sharepoint Sites with the PnP - Search Result People card returning user profiles.
2. The page/site opens, and immediately refreshes itself prompting me to logon to O365 2-3 times in a row.
3. Refreshing the site then, or going to another site with the same config doesn't retrigger the issue. Only if I close and reopen my browser and to the same again.

**Expected behavior**
This started occurring in june. Was all good when first set up in april.

**Desktop (please complete the following information):**
 Tried browsers:
-Edge
-Chrome
-Brave
Also tried em all after clearing cache and temp files. Plus incognito.

**Additional context**

**Comment by thosjo95** [comment] 2024-08-20 18:13
I'll try that and reach back. Thank you!

**Comment by kasperbolarsen** [comment] 2024-08-27 06:29
Hi @thosjo95  I have sent you an invite for a PnP Modern Search Office Hours call for later today, but haven't received an answer. Have you resolved the issue and then, how ?

**Comment by thosjo95** [comment] 2024-08-27 07:00
Hello Kasper,

I’m sorry but I’m not able to attend the meeting and do any troubleshooting this week.

I will reach out to you via the forms if I need another meeting.

I’ll do What was suggested in the github first - update to latest version. I’ll do that as soon as I’m able, and update you on the result

Br,
Thomas S

Med vennlig hilsen,
Thomas Sjøvold
________________________________
Fra: Kasper Larsen ***@***.***>
Sendt: Tuesday, August 27, 2024 8:30:01 AM
Til: microsoft-search/pnp-modern-search ***@***.***>
Kopi: thosjo95 ***@***.***>; Mention ***@***.***>
Emne: Re: [microsoft-search/pnp-modern-search] PnP - Search Results - People cards triggers issue where the site/page reloads 2-3 times (Issue #3915)


Hi @thosjo95<https://github.com/thosjo95> I have sent you an invite for a PnP Modern Search Office Hours call for later today, but haven't received an answer. Have you resolved the issue and then, how ?

**Comment by wobba** [comment] 2024-09-08 09:47
Closing this and feel free to log a new issue if the issue is present on the latest release as we don't triage or fix issues for older versions. And we know the Graph Toolkit has been updated since the version you are using.

**Closed by wobba** 2024-09-08 09:47 UTC
Labels: Needs: Author Feedback
