### ISSUE TITLE
Custom metadata for Search (search box) like advanced.aspx

### ISSUE THREAD

**Issue by TiloGit** [microsoft-search/pnp-modern-search#2094] opened 2022-05-18 18:36 UTC
**Is your feature request related to a problem? Please describe.**
Trying to search by metadata /custom column. 

**Describe the solution you'd like**
possibility to add columns to the search box or have an advanced search box which support metadata

**Describe alternatives you've considered**

- Use refiners to add all keywords/metadata I want to search
- SP OOTB via [advanced.aspx](https://www.sharepointdiary.com/2019/01/sharepoint-online-advanced-search-add-property-restrictions.html) to Search metadata in SP advanced search. 
- [Search for metadata in document libraries in Microsoft SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/metadata-search) 

**Additional context**

**Comment by wobba** [comment] 2022-05-20 16:15
We have no plans to build out with a more advanced search box similar to classic, as it's very few people who will use this. There are scenarios where it is valuable for specific horizontal and vertical solutions.

Duplicate of #593

**Closed by wobba** 2022-05-20 16:15 UTC
