### ISSUE TITLE
People Layout causes filter web part to stack vertically even when set to horizontal layout

### ISSUE THREAD

**Issue by corriespondent** [microsoft-search/pnp-modern-search#1179] opened 2021-07-27 15:51 UTC
**Version used**
4.3.0

**Describe the bug**
When using the Filters web part in horizontal layout, using the People Layout causes the filters to be stacked vertically. Upon inspection, the Filters CSS is not loaded in the style tag (see screenshot below).

**To Reproduce**
1. Set up a page with PnP Modern Search v4 Search Results web part and select People layout.
2. Add Filters web part (obviously set it up to ensure that Filters web part will display options) and set up using Horizontal layout.
3. The Filters web part will display properly in edit mode, but once you save the page, the filters will stack vertically (and if you inspect, the STYLE tag is empty).
4. Try changing the search results web part to use any other layout, and the filters web part will lay out horizontally again.

**Expected behavior**
The people layout should not break the styling for the filters web part!

**Screenshots**
![image](https://user-images.githubusercontent.com/23064475/127183581-7f61cae4-641d-434f-a36b-31618b8c0fd2.png)

**Desktop (please complete the following information):**
 - Browser: Chrome, IE

**Additional context**
We have reproduced this issue on three separate tenants (dev and production). Oddly, we have one dev tenant where this issue does not occur.

**Comment by CreativeAcer** [comment] 2021-08-17 08:23
I just tested this with V4.0 (Januari 2021) and i cannot reproduce the issue in that version. 
After upgrading to 4.3 (July 2021) everything still works as expected, installing 4.3.0 in a seperate tenant also worked as intended.

Are you using a custom template anywhere ?

**Comment by corriespondent** [comment] 2021-08-17 14:59
Hi! I was doing my testing with 4.3 as downloaded straight from the repo, with only normal configurations for setting up the people results and filters. There are no custom filter or result templates in use for that web part in my tests. On three tenants, 2/3 displayed the issue where styles were not applied initially; however, since then as I have checked back -- with no changes -- one of them is now working properly...!! So now I have 1 tenant with the issue. I have no idea what is different between the different environments to have caused this issue, and why one of them started working.


________________________________

**Comment by wobba** [comment] 2021-08-19 11:29
Do you have multiple web parts on the page?

**Comment by corriespondent** [comment] 2021-08-19 19:29
Hi! I do not have any other web parts on the page, just the PnP search filters and PnP search results web parts. We created a brand new communication site, brand new page, and I dropped those two web parts on and configured them. Screenshots below show that the search filter is set to horizontal:
[cid:8500787e-b45b-4e50-aa08-175fa6f9cac2]

The filters display properly in edit mode, but after publish, they stack vertically:

[cid:8e9e1c12-4e0e-4fea-889d-2b1d3dcb73e3]

This tenant does have PnP Search v3 already (being used for existing pages), but I uploaded the latest v4.3.0 sppkg to the app catalog when testing again.
[cid:23ea7765-6942-42ce-834e-4306a7a76f8f]

Note that this happened for me in two different tenants, but a third tenant was working fine. One of the two tenants has magically fixed itself, but the original tenant -- a client production tenant -- is still showing this issue.

Thank you again for reaching out!

________________________________

**Comment by HamEv** [comment] 2021-08-22 11:51
I have also problems with my filter webpart on a search result page with people results.
When adding my filter webpart in the vertical section of my page everything works perfect (expect die CSS formatting), filtering works:

![grafik](https://user-images.githubusercontent.com/61208008/130353978-84e4b8be-9307-46cc-8b40-b54a2bcec292.png)

When I move the filter webpart to the horizontal section of my page all filter results are disaparing and the webpart is shown empty. Here you can see the page in edit mode (after moving it):

![grafik](https://user-images.githubusercontent.com/61208008/130354015-dc49979c-c934-4c01-938b-fa413bc87df7.png)

And here the page in view-mode:

![grafik](https://user-images.githubusercontent.com/61208008/130354028-9b472768-8f08-45ae-8132-a0b5b708705c.png)


Would be great, if the filter webpart works in both sections.

**Comment by wobba** [comment] 2023-05-27 16:25
I tested a bit and it seems to work as expected assuming the column/region it's places has enough space to render it horizontally. If not it will wrap and look vertical.

**Closed by wobba** 2023-05-27 16:25 UTC
Labels: Needs: Triage, v4
