### ISSUE TITLE
Issue with User profile properties in KQL and using result source ID

### ISSUE THREAD

**Issue by spicht** [microsoft-search/pnp-modern-search#1325] opened 2021-09-21 13:23 UTC
Hello Modern Search Team,

I have some issues with an environment where I use a combination of 4 user profile properties mapped to taxonomy and their according managed properties. 

On Version 3 of PnP Search I used this KQL:

`{|RefinableString10:{User.Property1}} AND {|RefinableString11:{User.Property2}} AND {|RefinableString12:{User.Property3}} AND {|RefinableString13:User.{Property4}} `

which worked like a charm. 

Now with version 4.3.0 (and an earlier version of 4) it's not working as soon, as I use multiple tags within the user profile property. If I only put one tag into the property it works. 

When I create a result source with that same KQL it works as well. If I put it into the Microsoft Highlighted content Webpart it works as well. 

I tried to use the result source within the PNP Searchresults webpart instead, but it doesn't work either, I only ever get 0 items.

**Comment by wobba** [comment] 2021-09-21 14:18
Closing as the issue is not using any of the issue templates.

**Closed by wobba** 2021-09-21 14:18 UTC
Labels: type:incomplete-submission
