### ISSUE TITLE
Inconsistent previews based for files

### ISSUE THREAD

**Issue by ishaisagi** [microsoft-search/pnp-modern-search#820] opened 2021-03-01 05:37 UTC
**Version used**
4

**Describe the bug**
when searching for content, some searches return the results and show the preview images for them, and some show a placeholder image instead. If you change the search term so that only some of the files are returned, the same files are returned, but the ones that did not have a preview now have a preview.

**To Reproduce**
1. Uploaded 4 files - 3 pdfs (generated by word, using the rand() function for random content) and one html to a document library. name them "document 1.pdf", "document 2.pdf","document 3.pdf","document 4.htm"
2. wait for index
3. use search box web part to do a search that returns all content using the "document" (part of file name)
4. some files have previews, others do not:
![nopreview](https://user-images.githubusercontent.com/32532384/109455829-8e47d280-7aab-11eb-835d-5107fa39f5b0.jpg)
5. do another search - this time for a word that returns the document that doesnt have the preview, and it comes up with a preview
![preview](https://user-images.githubusercontent.com/32532384/109455855-a3246600-7aab-11eb-9823-73af1b8b214d.jpg)
6. search again - this time so that the two "problem" files are returned - result is that one shows with preview, one with a blank (broken image)
![preview and nopreview](https://user-images.githubusercontent.com/32532384/109456005-00201c00-7aac-11eb-91d9-33c98ca3112b.jpg)

note this happens both in edit mode and when page is published - both in sandbox and in an actual page

**Expected behavior**
The preview should show after every search for each file

**Screenshots**
![nopreview](https://user-images.githubusercontent.com/32532384/109456026-09a98400-7aac-11eb-965b-19d18b8f8715.jpg)
![preview and nopreview](https://user-images.githubusercontent.com/32532384/109456031-0adab100-7aac-11eb-9c26-b5c72f05ac12.jpg)
![preview](https://user-images.githubusercontent.com/32532384/109456033-0b734780-7aac-11eb-93a0-e5d3b66b8998.jpg)

**Desktop (please complete the following information):**
 - chrome and firefox on windows 10

**Comment by wobba** [comment] 2021-03-01 09:45
Duplicate of #784 and #689 .

**Closed by wobba** 2021-03-01 09:45 UTC
