### ISSUE TITLE
Please add the option to set the items per page (in all layouts) to be set by the user

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft-search/pnp-modern-search#1197] opened 2021-08-09 19:15 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
items per page (in all layouts) is only available in the web part properties. So it is fixed for the page containing the PnP search results web part.
My users asked to be able to change at run time because some users have big monitors and some work only on laptops. 
If the property can denote "user changeable" (or something like that) the user will get a dropdown with few options to set the items per page near the pager control (like in many table controls)

**Describe alternatives you've considered**
alternative solutions I considered was to change the PnP search results web part. Too complicated for me and no advantage to others 

Thank you for great product

**Comment by bryllyg** [comment] 2021-08-17 17:53
Seconding :-) We have also had requests for this functionality.

**Comment by wobba** [comment] 2021-08-29 11:56
Duplicate of #822

**Closed by wobba** 2021-08-29 11:56 UTC
Labels: enhancement, v4
