### ISSUE TITLE
Hiding v4 Search box for IOS

### ISSUE THREAD

**Issue by jamesforsytheiv** [microsoft-search/pnp-modern-search#996] opened 2021-05-13 13:00 UTC
**Version used**
Ex: 4

**Describe the bug**
We have so many users using all devices, we cannot use the new awesome v4 box, because it is not supported for IOS/Safari and disrupts the other OOB webparts on the page.

We tried hiding it from IOS users using javascript/CSS... works perfectly but the v4 search box blows up all the other OOB web parts that render after it on the page.

Is there something I could add to the solution to make it able to coexist with the other OOB webparts? 

It doesnt affect the other search webparts only the MS ones like events, highlighted content, quick links...

**To Reproduce**
Add search v4 box to page and then add other webparts further down page, view in IOS the OOB webparts intermittently display [object Object] error.

**Expected behavior**
Just hoping to find out more to try and make this work for everyone. Dont expect it to work in IOS, but hoping it can be used and hidden on page without reducing the IOS experience with errors

**Comment by wobba** [comment] 2021-05-14 15:08
Safari issues should be resolved in the dev branch, and appear in v4.2 when released. Duplicate of #685.

**Closed by wobba** 2021-05-14 15:08 UTC
