### ISSUE TITLE
Every other search preview image does not display an image pnp modern search

### ISSUE THREAD

**Issue by VishalLinde** [microsoft-search/pnp-modern-search#1310] opened 2021-09-17 08:46 UTC
### Kindly go through the attached screenshot for your reference

**Version used**
Ex: 4.0

**Describe the bug**
Alternative image preview is not working

![MicrosoftTeams-image](https://user-images.githubusercontent.com/90893284/133753355-bc03eec6-5855-43f3-98f5-663bb4f6c55b.png)

**Comment by Laul0** [comment] 2021-09-17 16:03
Hi @VishalLinde,

Can you provide more information about the steps to reproduce your issue?
Your issue is linked to the SharePoint Pages? SharePoint library with images? What are the objects returned by your search results?
Did you edit the `Selected properties` of the Search Results?

**Comment by wobba** [comment] 2021-09-19 15:35
@VishalLinde if you are using v4.0, upgrade to a later version and this should be fixed. Duplicate of #863

**Closed by wobba** 2021-09-19 15:35 UTC
Labels: v4
