### ISSUE TITLE
Search result page error

### ISSUE THREAD

**Issue by spo365** [microsoft-search/pnp-modern-search#326] opened 2020-06-23 05:29 UTC
**Version used**
Ex: 3.7

**Describe the bug**
When user type any keyword to search box getting below error 

Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}

**To Reproduce**
1. Go to 'search result page'
2. Add keyword 
3. Hit enter '
Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}
**Expected behavior**
Bring the search result base on the keyword.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kachihro** [comment] 2020-06-23 06:35
Duplicate of #325

**Closed** 2020-06-23 07:56 UTC

**Comment by spo365** [comment] 2020-06-23 08:04
Hi @wobba ,

thanks for your help!!
May i know what has been change which cause this issue. Is there any change from MS which impacted ?

**Comment by wobba** [comment] 2020-06-23 11:46
Not sure if a change was made or not, outside of that we got an object and not a string. Seems `tryGetValue` on `DynamicProperty<TValue>` might have changed and as such maybe an issue should be logged at sp-dev-docs.

**Comment by spo365** [comment] 2020-07-07 14:22
i am using version 3.10 and made the changes for object and string check in search result and search webpart code it was working fine. Today it started giving below error.
 when i type any keyword in search box it always pass "*"  in search result page.
while debugging getting undefined error below.
let queryDataSourceValue = this.properties.queryKeywords.tryGetValue();

**Comment by wobba** [comment] 2020-07-07 15:09
@spo365 which means `this.properties.queryKeywords` could be undefined. Does it work in the hosted workbench?

**Comment by spo365** [comment] 2020-07-07 15:47
No it is not working on hosted workbench. What ever keyword we type in search box it always bring all records.

**Comment by wobba** [comment] 2020-07-07 16:52
That's not what I asked...if you debug and set a breakpoint at the line, does it give data back?

**Comment by spo365** [comment] 2020-07-07 16:59
Yes we debug the solution and it does not give any data.

**Comment by wobba** [comment] 2020-07-07 17:02
Is the dynamic data connection persisted when you save and re-edit the page/webpart?

**Comment by spo365** [comment] 2020-07-07 17:13
Yes it persist, till today morning everything was working no changes has been deployed. 
Suddenly it stoped which impacted all my users.
Now I am losing  confidence with  PNP search web part due to so many uncertainty.

**Comment by FranckyC** [comment] 2020-07-07 17:59
@spo365 Sorry about this situation but this issue was introduced by Microsoft changing the dynamic data behavior unexpectedly.

**Comment by FranckyC** [comment] 2020-07-07 18:21
@spo365 can you try this https://github.com/microsoft-search/pnp-modern-search/issues/299#issuecomment-655039850

**Comment by spo365** [comment] 2020-07-08 00:24
no change same issue. it bring all record seem like search result web part is not able read keyword from search box.
