### ISSUE TITLE
Person hover card in combination with Personal mail webpart

### ISSUE THREAD

**Issue by SPLeon** [microsoft-search/pnp-modern-search#2387] opened 2022-09-26 13:21 UTC
Hi,

**Version used**
4.7

**Describe the bug**
I found an issue with PnP search in combination with some webparts of PnP starter kit.
I've added the search result webpart to a page and we display people results with hover card (builtin).
When navigating to another page where Personal Meetings/Personal Agenda webpart is added, this webpart is not working (unexpected error).
Also when navigating to the search result page after I have visited a page with other PnP webparts, the result webpart is not working.
Also search input is not working. Think this is related to the use of Graph Api.

**To Reproduce**
1. Go to page where PnP Personal Meetings/ PnP Personal Agenda webpart are added 
2. Go to page where PnP Search webpart is added with Person card and Person hover card (works without hover card)
3. Search for a person
4. No results are being display / no search query is executed (url doesn't change)
5. Refresh page, webpart is working as expected

**Expected behavior**
Search is working as expected

**Desktop (please complete the following information):**
 - Browser Edge Chromium

**Additional context**
Other way around, when you first navigate to Search page and execute query and then navigate to other page were PnP personal webparts are added, the webpart don't work. (Personal mail does work). Error in webparts:

[SPLoaderError.loadComponentError]:
Failed to load component "6d28e73b-ed80-494e-8238-c0106c26b36a" (PersonalCalendarWebPart). Original error: Failed to load component dependency "6d28e73b-ed80-494e-8238-c0106c26b36a" from component "PersonalCalendarWebPart" (Failed to load component "78b11c7d-7ca8-47cb-a93c-d3beabb519a1" (MgtSpfxLibrary). Original error: Failed to load entry point from component "78b11c7d-7ca8-47cb-a93c-d3beabb519a1" (MgtSpfxLibrary). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-mock-provider" has already been used with this registry). Original error: {3}

INNERERROR:
Failed to load component dependency "6d28e73b-ed80-494e-8238-c0106c26b36a" from component "PersonalCalendarWebPart" (Failed to load component "78b11c7d-7ca8-47cb-a93c-d3beabb519a1" (MgtSpfxLibrary). Original error: Failed to load entry point from component "78b11c7d-7ca8-47cb-a93c-d3beabb519a1" (MgtSpfxLibrary). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-mock-provider" has already been used with this registry). Original error: {3}
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nl-nl_168dc8aa602dd549589131872131aef8.js:70:215909)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nl-nl_168dc8aa602dd549589131872131aef8.js:70:793796)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nl-nl_168dc8aa602dd549589131872131aef8.js:70:831105)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nl-nl_168dc8aa602dd549589131872131aef8.js:70:827196)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_nl-nl_ffad6cdffea73800d2a1.js:1:6036

**Comment by wobba** [comment] 2022-09-26 14:16
Can you please update the issue to use the bug template and provide more details on what errors in the console, how to set up repro etc. If not I'll close this one. And the issue could very well be the Starter Kit web parts, not these 😉

**Comment by SPLeon** [comment] 2022-09-26 14:34
I updated the post.

**Comment by wobba** [comment] 2022-09-26 15:37
Seems to be the issue is the starter kit web parts, as they are the ones failing. I see search web part use mgt v2.3.0 while starterkit uses v2.2.1. So this could also be a culprit. PnP Modern search also checks if `Providers.globalProvider` is already set before using it, something toolkit does not.

This is an issue when two projects use different versions of the same dependency - and the dependency is global in the DOM.

**Comment by SPLeon** [comment] 2022-09-26 17:20
Sorry, but i'm not a developer. What can I do at my end to make this work? Thanks for the assistance.

**Comment by wobba** [comment] 2022-09-26 19:03
Short answer, log an issue with the starterkit project so they can fix the implementation and release a new version. If this does not help, let me know and I'll reach out to some of the contributors.

**Comment by SPLeon** [comment] 2022-10-24 08:01
I raised an issue at SPStarterkit. Bit late, but was working on another project.

**Comment by wobba** [comment] 2022-10-24 17:01
I'll close this one, and I have changed the mgt reference as well with #2480

**Closed by wobba** 2022-10-24 17:01 UTC
