### ISSUE TITLE
Pnp Search 4.10.2 - Error webParts on smartphone/mobile use

### ISSUE THREAD

**Issue by DavidD410** [microsoft-search/pnp-modern-search#3541] opened 2024-02-16 13:33 UTC
Hi,

**Version**
4.10.2

**Describe the bug**
PnP Search Results web parts are not loading on mobile devices, for internal users. 
The web parts are loading fine on computer devices. Error reproduced on both, Chrome and Safari browsers.
Pnp Search is deployed on tenant app catalog

**To Reproduce**
From a mobile device navigate to SharePoint page with pre-configured PnP search web parts
Login using a company account
Scroll down to the search results area
You're presented with 'something went wrong' messages

**Expected behavior**
The page with PnP web parts loads.

**Screenshots**
![image (1)](https://github.com/microsoft-search/pnp-modern-search/assets/160244835/8ffe68f1-b0b8-4450-9ed2-d395269b32db)

**Comment by kasperbolarsen** [comment] 2024-02-16 13:36
please see https://github.com/microsoft-search/pnp-modern-search/issues/3505
Can you test and verify that MGT might be the real issue?

**Comment by DavidD410** [comment] 2024-02-16 13:38
> please see #3505 Can you test and verify that MGT might be the real issue?

MGT ?

**Comment by kasperbolarsen** [comment] 2024-02-16 13:39
Microsoft Graph Toolkit

**Comment by DavidD410** [comment] 2024-02-16 13:46
> please see #3505 Can you test and verify that MGT might be the real issue?


The problem also appears on a page with just the search box as a web part

**Comment by wobba** [comment] 2024-02-19 15:12
Duplicate of #3505

**Closed by wobba** 2024-02-19 15:12 UTC
