### ISSUE TITLE
pnP Modern Search - Search Extensibility Library (Sorry, something went wrong with adding the app)

### ISSUE THREAD

**Issue by aalejoramirezz** [microsoft-search/pnp-modern-search#739] opened 2021-02-03 19:49 UTC
![image](https://user-images.githubusercontent.com/44932668/106800829-f6cb9d00-662e-11eb-9d96-26b779ee06b3.png)
Hi there,

Do you know why I am getting this error?

Many thanks

**Comment by wobba** [comment] 2021-02-03 20:24
Duplicate of https://github.com/microsoft-search/pnp-modern-search/issues/707#issuecomment-768410216

**Closed by wobba** 2021-02-03 20:24 UTC
