### ISSUE TITLE
Date is not showing correct some times on page

### ISSUE THREAD

**Issue by Priy16** [microsoft-search/pnp-modern-search#1548] opened 2021-11-22 07:19 UTC
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/1539

Hi Team,

We need support on my issue, we don't get any support on this. Please help us.

We already raised with  Microsoft support team. Microsoft suggested that its PnP search issue and this will help by GitHub team.

Reference already attached screen shot.

Request to help us.

Awaiting for your valuable response.

Hi Team,

We have a page that have some columns and that column data coming from a list that is a PnP web part(version 3).
There is a 'UP To' Single line text column on page, that showing date from managed metadata column of the list.

UP To column showing some incorrect date (month and year) of some records. After refreshing the page or sorting the column some time it showing correct and some time same record showing incorrect date. 

Issue with random records not with particular records. And same records automatically corrected after refreshing the page or sorting the records. 

For more reference attaching some files.
some times showing incorrect after ![UptoColumnIssue](https://user-images.githubusercontent.com/94505069/142134293-ce1a9542-f785-4d0a-8792-e24d694d243c.jpg)the page of any record.

![UptoColumnIssueCorrectOne](https://user-images.githubusercontent.com/94505069/142134365-c238d13e-6330-48ed-8da3-039fb3b23de2.jpg)</div>

**Comment by wobba** [comment] 2021-11-22 13:10
Closing as duplicate of #1539

**Closed by wobba** 2021-11-22 13:10 UTC

**Comment by Priy16** [comment] 2021-11-30 07:40
Hi Mikael,

My issue is with PnP Search Web part.

We have a page Publications.aspx, where data is displayed/searched with PnP search Web Part.
We have created and used Managed properties which are mapped with Crawl Properties.
For reference, attaching screen shot of web part in edit mode.

 
![image](https://user-images.githubusercontent.com/94505069/144005320-740ac786-b34a-4e4b-a3b0-0a66ad5e07a4.png)


We are displaying data from search database, where data is crawled from SharePoint library(Original Data).This PnP web part sometimes shows wrong value in “UP TO” Column while searching(Intermittent Issue).



Please find the below steps to triage the issue
1.	Login at Info Hub SharePoint Communication site and then Navigated to Publication.aspx, where we have used PnP Search Web Part to display the Publication records.
2.	By Default N numbers of records populated as shown in below figure.

![image](https://user-images.githubusercontent.com/94505069/144005395-f7a65ffe-e423-40f5-a44b-f4b91123b12a.png)

 

3.	When we refresh the page for multiple times or when we use paging or sorting multiple times, the “UP TO” column displays wrong data for few records.

![image](https://user-images.githubusercontent.com/94505069/144005466-96bd7015-6d3f-4884-a32c-ef629a622a53.png)

  
From the above screen shot, we can see that in place of showing “12-8900”, it is showing “01-4501”.

4.	Then, we checked the data in SharePoint library and found out that the “UP TO” column is storing the right value “12-8900”.
5.	We thought that data might have not crawled from SharePoint Library, so we re-indexed the library. Even after re-indexing, the issue didn’t get resolved.
6.	Then we raised a case with Microsoft. We had two troubleshooting sessions with Microsoft Engineers. He collected the network logs and found out that data coming out from search engine is correct from backend. He confirmed that the issue is from the web part side while rendering the contents.
7.	He suggested logging a ticket with GitHub Support.

Kindly let us know if you need anything else from our side, we are also happy to have call with you. 
I shall be obliged if you do the needful.

Regards,
Priy Ranjan

 





[PublicationIssu.docx](https://github.com/microsoft-search/pnp-modern-search/files/7623787/PublicationIssu.docx)

**Comment by wobba** [comment] 2021-12-03 09:43
Without having an exact repro with the template and setup used it's difficult to figure out where data might be bound wrongly. Also, your submission is incomplete with no mention on web part version etc. And use the other discussion which is not closed.
