### ISSUE TITLE
v4 Add user selectable result set sorting

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#703] opened 2021-01-25 15:11 UTC
**Is your feature request related to a problem? Please describe.**
There is no mechanism for users to sort the result set in v4.0 as there was in the v3.15.3 search result web part.   Title click sorting on a page is not adequate when you're interested in sorting the entire result set.  Result set sorting is a tier-one capability.

**Describe the solution you'd like**
Implement the v3.15.3 result set sorting capability in the v4.0 search result web part (or maybe put it in a different web part, kind of like filters).

**Comment by FranckyC** [comment] 2021-01-29 01:48
Duplicate of #597.

**Closed by FranckyC** 2021-01-29 01:48 UTC
Labels: enhancement
