### ISSUE TITLE
Result counts in v4 search verticals web part

### ISSUE THREAD

**Issue by codyrhowe** [microsoft-search/pnp-modern-search#825] opened 2021-03-02 15:17 UTC
Version 3.x of the Search Verticals web part had result counts for each vertical, would like to see the same functionality in v4, this is something our users have been used to having available.

**Comment by FranckyC** [comment] 2021-03-09 01:47
Hi @codyrhowe, thank you for your feedback! Because verticals between v3 and v4 are very different in their implementations this is unfortunately not so easy to reproduce. Anyway, I'll add it for a future release. Thanks!

**Comment by bryllyg** [comment] 2021-05-07 15:48
I'll second the request :-)

**Comment by PranavR7** [comment] 2021-06-25 00:17
I reckon we really need this feature as most users of Search v3 found this feature to be extremely useful. It will be a nice addition if search v4 could have it too.

**Comment by bryllyg** [comment] 2021-06-28 19:18
Agreed!

**Comment by edarroudi** [comment] 2021-12-08 10:56
just saw this.. anyways i don't know how far @FranckyC  is with that.. So here is my approach https://github.com/microsoft-search/pnp-modern-search/pull/1608

**Comment by wobba** [comment] 2023-05-27 13:26
Closing, also as counts are not reliable these days imo.

**Closed by wobba** 2023-05-27 13:26 UTC
Labels: enhancement, v4
