### ISSUE TITLE
V4 Query Template: {Hub.HubSiteId} becomes undefined when using along with {Page} level token

### ISSUE THREAD

**Issue by Tin-Bui** [microsoft-search/pnp-modern-search#654] opened 2021-01-11 21:54 UTC
**Version used**
4.0.0-preview

**Describe the bug**
In query template , the {Hub.HubSiteId} token resolve to the current hub site ID correctly. However, as soon as I use it in conjunction with a Page level token , such as {Page.Id}, the {Hub.HubSiteId} become "undefined", as showed in the debug template's queryModification node.

**To Reproduce**
1. Add a PnPSearch web part to the page
2. Update layout to "Debug"
2. Fill query template with "{Hub.HubSiteId}"
3. Observe the "{Hub.HubSiteId}" resolve correctly in the queryModification node of the debug display
4. In the query template, append "{SiteCollection.Id}"
5. Observe both of the token still resolve correctly in the debugging output
6. In the query template, append additional token "{Page.Id}"
7. Observe "{Hub.HubSiteId}" is now undefined in the debugging output, while the other 2 tokens are still resolving correctly.

**Expected behavior**
{Hub.HubSiteId} in query template resolve correctly no matter which other tokens are being used in conjunction with it.

**Screenshots**
![HubSiteId OK](https://user-images.githubusercontent.com/33175306/104242716-ab9cef00-54b3-11eb-9bf3-da19e3886fd7.JPG)
![HubSiteId Still OK With Site Level Token](https://user-images.githubusercontent.com/33175306/104242733-b192d000-54b3-11eb-87e5-e26b36ebf6cb.JPG)
![HubSiteId NOT OK With Page Level Token](https://user-images.githubusercontent.com/33175306/104242743-b5beed80-54b3-11eb-8da7-f75284ecbe03.JPG)

**Desktop (please complete the following information):**
 - Chrome 86.0.4240.111

**Additional context**
N/A

**Comment by FranckyC** [comment] 2021-01-15 13:29
Hi @Tin-Bui , I'm able to reproduce the issue and found the cause. Good catch actually, not easy to fnd ;). I will work on a fix, thank you!

**Comment by FranckyC** [comment] 2021-01-15 15:51
Should be resolved in the v4 branch.

**Closed** 2021-01-15 15:52 UTC
