### ISSUE TITLE
Results web part drops connection to search box

### ISSUE THREAD

**Issue by paylord** [microsoft-search/pnp-modern-search#426] opened 2020-08-13 04:57 UTC
**Version used**
3.14.2.0

**Describe the bug**
The Results web part allows me to connect to the Search Box web part but then drops the connection as soon as I move to the next settings page or close the settings dialog.

**To Reproduce**
1. Open modern comms site home page
2. Clear all existing sections
3. Add Search Box web part - default settings
4. Add Search Results web part
5. Connect Results to Search Box (note that the 'Use a default search query' checkbox is missing)
![image](https://user-images.githubusercontent.com/8131698/90095556-56c64280-dd74-11ea-8662-2cc562018cc8.png)
6. Click next to go to next page of settings (or close and reopen settings) and the connection to the search box has been dropped
![image](https://user-images.githubusercontent.com/8131698/90095667-b58bbc00-dd74-11ea-9228-a7ca6373d9ed.png)

**Expected behavior**
I have tried refreshing the page, saving and editing again, adding a value in the text box etc.  Eventually, the first page of settings shows the check box and then it seems to work as expected:
![image](https://user-images.githubusercontent.com/8131698/90095804-13200880-dd75-11ea-8d3e-f3199d94a4ad.png)

**Screenshots**

**Desktop (please complete the following information):**
 - Browser - Chrome
 - Windows 10

**Additional context**

**Comment by wobba** [comment] 2020-08-13 05:57
Duplicate of #299

**Closed by wobba** 2020-08-13 05:57 UTC

**Comment by paylord** [comment] 2020-08-13 07:09
Bah sorry - I did search and browse current issues but obviously not well enough!  A man-look as my wife would say.
