### ISSUE TITLE
Results web part not showing all results when paged through

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#1208] opened 2021-08-12 19:54 UTC
**Version used**
v: 3.14.2

**Describe the bug**
Query includes 3 lists with a total of 9750 results. Web part set to 20 results per page  in new to old order with paging on. When I get to page 26 (ie 520 items),  the results page is empty and there's no paging element to go forwards or back.
If I search for an item I know is at the start of the list it does get returned.
When I test the query in the query builder, it shows 9750 results.

**To Reproduce**
1. Add results web part 
2. Set query to include multiple lists 
3. Set default search to"*"....'

**Expected behavior**
Should be able to page through all results

**Desktop (please complete the following information):**
Chrome

**Comment by bryllyg** [comment] 2021-08-13 23:10
Hi @webbrewer, 

I'm running v3.21.0. I just set up a test  querying three lists with a total of 29348 items. I have it set to 25/page, and I get back 1174 pages = 29350 -2 (last page only shows 23 results).  You didn't post your query, so I can't see if you specified OR between your lists in the query.  The default is AND, so that would produce less results.  Alternately, I am running a later version.

**Comment by wobba** [comment] 2021-08-14 08:19
Also remember that the total count is not necessarily correct but an estimation.

**Comment by webbrewer** [comment] 2021-08-14 16:56
Yes, I used OR:
`(Path: https://xxxx.sharepoint.com/sites/Exxxx/Lists/xxxx  OR Path:  https://xxxx.sharepoint.com/sites/Exxxx/Lists/xxxxx OR Path:https://xxxx.sharepoint.com/sites/Exxxx/Lists/xx) Title:{searchTerms}`
As I said "If I search for an item I know is at the start of the list it does get returned", so I know all the results are getting returned - I just can't page past page 26. There should be about 488 pages.

**Comment by wobba** [comment] 2021-08-16 09:47
Are the spaces in your sample query what you have in the web part? There should be not spaces between property, operator and value.
`prop:value` works, `prop: value` does not.

**Comment by webbrewer** [comment] 2021-08-16 14:30
No spaces in the web part query.

**Comment by webbrewer** [comment] 2021-08-16 16:45
Retested in VERSION  4.0.0.0, same issue. It only displays 510 items out of 9750+

**Comment by wobba** [comment] 2021-08-19 11:20
The issue is 99.9% with your setup. Feel free to export the web part settings and share so we can look at it.

**Comment by webbrewer** [comment] 2021-08-19 14:56
Happy to - but how do I export the web part settings?

**Comment by wobba** [comment] 2021-08-23 17:04
@webbrewer Last web part settings pane. 

![image](https://user-images.githubusercontent.com/51104/130487715-e659ccb4-8aa6-49b9-97f2-9f9bae3ee84c.png)

Click 'Edit Properties', then export. Should be there in each web part.

**Comment by webbrewer** [comment] 2021-08-23 18:25
@wobba No option like that in the web parts here....3rd page of properties pane:
![untitled](https://user-images.githubusercontent.com/51796756/130497744-9dee3012-0075-464f-bbb5-66c6a29f2edd.png)

**Comment by wobba** [comment] 2021-08-29 12:10
Ah, you're on an older version. Then you should upgrade and verify if paging is still an issue.

**Comment by webbrewer** [comment] 2021-09-02 14:32
As I said above, same issue with version 4.

**Comment by wobba** [comment] 2021-09-02 17:22
@webbrewer Newer versions of v3 and v4 have export web part property settings. The dot release says something if you are on a newer version. v4 is not newer than v3 in terms of bugs. 

And, I cannot repro the paging issue you mention so hard to troubleshoot. If you have a newer v3 or v4 there is an option to export the web part settings so you could share your exact setup which may or may not help with repro.

**Comment by webbrewer** [comment] 2021-09-02 19:07
I updated to v4.3. Same issue so I attached wp props file. @wobba [
[v4-3-webpartproperties.txt](https://github.com/microsoft-search/pnp-modern-search/files/7101161/v4-3-webpartproperties.txt)
](url)

**Comment by wobba** [comment] 2021-09-06 17:33
I cannot repro. Can you try this:

* Navigate to the classic search center https://xxx.sharepoint.com/search
* Run your query `(Path:https://xxx.sharepoint.com/sites/Employee-Recognition/Lists/VWTGfeb2020import  OR Path:https://xxx.sharepoint.com/sites/Employee-Recognition/Lists/vwtg2 OR Path:https://xxx.sharepoint.com/Lists/VWTG%20Archive%20to%202019)`
* Can you then page all results?

**Comment by webbrewer** [comment] 2021-09-10 17:42
@wobba More results but still not all items.
Total items in 3 lists: 9856 
Classic search results total: shows "about 7771 items" but then it stops at page 543 - 5439 items.
Modern results count: 9870 but stops at page 52 - 520 items.

**Comment by wobba** [comment] 2021-09-12 14:02
Closing this as it's an API issue and we cannot control in the web parts how accurate paging is as you page along. Expecting anyone to page past page 3-4 is highly unlikely.

**Closed by wobba** 2021-09-12 14:02 UTC
Labels: Needs: Triage, v3
