### ISSUE TITLE
PnP Search Filters v4 - 0 Results when filtering on multiple filter fields for external data source results

### ISSUE THREAD

**Issue by PinnuDivya** [microsoft-search/pnp-modern-search#3934] opened 2024-08-23 11:57 UTC
**Version used**
 4.12.2.0

**Describe the bug**
I have created external data source connector to pull data from cosmos DB in M365 search admin center.
I am using microsoft search option as datasource and external Items as entity type. 
![image](https://github.com/user-attachments/assets/9b2301e5-3c18-4bb7-9577-22339897bc0c)

I am able to see the results in results webpart. Please see below for debug code.
![image](https://github.com/user-attachments/assets/7e1beb06-3f93-4724-9027-890c5fbec565)

I have also configured filters having 3 filter types. I have selected OR between the filters.
![image](https://github.com/user-attachments/assets/08b3a296-85e9-4f09-80bf-eaed36bc7db6).

The issue I am facing is when I select any 1 filter, I am able to see the results. But I see zero results when I select 2 or 3 filters.
Below image refers when one filter is been selected. When this filter is selected, past 24 hours in Modified Date filter is having 16 count.
![image](https://github.com/user-attachments/assets/d10033b8-191c-4281-b851-959f2f4e4a03)

When I select past 24 hours in Modified Date filter, results is showing as 0 instead of 16.
![image](https://github.com/user-attachments/assets/a1bf5b88-62cc-46ee-9626-59e1dd35cd2d)

And below is the query I am seeing when I have selected 2 filters.
f=[{"filterName":"filetype","values":[{"name":"docx","value":"\"ǂǂ6543218\"","operator":0,"disabled":false}],"operator":"or"},{"filterName":"lastModifiedTime","values":[{"name":"Past 24 hours","value":"2024-08-23T11:50:06.315Z","operator":5},{"name":"Past 24 hours","value":"2024-08-22T11:50:06.315Z","operator":4}],"operator":"or"}]#

**To Reproduce**
Steps to reproduce:
1. Create external data source connector in M365 search admin center
2. Configure PnP search results for external data entity type and configure filters on any sharepoint page.
3. Select 2 or more filters.

**Expected behavior**
User should see the results in results webpart.

**Desktop (please complete the following information):**
 - Browser : Tested in Edge

**Additional context**
I have implemented same with out PnP and filters worked as expected
<img width="513" alt="image" src="https://github.com/user-attachments/assets/84daae85-0e41-4d7b-8bc8-a68dbb897119">

It would be very helpful if any one could help me here.

**Comment by PinnuDivya** [comment] 2024-08-27 11:32
@wobba We are configuring this pnp search webpart for one of our client and this is very high priority for us. Could you please give confirmation on this ASAP.

**Comment by Prash-Ever** [comment] 2024-08-28 14:27
@wobba We are encountering similar issues with multiple filters malfunctioning when integrating various data sources, such as external (azure SQL or custom m365 connector), drives, list items, messages etc. This is proving to be a blocker, and we are in urgent need of a quick workaround or resolution.

**Comment by kasperbolarsen** [comment] 2024-08-28 19:16
I can confirm that multiple filter values don't work when dealing with External data. @Prash-Ever  we welcome a PR from you. Please note that PnP Modern Search is an Open Source project and not associated with MS and our SLA is "when somebody will use their sparetime to improve the project"

![image](https://github.com/user-attachments/assets/1d1ac02b-e098-410c-920a-a17c766dc420)

**Comment by kasperbolarsen** [comment] 2024-09-12 12:05
as this seems to be an API issue, I have contacted the product team in Microsoft and awaits a response

**Comment by wobba** [comment] 2024-09-23 14:12
Plan is to rewrite how we do Graph queries to make this work.

**Comment by tmelnychenko** [comment] 2024-09-24 10:59
@wobba we had the same issue but with the federated search (default Microsoft connector to Dynamics 365). It would be great if the fix for this issue can be added to the plan 👍

**Comment by abates100** [comment] 2024-10-17 20:54
I can confirm the same occurs in version Version: 4.13.1.0

**Comment by kasperbolarsen** [comment] 2024-10-18 06:40
> @wobba we had the same issue but with the federated search (default Microsoft connector to Dynamics 365). It would be great if the fix for this issue can be added to the plan 👍

Does this request have anything to do with PnP Modern Search? If we are able, via Graph Connectors, to query data from Dyn365 I would VERY much like to know more

**Comment by wobba** [comment] 2024-11-12 21:22
Fixed in the latest release.

**Closed by wobba** 2024-11-12 21:22 UTC
Labels: bug, enhancement, Needs: Triage
