### ISSUE TITLE
Edit Results Types not saving if inline template is used

### ISSUE THREAD

**Issue by shuenSL** [microsoft-search/pnp-modern-search#695] opened 2021-01-22 21:50 UTC
**Version used**
4.0.0.0

**Describe the bug**
Edit Result Types not saving unless external template is used

**To Reproduce**
1. Edit Search Results web part
2. Click Edit Result Types on page 2
3. Select a data source field and operator.
4. Enter a condition value
5. Click Save
6. Click to edit the Result Types again

**Expected behavior**
Should show previously entered data source, operator and condition value.

**Desktop (please complete the following information):**
 - Browser [Chromium]

**Additional context**

**Comment by wobba** [comment] 2021-01-26 19:37
Duplicate of #690

**Closed by wobba** 2021-01-26 19:37 UTC
