### ISSUE TITLE
specific keyword search gives error

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#463] opened 2020-09-09 19:56 UTC
**Describe the bug**

Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

when i search for energy i get this error. but this searches are successxful[*Energy,"energy",energy*]

Am i hitting a limit? is this a bug? 
![modernsearchErr](https://user-images.githubusercontent.com/25770942/92646837-a1bc7280-f2ac-11ea-8be0-59bb8a42e1e4.PNG)

**Comment by cpluceDev** [comment] 2020-09-09 20:10
those energy keyword searches that were successful I had a wildcard symbol in front and at the end. it was removed after my post was made. energy by itself does not work, it gives me the error

**Comment by cpluceDev** [comment] 2020-09-09 21:05
interesting enough. this error only happens on the search results page where the vertical is connected on a single page. however, when I test this search with my other setup where search vertical is using links or multiple pages to narrow the scope, I do not get the error. unfortunately, I have another issue with the multiple page setup when the search box is blank it gives me undefined in the url fragment and o results. seems I cant get 100% working solution. :(

**Comment by wobba** [comment] 2020-09-10 13:32
If you can share exact setup we can try to repro.

**Comment by cpluceDev** [comment] 2020-09-10 15:43
i am using 3.14.20 version.  i also have another issue submitted on a different issue. which is related to using multiple pages for search vertical compared to a single page in the configuration for search verticals.  Each has it s own issue. This one works except that one search keyword gives an error. im guessing its passing alot of results. when i use asterisk in front or end of energy or use quotations it works without the error. jsut a little more insight. also i dont get this error when using the multiple page configurations for verticals thx again

**Comment by wobba** [comment] 2020-09-11 12:00
I'd appreciate you checking with the latest release as there was some fixes on URL triggering.

**Comment by cpluceDev** [comment] 2020-09-11 20:00
what would be the best way to get the latest version? how / can i update my current project that is on my C drive? i tried to download the latest zip and running npm install, gulp bundle and gulp package-solution but im getting errors with this new package. i can bundle successfully but not package it.

Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (C:\Users\11111\spfx\pnp-modern-search-main\search-parts\node_modules\@microsoft\sp-build-core-tasks\lib\packageSolution\packageSolution\createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (C:\Users\11111\spfx\pnp-modern-search-main\search-parts\node_modules\@microsoft\sp-build-core-tasks\lib\packageSolution\PackageSolutionTask.js:135:36)
    at DestroyableTransform.prefinish (C:\Users\11111\spfx\pnp-modern-search-main\search-parts\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:198:13)
    at prefinish (C:\Users\11111\spfx\pnp-modern-search-main\search-parts\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\Users\11111\spfx\pnp-modern-search-main\search-parts\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\Users\11111\spfx\pnp-modern-search-main\search-parts\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (C:\Users\11111\spfx\pnp-modern-search-main\search-parts\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DestroyableTransform.onend (C:\Users\11111\spfx\pnp-modern-search-main\search-parts\node_modules\gulp\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)

**Comment by MakingThingsWorkToronto** [comment] 2020-09-11 20:22
The above would typically happen when you haven't done the "gulp bundle --ship" before the "gulp package-solution --ship" ...

To debug, install/deploy the package in the app catalog (you can package yourself or deploy the latest release).

Pull the latest code from the main branch, then run: "gulp serve" in terminal.

Navigate to your test page and append the following query string parameters: ?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js

That will load debug scripts from local host! Happy debugging!

**Comment by cpluceDev** [comment] 2020-09-11 20:29
thanks. i figured out the error. and deployed it but i still get the 500 error above. yep. i would like to streamline this update process so i dont have to do 10 steps every time when updating the app. so i would do a pull to my directory. search-main

**Comment by cpluceDev** [comment] 2020-09-11 20:44
updated to latest version. i get the 500 error when searching on energy and test for  keywords but works on many other keywords.  strange how the error only happens on this 2 keywords and thast it. and if i put the keyword in quotes or use an asterisk with it it also works. just doesnt work by itself

**Comment by MakingThingsWorkToronto** [comment] 2020-09-11 20:58
Are you able to reproduce this error in the [Search Query Tool](https://github.com/pnp/PnP-Tools/tree/master/Solutions/SharePoint.Search.QueryTool)?

**Comment by cpluceDev** [comment] 2020-09-11 23:34
no i cannot reproduce the error with the tool.  i only get the error when i search the one list using the search vertical and its KQL and result source. but when i use other search methods such as url fragment or url query or OOTB search. it works.

**Comment by cpluceDev** [comment] 2020-09-12 14:48
as stated above this only gives me an error when using search verticals on a single page. when i use open in new page and use several links and pass the searchterm in the url fragment it works. of course, this method has another bug where when you navigate from each vertical tab and there isnt a keyword in teh search box you get an undefined and no results and you need to refresh page to clear that. i had found this but not sure it is related but it is similar

https://github.com/SharePoint/sp-dev-docs/issues/2935

**Comment by cpluceDev** [comment] 2020-09-14 14:19
i have looked at filddler for this but not sure i see anything in there.  anything that i can look at fiddler that maybe able to help with this error? I can see where the query caused the error and i have one where it succeeds.

**Comment by wobba** [comment] 2020-09-14 14:34
@cpluceDev If you could paste the request JSON of the search REST call that would help.

**Comment by cpluceDev** [comment] 2020-09-14 14:51
{"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

**Comment by cpluceDev** [comment] 2020-09-14 15:01
`{
    "request": {
        "__metadata": {
            "type": "Microsoft.Office.Server.Search.REST.SearchRequest"
        },
        "ClientType": "PnPModernSearch",
        "Properties": {
            "results": [
                {
                    "Name": "EnableDynamicGroups",
                    "Value": {
                        "BoolVal": true,
                        "QueryPropertyValueTypeIndex": 3
                    }
                },
                {
                    "Name": "EnableMultiGeoSearch",
                    "Value": {
                        "BoolVal": true,
                        "QueryPropertyValueTypeIndex": 3
                    }
                }
            ]
        },
        "Querytext": "energy",
        "TimeZoneId": 10,
        "EnableQueryRules": true,
        "SourceId": "111",
        "EnableNicknames": false,
        "EnablePhonetic": false,
        "QueryTemplate": "{searchTerms} path: https://site.sharepoint.com/sites/root/subsite/Lists/List1 -path:https://site.sharepoint.com/sites/root/subsite/Lists/List1/AllItems.aspx path:https://site.sharepoint.com/sites/sitedev/subsite/Lists/List2/  -path:https://site.sharepoint.com/sites/sitedev/subsite/Lists/List2/AllItems.aspx",
        "RowLimit": 10,
        "SelectProperties": {
            "results": [
                "Title",
                "Path",
                "Created",
                "Filename",
                "SiteLogo",
                "PreviewUrl",
                "PictureThumbnailURL",
                "ServerRedirectedPreviewURL",
                "ServerRedirectedURL",
                "HitHighlightedSummary",
                "FileType",
                "contentclass",
                "ServerRedirectedEmbedURL",
                "DefaultEncodingURL",
                "owstaxidmetadataalltagsinfo",
                "ContentType",
                "devContractNumber",
                "Services2",
                "Subsector",
                "OriginalPath",
                "FileExtension",
                "IsDocument",
                "IsContainer",
                "IsListItem",
                "HtmlFileType",
                "NormSiteID",
                "NormWebID",
                "NormListID",
                "NormUniqueID",
                "ParentLink",
                "Author",
                "AuthorOWSUSER",
                "SPSiteUrl",
                "SiteTitle",
                "SiteId",
                "WebId",
                "UniqueID",
                "subsiteSkills",
                "subsiteCertifications",
                "subsiteServices",
                "",
                "subsiteSubsector",
                "subsiteProjectDescriptions",
                "subsiteProjectNumber",
                "subsiteEmployeeId",
                "CreatedDateOWSDATE",
                "CreatedOWSDATE",
                "CreatedBy",
                "ModifiedOWSDATE",
                "ModifiedBy"
            ]
        },
        "TrimDuplicates": false,
        "SortList": {
            "results": [
                {
                    "Property": "Created",
                    "Direction": 0
                },
                {
                    "Property": "Size",
                    "Direction": 1
                }
            ]
        },
        "Culture": 1033,
        "Refiners": "ContentType(sort=name/ascending),RefinableString194(sort=name/ascending),RefinableString195(sort=name/ascending),JobTItle(sort=name/ascending),RefinableString11(sort=name/ascending),RefinableString182(sort=name/ascending),refinablestring196(sort=frequency/descending),RefinableString189(sort=name/ascending),RefinableString190(sort=name/ascending),RefinableString184(sort=name/ascending),RefinableString34(sort=name/ascending),RefinableString03(sort=name/ascending),RefinableString124(sort=name/ascending),RefinableString88(sort=name/ascending),RefinableString193(sort=name/ascending),RefinableString192(sort=name/ascending),RefinableString198(sort=name/ascending),RefinableString197(sort=name/ascending),RefinableDate10(discretize=manual/2019-09-14T14:50:16.606Z/2020-06-14T14:50:16.606Z/2020-08-14T14:50:16.606Z/2020-09-07T14:50:16.606Z/2020-09-13T14:50:16.605Z),RefinableDate11(discretize=manual/2019-09-14T14:50:16.606Z/2020-06-14T14:50:16.606Z/2020-08-14T14:50:16.606Z/2020-09-07T14:50:16.606Z/2020-09-13T14:50:16.606Z)",
        "HitHighlightedProperties": {
            "results": []
        },
        "RefinementFilters": {
            "results": []
        },
        "ReorderingRules": {
            "results": `[]`
        }
    }
}`

**Comment by wobba** [comment] 2020-09-15 08:54
1. Seems to be a space in `path: https://`. Should be no space after `:`.
2. You have a result source id of `111`. This is not correct. Either leave blank or a correct GUID.

**Comment by cpluceDev** [comment] 2020-09-15 13:57
ah. ill take a look.  i also know it is working now when i changed my KQL to search new lists. maybe that was fixed when i copied and pasted the paths over

**Comment by cpluceDev** [comment] 2020-09-15 14:01
i do have a concern about the result source showing 111. i dont have that configured anywhere. ill keep an eye on this

**Comment by cpluceDev** [comment] 2020-09-15 14:07
i think i edited the id by accident before i posted for anonymous reasons

**Comment by wobba** [comment] 2020-09-15 16:55
Ok... it would help to know what the ID was, as the OOB sources have all the same guids. No PII in the guid :)

**Comment by cpluceDev** [comment] 2020-09-16 02:25
SourceId=8413cd39-2156-4e00-b54d-11efd9abdb89

i also noticed it works on two verticals out of 4 verticals. all verticals are using the same source id with different KQL b/c i couldn't get the multiple result source ID option to work which would have been ideal but it returns all results from across the tenant and i have these configured individually using the same KQL syntax im using in the veritcasl settings with a single source/result  id

**Comment by wobba** [comment] 2020-09-16 09:25
Thank you, that's the general local result id. Then I cannot really figure out why search breaks for one keyword only as the request looked ok to me.

**Comment by cpluceDev** [comment] 2020-09-16 14:41
i have narrowed down the search error to this one custom list that is populate by flow. when searching this term on that list i get the error. when i removed the path to this list from the query template it works.

**Comment by cpluceDev** [comment] 2020-09-16 14:45
i think it might be the column type for multiple line of text. need to change from enhanced to plain text. will test now

**Comment by wobba** [comment] 2020-09-16 18:14
I'll close this issue and you can potentially file a support ticket for this, as it seems to be a backend issue, not an issue with the web parts :)

**Comment by cpluceDev** [comment] 2020-09-16 18:35
but it works using the url fragment method and multiple pages linked in the vertical. just doesnt work when configured using a single page multiple query temaplates.

**Comment by cpluceDev** [comment] 2020-09-16 18:37
there is also no issue with OOTB search.  just the pnp search web parts gives the error

**Comment by cpluceDev** [comment] 2020-09-16 21:23
interesting. i copied the page and removed the connected refiners webpart. now the error is gone.

**Comment by cpluceDev** [comment] 2020-09-17 02:05
![image](https://user-images.githubusercontent.com/25770942/93411260-5bdd4c80-f860-11ea-9b0e-f6908f6a0fe4.png)

**Comment by cpluceDev** [comment] 2020-09-17 02:07
![image](https://user-images.githubusercontent.com/25770942/93411347-98a94380-f860-11ea-8092-a3490882a64a.png)

**Comment by cpluceDev** [comment] 2020-09-17 14:02
any ideas? thx

**Comment by wobba** [comment] 2020-09-17 15:03
Assuming the payload you pasted earlier gave an error. If you add this to the refinement in the SP query tool.. does it also break?

`ContentType(sort=name/ascending),RefinableString194(sort=name/ascending),RefinableString195(sort=name/ascending),JobTItle(sort=name/ascending),RefinableString11(sort=name/ascending),RefinableString182(sort=name/ascending),refinablestring196(sort=frequency/descending),RefinableString189(sort=name/ascending),RefinableString190(sort=name/ascending),RefinableString184(sort=name/ascending),RefinableString34(sort=name/ascending),RefinableString03(sort=name/ascending),RefinableString124(sort=name/ascending),RefinableString88(sort=name/ascending),RefinableString193(sort=name/ascending),RefinableString192(sort=name/ascending),RefinableString198(sort=name/ascending),RefinableString197(sort=name/ascending),RefinableDate10(discretize=manual/2019-09-14T14:50:16.606Z/2020-06-14T14:50:16.606Z/2020-08-14T14:50:16.606Z/2020-09-07T14:50:16.606Z/2020-09-13T14:50:16.605Z),RefinableDate11(discretize=manual/2019-09-14T14:50:16.606Z/2020-06-14T14:50:16.606Z/2020-08-14T14:50:16.606Z/2020-09-07T14:50:16.606Z/2020-09-13T14:50:16.606Z)`

and if you fix the managed property casings to be `RefinableString` for all and `JobTItle` seems to not match your schema most likely. And you should use `SPContentType` and not `ContentType`.

**Comment by cpluceDev** [comment] 2020-09-17 15:26
yep. i get the error with the search query tool

**Comment by cpluceDev** [comment] 2020-09-17 15:30
fails all the time now when i copied the above refinements into search query tool

**Comment by cpluceDev** [comment] 2020-09-17 15:59
im going to test this with OOTB classic search page and web parts. think this may be on MSFT end

**Comment by wobba** [comment] 2020-09-17 16:31
Can you try remove one and one refiner until it works to isolate the issue?

**Comment by cpluceDev** [comment] 2020-09-17 18:46
i did that. it doesnt matter what refiner i add back one by one, it errors.  only way to clear it, is to remove all refiners. it also works when i use classic  search web parts when i cloned the exact setup

**Comment by cpluceDev** [comment] 2020-09-18 01:57
i had pasted the refiners in the wrong text box earlier. it seems to work with the search query tool. i get 20 results.

![image](https://user-images.githubusercontent.com/25770942/93546471-70851780-f928-11ea-8917-19e7d0d8d9e3.png)

**Comment by wobba** [comment] 2020-09-18 06:42
@cpluceDev if you remove the () parts per refiner spec? But if the same part works using the query tool that is weird. Did you connect to the same site URL as you are testing the webpart at as well? And set the query tool to use POST and not GET.. just to get the requests as equal as possible. Are you in a multi-geo environment?

**Comment by cpluceDev** [comment] 2020-09-18 13:48
not sure what you mean by- if you remove the () parts per refiner spec?   i connected to same site and it is a post.  multi-geo is configured at our tenant.   it is not just the refiners web part that is breaking it. it is the one list when i search with that keyword that breaks it. when i search other lists using that keyword it is fine. so it seems to be something to do with that list and refiners or mapped properties) parsing that keyword. id also like to add this list is being populated by flow from a sql database. thanks for helping and quick replies. much appreciated

**Comment by wobba** [comment] 2020-09-19 07:52
If you read the refiner spec (what you entered into the refiners parameter) each part has a () section with additional info...remove them so you end up with:

Refiner1,Refiner2

etc. to see if it's the extra parts causing issues or not.

If it's multi-geo, remove the geo call and see if one geo causes the issue. Testing the call by connecting per geo. Or enable geo in the extra param field in the query tool as it's not multigeo my default.

See https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-search-for-multi-geo?view=o365-worldwide#sample-get-request-to-fan-out-to-some-geo-locations or info on querying per geo.

**Comment by cpluceDev** [comment] 2020-09-22 14:04
Using the search query tool did not produce the error.  I'm going to rebuild the list and test from a meeting list. Might be something with the list

**Comment by cpluceDev** [comment] 2020-09-22 19:40
i was able to resolve this. strange but when i copied the search results page. deleted the search results web part, added a new one. configured the new web part to use verticals and filters and it works now with all keywords

**Closed** 2020-09-23 12:00 UTC

**Comment by cpluceDev** [comment] 2020-09-30 14:58
just wanted to provide some more feedback. in case you may have some insight. good chance this was due to the fact the web part on this page was the old version of the PnP Modern Search Web Part and was upgraded to this PnP Modern Main web part. that could have something to do with it. so far all is still working and searching as expected. thx

**Comment by wobba** [comment] 2020-10-01 14:08
@cpluceDev Thank you for getting back on this. Do you know how old the other version was?

**Comment by cpluceDev** [comment] 2020-10-01 14:32
yep been using this since Jan 2019 and will need to upgrade eventually when this is tested fully. i had no issues with this version. seems this newer version has alot of functionality but has some bugs 

![image](https://user-images.githubusercontent.com/25770942/94823020-fa24f280-03c8-11eb-8fe1-a26acaac9eb9.png)
