### ISSUE TITLE
Filter: Combo Box "OR" combination is not working

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#1711] opened 2022-01-13 08:39 UTC
**Version used**
4.5.3

**Describe the bug**
The toggle to switch between AND and OR in the Filters is not working. Multiple values selected in one Filter combo box are always combined with "AND", ignoring the button to toggle between AND and OR

**To Reproduce**
have a filter webpart with combo box and a search result with multitple entries.
select multiple values from the combo box and choose the "OR" option
Apply the Filter

**Expected behavior**
multiple values from the filter should be combined with OR if option is selected

**Screenshots**
![image](https://user-images.githubusercontent.com/91128746/149295261-4679fcf3-9d26-4fd0-a4ec-af4a10a2a15b.png)

**Desktop (please complete the following information):**
edge chromium

**Additional context**

**Comment by ayblanchet** [comment] 2022-01-19 13:43
Same error with the same version.

**Comment by FranckyC** [comment] 2022-02-01 21:24
Hi @till-llit, I'm not able to reproduce this issue. Actually maybe the UI is misleading as you have to select first the operator and then click on the 'Apply' button to validate.

**Comment by till-llit** [comment] 2022-02-02 07:10
Hi @FranckyC , i still cannot change the "Operator between values" - even with the Apply button. For me it remains always with the default operatoir from the Filter Settings.

in my example i have "OR" selected as default "Operator between values" for the Column "File Type"

![image](https://user-images.githubusercontent.com/91128746/152109424-b23769cd-5eef-4835-a513-bf1d12db8c13.png)

Now i select 2 values from the filter, choose "AND" and press "Apply"

![image](https://user-images.githubusercontent.com/91128746/152109493-07254b7c-b6a4-457e-8130-70dbb2cbe3b8.png)

I still receive a result list filtered by a "OR" combination of both filters:

![image](https://user-images.githubusercontent.com/91128746/152109581-bd515d98-04b3-4acf-8a77-cdd1062e28b6.png)

**Comment by till-llit** [comment] 2022-02-02 14:35
still reproducable with 4.5.4

**Comment by FranckyC** [comment] 2022-02-02 15:49
I'm not able to reproduce this issue with 4.5.4 :/

![Untitled Project](https://user-images.githubusercontent.com/5659122/152188078-89901912-abcc-4762-8858-c10d4c76c540.gif)

**Comment by till-llit** [comment] 2022-02-03 06:45
thanks for the video, that helped! you need to choose "Custom" layout to reproduce the issue:

![image](https://user-images.githubusercontent.com/91128746/152294106-4247acf5-a316-491c-a940-b3242bb9b84f.png)

**Comment by FranckyC** [comment] 2022-02-10 02:02
Hi @till-llit, I was able to reproduce the issue and should be fixed by #1819. This will be available in the next release.

**Closed by FranckyC** 2022-02-10 02:02 UTC
Labels: Needs: Author Feedback, v4
