### ISSUE TITLE
when search from searchbox, pnp search results are not loading in IE.

### ISSUE THREAD

**Issue by sekharB487** [microsoft-search/pnp-modern-search#645] opened 2021-01-06 13:33 UTC
**Version used**
Ex: 3.15.3

**Describe the bug**
I am aware that team wont support on IE. But I am in need of a solution for our organization. So I am raising this for a solution.

I have Commented below line to support on IE.  It is working when I load script from local. 
// import 'core-js/modules/es.string.includes';
![image](https://user-images.githubusercontent.com/71835451/103772891-3b741080-5050-11eb-87a2-0f3e87cba9a1.png)
I deployed it and make it as default search page from search settings.  
When I search from home page search box, The page should partially load to search results page and results should be shown. I am getting results in chrome and edge perfectly. But for IE, it is giving below error. 

![image](https://user-images.githubusercontent.com/71835451/103773504-2ba8fc00-5051-11eb-8b9e-b652853f0fa7.png)

![image](https://user-images.githubusercontent.com/71835451/103773525-34013700-5051-11eb-8142-8c4f48cd66ef.png)

**Please help me out to where to make modifications in resolving this issue.** 

When I reload the page, I am able to see results.

![image](https://user-images.githubusercontent.com/71835451/103773956-d4575b80-5051-11eb-8715-49e6ead3082d.png)

**Desktop (please complete the following information):**
 - Browser [IE11]

**Comment by wobba** [comment] 2021-01-06 13:38
Duplicate of #576 - which has a link to a pre-release fix with the line commented out. Are you saying it breaks when this is commented out in IE11? Can you share an easy repro setup and I can take a look?

The fix is in the v3 branch, and Microsoft might actually fix this from their end (as they broke it).

**Comment by sekharB487** [comment] 2021-01-06 14:23
Hi Wobba, Thanks for your response as always. Here, I have uploaded zip file: https://github.com/sekharB487/PNPsearch
Please help me out in this issue.

**Comment by sekharB487** [comment] 2021-01-06 16:15
Hi @wobba , I had Tried with v3.16 commenting statement **//import 'core-js/modules/es.string.includes';.**
It was working in IE workbench and deployed in tenent. On search page I am using search vertical, filters, and results webpart.

**when I tried to search some keyword from https://XXXXXXXX.sharepoint.com/sites/CustomSearch/SitePages/Home.aspx, I am getting this error.**
![image](https://user-images.githubusercontent.com/71835451/103790512-4f773c80-5067-11eb-934a-0ad92c6386b3.png)
![image](https://user-images.githubusercontent.com/71835451/103790575-64ec6680-5067-11eb-975c-da36c2eb0497.png)

**when I just refresh the page, I am able to get all web parts.**
![image](https://user-images.githubusercontent.com/71835451/103790788-aaa92f00-5067-11eb-9c4a-a79ce7725b43.png)

I went through https://1drv.ms/u/s!AsQPRl4COMyeoq42TbOuuSoIg7Vwag?e=MU3PoS v3.17. I see this issue was handled very well in upcoming version. Could you please let me know the same steps used to make it work in IE. It will be very useful to us.

Thanks in advance.

**Comment by wobba** [comment] 2021-01-06 18:46
v3.17 has removed all references to core-js as we were not using it any more. Pull, the version-3 branch to see the changes.

**Closed** 2021-03-30 12:41 UTC
Labels: v3
