### ISSUE TITLE
Issue with Search results webpart with IE

### ISSUE THREAD

**Issue by sithender1** [microsoft-search/pnp-modern-search#589] opened 2020-12-02 14:37 UTC
Hello Team,

My Search results webpart is working fine if I access the SharePoint Site on Chrome. But same site when I access in IE getting the issue. 

**Something went wrong**
**If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details**

[SPLoaderError.loadComponentError]:
Failed to load component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Failed to load entry point from component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Error loading https://component-id.invalid/42ad2740-3c60-49cf-971a-c44e33511b93_3.15.3
 Cannot redefine non-configurable property 'includes'

INNERERROR:
Failed to load entry point from component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Error loading https://component-id.invalid/42ad2740-3c60-49cf-971a-c44e33511b93_3.15.3
 Cannot redefine non-configurable property 'includes'
CALLSTACK:
Error
   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:849936)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:849454)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:994853)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1035751)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1031790)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1024059)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:19198)
   at R (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:19174)
   at C (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:19060)
   at T (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:18638)

Any help?

Thanks
Sith

**Comment by FranckyC** [comment] 2020-12-02 17:20
Duplicate of #576

**Closed by FranckyC** 2020-12-02 17:20 UTC

**Comment by Erolsnow** [comment] 2020-12-04 01:24
Hi Guys,

I'm also experiencing this kind of issue when using this pnp-moderm-search webpart. Will this resolve the issue if I download the latest release now?

Latest release
 3.16.0
 bc5bc34

Thanks

**Comment by wobba** [comment] 2020-12-04 08:18
@Erolsnow no, we have not addressed the issue in the web parts - as I'd like to get clear guidance on the best approach for cases when OOB onboards a library which may be in use by 3rd party already.
