### ISSUE TITLE
Sort by feature unavailable on top of search results web part

### ISSUE THREAD

**Issue by nakkeerann** [microsoft-search/pnp-modern-search#1081] opened 2021-06-16 15:02 UTC
PnP Modern Search V4 search results web part does not have "sort by" feature available on top of it (except list layout). This is very nice feature, which was available as part of V3, but surprisingly not found on V4. I have also tried to explore the V4 documentations, but I could not find any details why this feature has been dropped from V4. 

Am I missing some configuration to turn on this with V4? or Do we have any plans to include this on the V4 search results web part in the future?

Available on V3:
![image](https://user-images.githubusercontent.com/20360358/122243186-d43e7000-cebb-11eb-8ab1-e16a36ddfc99.png)

But missing on V4:
![image](https://user-images.githubusercontent.com/20360358/122243426-06e86880-cebc-11eb-876f-79db28bd9463.png)

**Comment by FranckyC** [comment] 2021-06-17 00:12
Hi @nakkeerann , this is a duplicate of https://github.com/microsoft-search/pnp-modern-search/issues/597. Please follow this thread instead. Thanks!

**Closed by FranckyC** 2021-06-17 00:12 UTC
