### ISSUE TITLE
"HitHighlightedSummary" property is not returning the searched keywords with <c0> tag, else it returns only plain text in PNP modern Search v4.9.3.0

### ISSUE THREAD

**Issue by krishnare56** [microsoft-search/pnp-modern-search#3549] opened 2024-02-21 06:55 UTC
I am using PNP modern search V4 webparts in SharePoint online site. where i have linked search box and search results webpart. i need to highlight the Searched keyword in search results, i referred some documents where it stats "HitHighlightedSummary" will return the summery with highlighting the matched keywords, but in my case its simply returning the summery without highlighting the keywords. i am not sure what i am missing.

i have tried adding "HitHighlightedSummary" in Hit-Highlighted properties to but result is still same.

please find the below image for reference, where i have searched with word GCS but in "HitHighlightedSummary" it still returns plain summary.
<img width="566" alt="0kKpl" src="https://github.com/microsoft-search/pnp-modern-search/assets/131133647/f45f4abd-28be-4d6a-a5dd-4c2c74028fae">

**Comment by wobba** [comment] 2024-02-21 07:14
Duplicate of #3548

**Closed** 2024-02-21 07:14 UTC
