### ISSUE TITLE
Pass Search Vertical to Activate on Query String 

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#980] opened 2021-05-03 17:27 UTC
**Is your feature request related to a problem? Please describe.**
I want to use Search Verticals which send the user to separate pages for each vertical. I can do this, of course, and it works fine. However, when I land on one of the other pages, I'd like to activate the vertical which is currently in effect.

Example:
![image](https://user-images.githubusercontent.com/1295627/116910364-8d4e3100-ac13-11eb-8466-5bee95710155.png)

* Documents -> Search-Documents.aspx
* Formals -> Search-Formals.aspx
* Prior Art -> Search-Prior-Art.aspx

When I land on the Search-Formals page, I'd like the **Formals** Search Vertical to be selected, etc.

The reason for the separate pages is so I can provide different Managed Properties in the Search Filters for each search type.

**Describe the solution you'd like**
There are examples of this working in v3.x by passing the Search Vertical name on the query string, but it doesn't seem to work in v4.x

**Comment by sympmarc** [comment] 2021-05-03 17:35
Sorry about the incomplete description. Fixed!

There's also the notion of passing the vertical using a token, but I'm not sure how that should work. This seems to have no effect when used in the **Link URL** column:
`https://[tenant].sharepoint.com/sites/ClientsHub/SitePages/Search-Formals.aspx?v={verticals.name}`

**Comment by sympmarc** [comment] 2021-05-03 17:55
The workaround seems to be to display the verticals in a different order on each page, with the current vertical in position 1. That feels weird, but it will work for now.

**Comment by wobba** [comment] 2021-05-03 18:09
We're waiting for someone to contribute this feature to v4 :)

**Comment by sympmarc** [comment] 2021-06-01 16:21
Did someone contribute it yet? :)

**Comment by nikosmsk** [comment] 2021-06-02 14:01
Linking here similar requests #732 , #795

**Comment by wobba** [comment] 2021-06-11 08:51
Duplicate of #732

**Closed by wobba** 2021-06-11 08:51 UTC
Labels: enhancement, v4

**Comment by shivshankar112** [comment] 2022-03-25 17:21
Hey wobba, facing same above mentioned issue, did anyone contributed the feature ?
