### ISSUE TITLE
Unable to connect to retrieve data of type External Items using MS Search

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#607] opened 2020-12-12 23:35 UTC
**Version used**
4.0.0

I get a "The list is Read Only" error when trying to connect to an Azure DB Connector. The Connector seems to work as I get the expected values when using the OOTB MS Search with the custom search vertical

**To Reproduce**
1. Set Entity type to search to "External Items"
2. Enter the name of the Content Source as found on the connectors blade in the admin portal
3. See error

**Expected behavior**

**Screenshots**
<img width="306" alt="PnPsearchMSSearcherror" src="https://user-images.githubusercontent.com/20593570/101999158-8bbeb380-3cda-11eb-97b6-965db5467dc2.png">

<img width="748" alt="Connector" src="https://user-images.githubusercontent.com/20593570/101999169-a2650a80-3cda-11eb-8f3a-e969a8384e35.png">
<img width="611" alt="pnp400resultwp" src="https://user-images.githubusercontent.com/20593570/101999182-bb6dbb80-3cda-11eb-9e9a-c3269373b600.png">

**Desktop (please complete the following information):**
 - Browser Chredge

**Additional context**

**Comment by FranckyC** [comment] 2020-12-14 15:55
Hi @kasperbolarsen, I was able to reproduce it. However, the request seems to be correct :(. @wobba is this API part functional already? Can you test it in your env by any chance?

**Comment by wobba** [comment] 2020-12-15 13:40
@kasperbolarsen verify using the Graph Explorer. If you get the error there, log the issue with Graph. PnP web parts are API consumers only :) Can you test both v1 and beta endpoints?

**Comment by kasperbolarsen** [comment] 2020-12-16 08:18
@wobba 
using "https://graph.microsoft.com/v1.0/search/query" and request
{
    "requests": [
        {
            "entityTypes": [
                "externalItem"
            ],
            "contentSources": [
                "/external/connections/testDBConnection"
            ],
            "query": {
                "queryString": "*"
            },
            "from": 0,
            "size": 25,
            "fields": [
                "BusinessEntityID",
                "firstName",
                "lastName"
            ]
        }
    ]
}

Gives the expected result ( after granting "ExternalItems.Read" )
![image](https://user-images.githubusercontent.com/20593570/102322450-61415480-3f7f-11eb-9775-64e6e3c52b19.png)


It worked both i v1.0 and beta

**Comment by wobba** [comment] 2020-12-16 09:26
@kasperbolarsen can you compare the two requests? And also, can you check network trace which API call get's the "readonly" error? To rule out if it's some other API call, or the Graph API call.

**Comment by mbice** [comment] 2020-12-16 23:03
@kasperbolarsen did you grant API permissions for Graph external items? I had this same error and realized I needed to add and approve API access for Microsoft Graph ExternalItem.Read.All.

![image](https://user-images.githubusercontent.com/985283/102416922-95346e00-3faf-11eb-8542-73103d9b26d3.png)

**Comment by kasperbolarsen** [comment] 2020-12-16 23:54
@mbice That makes sense, however I have no idea where I should add that permission. Is this in the Azure AAD -> API Permissions and for which object ?

**Comment by mbice** [comment] 2020-12-17 00:02
@kasperbolarsen go to Azure > App Registrations > SharePoint Online Client Extensibility Web Application Principal. Then go to API permissions and add a new permission. The delegated permission is Microsoft Graph > ExternalItem > ExternalItem.Read.All. Once you've added that, grant admin consent on it and then reload the page and your query should work.

![image](https://user-images.githubusercontent.com/985283/102420798-c1ec8380-3fb7-11eb-93ca-28a468288526.png)

**Comment by kasperbolarsen** [comment] 2020-12-21 23:20
@mbice Thanks :-) That got me pass that one. Now the error msg in the results web part reads :  ( and I am just a business consultant which write some client-server code some 20 years ago, so I have no idea about how to debug this ;-) sorry)

![image](https://user-images.githubusercontent.com/20593570/102831069-2c078d00-43eb-11eb-8669-757b55e008f6.png)

**Comment by mbice** [comment] 2020-12-22 00:22
@kasperbolarsen yeah I saw that error as well. I submitted a PR for it, which was merged the other day so hopefully that makes its way into a new release soon.

https://github.com/microsoft-search/pnp-modern-search/pull/628

**Closed** 2021-01-04 15:29 UTC
