### ISSUE TITLE
Question:  Getting started - not seeing any results

### ISSUE THREAD

**Issue by mikezimm** [microsoft-search/pnp-modern-search#409] opened 2020-07-30 16:48 UTC
Hi,
I was wondering what the absolute minimum settings are required to add to the prop pane to get results on the page just so I know it's wired up correctly.

## This is what I did so far
1. I packaged packaged the solution and deployed to my app catalog (no errors)
2. Added it to a site though site contents (no problems)
3. Added the four search webparts to a page (no problems)
4. Connected them all to the search results using the search results prop pane (painless :)
5. Saved the page
6. Typed something in the search box but didn't get any results :(

When I edit the page (screenshot # 1), I see the configure button but nothing in the prop pane that screams out that I need to do something.

Am I missing something to get just results from say... our entire tenant?  ie no refined search scope?

![image](https://user-images.githubusercontent.com/49648086/88950361-8c423a80-d262-11ea-9abf-1b20dfc9a553.png)

This is what the published page looks like
![image](https://user-images.githubusercontent.com/49648086/88950380-906e5800-d262-11ea-8209-d1309b3d10f4.png)

Thanks!

**Comment by wobba** [comment] 2020-08-03 13:13
Start with just the search box and result web part, get those working. Then change to add verticals and check the query template used etc. Much easier to figure out where the error is this way.

**Comment by andrewbackway** [comment] 2020-08-07 23:54
Had the same issue, found the connection between the results box and the search box wouldn't stick, eventually after a few attempts it stuck.

At a guess i'd say theres something wrong with the first page of the search results property editor.

**Comment by wobba** [comment] 2020-08-08 07:10
I'll see if I can repro and figure it out.

**Comment by wobba** [comment] 2020-08-13 07:03
Searchbox issue is a duplicate of #299 I believe and will track it there.

**Closed by wobba** 2020-08-13 07:03 UTC
