### ISSUE TITLE
Error "Cannot read properties of undefined" on first load

### ISSUE THREAD

**Issue by JungLSEDV** [microsoft-search/pnp-modern-search#3823] opened 2024-06-25 15:16 UTC
**Version used**
4.12.2

**Describe the bug**
When opening the Page for the first time the PnP Search-Results Webpart will throw an Error

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Clear Cache/Open Browser with Incognito mode
1. Go to Sharepoint Website with a PnP Search-Results Webpart present
2. The Error should pop up

**Expected behavior**
An Empty Search-Results Webpart should be displayed/not be displayed since nothing is input into the Search Box Webpart

**Screenshots**
Chrome:
![image](https://github.com/microsoft-search/pnp-modern-search/assets/152263948/24b73ff2-3fc4-446f-8634-494a383052b1)

Firefox:
![image](https://github.com/microsoft-search/pnp-modern-search/assets/152263948/baaf3d6e-9cbc-41a8-ae5e-8d2e10c3469d)

**Desktop (please complete the following information):**
Tested in Chrome (126.0.6478.115 64-Bit) and Firefox (127.0.1 64-Bit)

**Additional context**
We use the Search Results as a Person-Search to find Coworkers via our Intranet page (Set up similar to the "useful people search" but without the Filters Webpart)
We had the same issue some time ago when we first set up our page with version 4.10.2
But similar to Issue #3700 it was fixed with 4.11.0
I have the strange feeling it came back with 4.12.* but i just made aware of it today so i havent had the time to try to revert to 4.11.

**Comment by rdel49** [comment] 2024-07-08 13:40
I was noticing this issue too last week; it appears to be linked to the Microsoft Graph Toolkit toggle for Sharepoint Search with People layout. 

I had "Use Microsoft Graph Toolkit" checked. When checked, any Ctrl+F5 refresh of the page would result in an error similar to below:
![image](https://github.com/microsoft-search/pnp-modern-search/assets/115031782/7e5cf42b-88ce-449b-b87e-4c7e23cd6b95)

When I unchecked "Use Microsoft Graph Toolkit" I do not see this error when doing a Ctrl + F5 refresh.

**Comment by JungLSEDV** [comment] 2024-07-08 14:02
Since my Issue we reverted back to 4.11.1.
This Version does NOT have this issue.

After @rdel49 's comment i checked and we also have the "Use Microsoft Graph Toolkit" toggle enabled
I can also confirm without the Toggle we do not get the Error, but we dont get search results either, but that may be our Queries 
Search-Query: "{searchTerms}* WorkEMail:_workdomain_ -.az" (Search everyone having a workmail and not having .az as a mailsuffix)
Standard-Value: "XXX" (Should Display as empty since noone should have that Name)

**Comment by mobun** [comment] 2024-07-25 14:39
@rdel49 & @JungLSEDV quick question.
I came across the issue because the error is only displayed in the browser console (Use Microsoft Graph Toolkit was already deactivated). 
Can you also reproduce this?

**Comment by kasperbolarsen** [comment] 2024-07-27 08:01
> Since my Issue we reverted back to 4.11.1.
> This Version does NOT have this issue.
> 
> After @rdel49 's comment i checked and we also have the "Use Microsoft Graph Toolkit" toggle enabled
> I can also confirm without the Toggle we do not get the Error, but we dont get search results either, but that may be our Query
> Search-Query: "{searchTerms}* WorkEMail:_workdomain_ -.az" (Search everyone having a workmail and not having .az as a mailsuffix)
> Standard-Value: "XXX" (Should Display as empty since noone should have that Name)

I would think that you query should be:
"{searchTerms}* -WorkEMail:_workdomain_.az"
KQL doesn't support "ends with"

**Comment by JungLSEDV** [comment] 2024-07-29 11:15
@mobun i can confirm, that with "Use Microsoft Graph Toolkit" disabled, there is still an error Message on the Browser Console
![image](https://github.com/user-attachments/assets/9ecf1e04-d406-4111-b872-2fd58d3eb3c5)

@kasperbolarsen i have now modified my Query to this 
`({searchTerms}*) //Searchfilter Field
(WorkEMail:workdomain.de) //WorkEMail contains our workdomain (excludes all external partners in our AD)
(-WorkEMail:.az*) //exclude addresses contiaining .az (.az ist our suffix for apprentices)
(-WorkEMail:auszubildende*) //exclude group-users for apprentices
(-WorkEMail:admin*) //exclude users with admin in their Mail address`

**Comment by mobun** [comment] 2024-08-06 15:51
I can no longer reproduce the error. Maybe the whole thing has been fixed by MSFT through an update in SharePoint? 
Since I have not actively made any changes, I assume that this is the case.

**Closed** 2024-08-06 16:22 UTC
Labels: Needs: Author Feedback, Needs: Triage
