### ISSUE TITLE
Incorrect file type / document icon.  Instead of document icon, the site icon displayed in search result webpart V3

### ISSUE THREAD

**Issue by michikammerer** [microsoft-search/pnp-modern-search#1583] opened 2021-12-02 16:03 UTC
Version used:
3.22.0.0

Description:
We are using V3 modern search webparts at quit few soltuions. Since approx. 2-3 days (30.11.2021) the "Search Result" webpart doen't display the file type icon any more. Instead of the document icon, the webpart display the site icon. This happens only for documents crawled after 30.11.2021 (approx.) or re-index of a site will be done. This issue happen on all our tenants. It look like Microsoft has changed something on search.

Reproduce:
1. Place v3 search result webpart (display icons)
2. Re-Index a site with documents
2. Instead of file icon the site icon will be displayed 

Desktop:
 - Browser: Edge / Chrome
 
![Search V3 - No Icon](https://user-images.githubusercontent.com/73946125/144458178-a6c94473-51c9-4b1c-a3ec-159f9acf71f2.png)

**Comment by wobba** [comment] 2021-12-03 10:42
I cannot repro. Can you grab a sample of the `postquery` JSON request as well as a sample item response?

**Comment by davidgrle** [comment] 2021-12-03 14:03
Got the same problem with version 4.4.1.0 here.

**Comment by wobba** [comment] 2021-12-03 14:19
@davidgrle doesn't help if we cannot have repro or some JSON request/response to look at :)

**Comment by wobba** [comment] 2021-12-03 14:23
Closing as it seems to be a duplicate of #1579 - same issue.

**Closed by wobba** 2021-12-03 14:23 UTC
Labels: Needs: Triage, v3

**Comment by michikammerer** [comment] 2021-12-03 15:05
@wobba : In my case of the missing document icon it happens as well with 4.4.1.0.

Attached you'll find postquery and response done with 3.22.0.0
[response.txt](https://github.com/microsoft-search/pnp-modern-search/files/7650468/response.txt)
[postquery.txt](https://github.com/microsoft-search/pnp-modern-search/files/7650469/postquery.txt)

**Comment by wobba** [comment] 2021-12-03 15:30
I found the issue. Seems the property `SiteLogo` is now returned in your tenant for all items - which is not the case on my old dev tenant as an example. I'll try to ask internally about this.

**Comment by michikammerer** [comment] 2021-12-03 16:35
x-searchplatform: Substrate

**Comment by taylorjandrew** [comment] 2021-12-09 11:47
We have this as well, in version 3.16 and it also happens in 4.4.1 - I watched the DocIcons disappear and get replaced by SiteLogos almost in real time as the search index updated. We have had unannounced (Microsoft) back end search and other changes recently that are affecting user/business confidence, and are costly to investigate and work around. My workaround on this for now is to use the Custom layout/template for search results in 4.4.1

**Comment by wobba** [comment] 2021-12-10 11:57
We need to change the icon logic in the web parts to solve this. Shouldn't be hard, but someone has to find the time to do so.
