### ISSUE TITLE
[HTTP]:500 - [CorrelationId]:6bcae9a0-f023-7000-6fe1-48bba24a8cdf [Version]:16.0.0.24218

### ISSUE THREAD

**Issue by SundownRyan** [microsoft-search/pnp-modern-search#3321] opened 2023-11-01 11:16 UTC
**Version used**
4.9.3
4.9

**Describe the bug**
I'm receiving the following error on the web part: 

[HTTP]:500 - [CorrelationId]:6bcae9a0-f023-7000-6fe1-48bba24a8cdf [Version]:16.0.0.24218

I've followed the guide [here](https://microsoft-search.github.io/pnp-modern-search/scenarios/Create-a-useful-People-Search/) to setup the web part for a people picker. I've tested this in two different tenants, one of which worked and the other showed the error above. The issue appears to be with the LocalPeopleResults source as the web part looks as though it works in any other search. The issue persists across different site collections.

I opened a ticket with Microsoft for the issue as I saw a previous issue raised was very similar, but they recreated the issue and concluded it was one to raise here. Any help is much appreciated. 

**To Reproduce**
Detailed steps to reproduce the behavior:
Following the guide provided on a [useful people search](https://microsoft-search.github.io/pnp-modern-search/scenarios/Create-a-useful-People-Search/) is what returned the error for both myself and the Microsoft engineer that was working on the issue.

**Expected behavior**
The web part should show a list of people from the org. 

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/103187369/38c600db-5f2b-4769-9e6c-5e66be2fb863)

**Desktop (please complete the following information):**
 - Browser: Chrome, Edge

**Comment by kasperbolarsen** [comment] 2023-11-01 11:56
Hi, can you use one of the tools here https://microsoft-search.github.io/pnp-modern-search/using-query-tools-to-verify-issues/ to verify the result you get when using the query?
If it is an issue with the localpeopleresult source it has nothing to do with this project, but perhaps we can find the root cause :-)

**Comment by wobba** [comment] 2023-11-12 17:23
Closing due to missing author feedback on triage. 500 errors are API related which means either something is wrong on the server side, or your configuration somehow sends a request which is incorrect. We would need the JSON request to see if we can spot the error.

**Closed by wobba** 2023-11-12 17:23 UTC
Labels: Needs: Author Feedback, Needs: Triage

**Comment by kasperbolarsen** [comment] 2023-11-12 17:27
I actually resolved one of those errors last week.  
The result web part was configured to sort by default using a property that wasn't sortable,  boom

**Comment by wobba** [comment] 2023-11-12 17:31
That will cause a 500 error for sure 🙂

**Comment by kasperbolarsen** [comment] 2023-11-12 17:36
Would it be possible to check if a property is sortable in the config panel, perhaps on save?

**Comment by wobba** [comment] 2023-11-12 17:38
We could hardcode the list (which I've never had time to do) as it's a set list from the schema, not changing (for SP at least).

**Comment by SundownRyan** [comment] 2023-11-13 09:18
Apologies for the delay, I've tried passing the issue back to Microsoft as I'm seeing the same error on any post request to the LocalPeopleResults source. I've tried a get all with no filters with the SharePoint Search Tool, with the same result.

**Comment by kasperbolarsen** [comment] 2023-11-13 18:09
> We could hardcode the list (which I've never had time to do) as it's a set list from the schema, not changing (for SP at least).

Should we add it as a new issue (enhancement)? If you can give me an intro I might be able to complete it.

**Comment by wobba** [comment] 2023-11-13 18:24
Think it is there somewhere already 😄
