### ISSUE TITLE
Term with ID not Found

### ISSUE THREAD

**Issue by nthoman** [microsoft-search/pnp-modern-search#2404] opened 2022-09-30 16:19 UTC
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/2403

<div type='discussions-op-text'>

<sup>Originally posted by **nthoman** September 30, 2022</sup>
![image](https://user-images.githubusercontent.com/48287847/193313075-af4c1475-a9fb-49b7-bab8-caf9bf646392.png)

I merged some terms in my term store in SharePoint Admin Center and now the Search Filter result list is still showing up terms that are not available anymore. I have confirmed the documents no longer have the old term mapped and I re-indexed the site but it's still showing up. Can we just have a switch to turn off NOT FOUND terms in the filter config?
</div>

**Comment by wobba** [comment] 2022-10-03 10:53
Duplicate of #2403

**Closed by wobba** 2022-10-03 10:53 UTC
