### ISSUE TITLE
Filter panel appears when clearing search terms but no filters selected

### ISSUE THREAD

**Issue by jamesdellowE2** [microsoft-search/pnp-modern-search#1144] opened 2021-07-12 07:44 UTC
**Version used**
4.2.2.0

**Describe the bug**
When searching and going through a process of selecting filters and trying different search terms, the panel filter opens even if no filters are selected

**To Reproduce**

1. Select a filter and close panel
2. Enter a search term with no results - panel opens
3. Clear filters - results appear. Close panel
4. Clear search term with x button - panel opens, but no filters are selected

**Expected behavior**
Filter panel shouldn't open unless the user accesses the filters or if there are no results.

**Screenshots**

**Desktop (please complete the following information):**
Edge

**Additional context**
The page contains:
- Search box
- Results
- Using Panel Filter

**Comment by Viipiin** [comment] 2021-07-14 04:51
I am facing the same problem. Also, is there a way so that I can set Target Audience on Vertical webpart

**Comment by wobba** [comment] 2021-07-14 15:48
@FranckyC seems state of the filter panel is dependent on if a filter was selected at one time or not - an not on explicit open/close. Not sure how best to set this as the web-component is recreated on each render. But passing in open/close should not be needed if state can be kept internally.

**Comment by FranckyC** [comment] 2021-07-15 00:41
@wobba you're right the issue is at web component level because the state is lost after every re-render. We need to "exterrnalize" the panel open state in a dedicated variable due to the Handlebars constraint. I'll see what I can do here.

**Comment by FranckyC** [comment] 2021-07-15 00:44
@Viipiin short answer no but please don't mix multiple questions in the same issue as this is not related.

**Comment by FranckyC** [comment] 2021-07-15 17:43
Hi @jamesdellowE2 this should be resolved in the `develop` branch and available in the next release. Thanks!

**Closed by FranckyC** 2021-07-15 17:43 UTC
Labels: bug, v4
