### ISSUE TITLE
PnP - Search Results web part - configuration not going to 3 and 4 pages

### ISSUE THREAD

**Issue by Joclaim** [microsoft-search/pnp-modern-search#2440] opened 2022-10-12 08:40 UTC
**Environment**
Below an overview of the different configurations we have used to solve the issue:
- Office 365, SharePoint Online
- Microsoft Edge & Google Chrome
- Versions 4.7.0 & 4.8.0
- Deployment Global app store and local app store
- Sites pages library, News post & Page
- Different site collections

**Issue**
We are unable to move to the next pages (3 and 4) in the configuration settings of the Search result web part. When clicking next on the second page of the configuration settings, it jumps back to the first. We have this issue in our complete tenant, for all pnp - Search results web parts, in different site collections. 

**Reproduce**
- Create a new Site Collection
- Create a new page
- Add the pnp - search box and the pnp - search results web part to the page
- Edit the pnp - search results web part
- Click SharePoint search as data source, click next to go the second page
- Click next to go to the third page (it will now jump back to the first page)

**Attempts to resolved**
- Uninstalled the deployment and redeployed
- Uninstalled from the Global app store and created a local app store and deployed
- Used different versions of the pnp-modern-search
- Created a blank environment= new site collection, new page
- Tried different configurations

**Additional information**

- We do not have the issue with our pnp - search box configuration, there we can go to the third and fourth page. 
- We also do not have the issue in our test tenant.
- We do get search results and search works for the configuration what we are able to do.
- We see this error in the dev tools console when clicking Next on the 2 page:

sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69 
        
**[TypeError: Cannot set properties of undefined (setting '0')]([url](url))**
    at Vt (sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69:28922)
    at uc (sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69:97983)
    at Xc (sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69:114143)
    at ad (sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69:115158)
    at sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69:123087
    at gc (sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69:101087)
    at t.unmountComponentAtNode (sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69:123073)
    at t.componentWillUnmount (chunk.property-pane-component_none_ebbbdfff738361243578.js:1:13226)
    at hs (sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69:93065)
    at Ds (sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69:94855)
ss @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
n.callback @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
pr @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
ms @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
Lc @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
Ki @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
Ac @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
hc @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
(anonymous) @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
Ki @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
Qi @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
qi @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
Pe @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69
Yt @ sp-pages-assembly_en-ie_f946efc90fdebdce11372a60518348b2.js:69

![Page1](https://user-images.githubusercontent.com/115615463/195293559-c00b7afc-85cc-4601-9daa-e13df1a223f8.PNG)
![Page2](https://user-images.githubusercontent.com/115615463/195293590-7d5409b3-8567-4c3f-970a-7a65c1049228.PNG)

**Comment by harshdamaniahd** [comment] 2022-10-12 09:40
Thanks, I am also having this issue..and struggled. I removed and readded 4.7.0.0 ...and still it doesn't work.

We are not able to connect to search box or search filters

**Comment by edarroudi** [comment] 2022-10-12 10:09
I'm also having this issue. I'll check if MS did some update and where the issue is. I have this issue since a couple of days on different tenants, thought first it's about my custom extension code..

**Comment by wobba** [comment] 2022-10-12 10:19
Duplicate of #2405, and read the comments at the bottom.

**Closed by wobba** 2022-10-12 10:19 UTC
