### ISSUE TITLE
Navigation - Uncaught Error: Dynamic Data Provider has been disposed 

### ISSUE THREAD

**Issue by fisketryne5** [microsoft-search/pnp-modern-search#1483] opened 2021-11-04 14:35 UTC
After navigating away from the search page, the next click on any link is ignored. The url in the browser are updated, but not the page. The following console error is added as a screenshot.

**To Reproduce**
1. Do a search on a page that has PnP Search Webparts.
2. Navigate to another page by default SharePoint navigation.
3. Click on a link on the next page.
4. The browser url changes but the page does not reload.

**Expected behavior**
I expect to navigate to a new page after clicking on the link.

**Screenshots**
![image](https://user-images.githubusercontent.com/22908383/140332769-6b07ae58-7ae7-4946-ac9a-43136ae5874e.png)

**Desktop (please complete the following information):**
 - Browser: chrome

**Additional context**
Tested in PnP Search version 4.4.1.0 and 4.3.0.0
Tested in two different tenants.

**Comment by mbice** [comment] 2021-11-05 16:21
We're seeing the same issue with 3.x. I can reproduce in 3.22.0, 3.21.0, and even 3.19.2.0 and fairly certain this was working even just a few days ago. Perhaps something has changed on the MSFT side?

**Comment by FranckyC** [comment] 2021-11-05 16:27
Dynamic data issues are usually race conditions issues and therefore, random. It is expected you don't see them every time. We'll look into it.

**Comment by VerlindenEAM** [comment] 2021-11-19 07:24
Hi all, I am checking with both V4 and V3 and we are encountering this a issue a lot, also from our users, is there any update on it?

**Comment by dgwebb** [comment] 2021-11-22 17:02
Hello - has there been any update on this issue?  We have numerous clients using the v3 web parts who are experiencing it.  It would be great to get a resolution one way or another.

**Comment by wobba** [comment] 2021-11-22 21:06
There's no need to ask for updates. Issues will be referenced and closed when adressed. And anyone can help out 🙂

**Comment by TrustLRon** [comment] 2021-11-25 10:30
We are seeing this issue when we have more than 1 results webpart on the page at the same time.  Interested to see if the others experiencing this issue have the same setup.  

*(below theory is fairly convoluted, sorry!)*

The `SearchBoxWebPart.ts` and the `SearchResultsWebPart.ts` both store references to the `history.pushState` function in a `_pushStateCallback` prop and replace the global on the `window` object with a custom `pushStateHandler` function. They then restore the `history.pushState` function to this stored native code function when the webpart is disposed in the `onDispose` event.

The issue seems to turn up when there is more than 1 instance of the same webpart on the page.  What I think is happening is that when the second instance loads, the `history.pushState` function has already been replaced, so the new instance ends up storing another copy of the `pushStateHandler` function (instead of the expected native code).  So when the internal routing (link interception) happens and `onDispose` is called, the global `history.pushState` ends up being restored to the custom one, which fails to work on the next navigation event (the custom function tries to call `tryGetSource` but falls back to the version in the `sp-pages-assembly{...}.js` in modern pages, that asserts that the `dynamicDataProvider` is not disposed and throws).

Out of interest, can anyone comment on why the global `history.pushState` is being overridden?  Would a potential fix be to move to having the search box webpart to emit a new `PopStateEvent` on search and have the other components listen for an `onpopstate` event?  Or are there other conflicting internals at play here?

Hopefully this info can help!

**Comment by dabanks** [comment] 2021-11-25 11:26
Our scenario is a little different where its seems to be causing issues anytime multiple webparts are connected via Dynamic Data (e.g. Search Box, Search Results and Search Filters). So anytime a user navigates to a page that includes these components or via a page that has these components the navigation breaks and "Dynamic Data Provider has been disposed" errors start appearing.

Worth noting that this is not just breaking navigation but page creation as well. Both the "New Page" and "Copy this page" functionality break when performed on a page with these components or when the user has navigated to a page via a page with these components.

It would be really good to get some indication of if this issue is being looked at and if a fix will be in the next release. We have a client who is looking to launch their new intranet shortly and as things stand with these issues in place, this cannot happen.

**Comment by wobba** [comment] 2021-11-25 14:58
@dabanks would be good if you can clarify what "navigation" means.. from a page on the site, another site etc. And it will be looked at when time allows. We aim to do a new release late December.

**Comment by dabanks** [comment] 2021-11-25 16:20
@wobba navigation is mostly between pages in a single site. However when this issue occurs it also breaks clicking any hub site navigation.

**Comment by till-llit** [comment] 2021-12-14 10:38
issue is still reproducable with 4.5.0

**Comment by wobba** [comment] 2021-12-15 15:21
@till-llit can you share exact repro setup? I cannot seem to repro with v4.5, testing on a team site.

* Have a page with a result web part
* Navigate to the pnp page
* Navigate to Home
* Clicked a link on home page which goes to another page on the site

I tried back and forth with home and pnp page - still cannot get it to fail.

**Comment by till-llit** [comment] 2021-12-15 15:44
im sorry - i was wrong i guess. i tried a lot and cannot reproduce with 4.5

**Comment by wobba** [comment] 2021-12-16 07:22
@till-llit I re-wrote the code as well to add more safety on dynamic data. It's included in 4.5.1.

**Comment by Fossness** [comment] 2021-12-24 00:27
Hi guys, new here so apologies if I post something redundant.

I can replicate the issue stated above with version 4.5.3 and here in this thread:

[#1642](https://github.com/microsoft-search/pnp-modern-search/issues/1642)

The only difference I have is that there are two PnP search results webparts on my custom search/results page (both webparts are being used to display information differently from the same query). I have tested this on a separate barebones tenant with the bare minimum configuration and the same behaviour occurs. This behaviour immediately stops after removing the second results webpart.

**To Reproduce**
Steps to reproduce the behavior:

Create new custom page and **add two PnP results search web parts pulling the same query**.
Go to site settings -> Search Settings -> change/add the custom page URL
Go to home page
Type "test" on SharePoint OOB search box and hit search link or enter.
Result (first time) - Redirected to custom search page
Click on back button (search box back button) from custom page
Change search test "xyz" and hit search again
Issue - search box do not redirect to anywhere...

Let me know if you need any further information.

**Comment by wobba** [comment] 2022-02-07 15:17
@Fossness I have repro.. two web parts using dynamic data from the page environment.

**Comment by wobba** [comment] 2022-02-07 15:56
Fixed in the dev branch with https://github.com/microsoft-search/pnp-modern-search/pull/1806

**Closed by wobba** 2022-02-07 15:56 UTC
Labels: bug, Needs: Triage, v4

**Comment by sumitdeyonline** [comment] 2022-02-10 22:23
When you are planning to release this fix?

**Comment by sumitdeyonline** [comment] 2022-02-14 19:53
We have built the dev branch and it's working for us. We are planning to roll out new search in the 2nd week of March, hopefully, we would get a new release by that time.

**Comment by sumitdeyonline** [comment] 2022-03-14 23:48
I have fixed with the DEV branch

**Comment by shariq1379** [comment] 2022-03-28 14:08
When we can expect release this change with PnP package?

**Comment by wobba** [comment] 2022-03-28 14:16
No exact plans - until that you can build the dev branch yourself 🙂
