### ISSUE TITLE
Selection not triggerring connected web part refresh

### ISSUE THREAD

**Issue by Titef** [microsoft-search/pnp-modern-search#3514] opened 2024-02-07 16:32 UTC
**Version used**
4.10.2

**Describe the bug**
When 2 search results web parts are connected with multi-selection activated, connected web parts is not refreshed when changing the selection using the "Select" icon at the left of the row in "Details List" layout

**To Reproduce**
Detailed steps to reproduce the behavior:

  Search Result Web Part #1 :
    1. Add a Search Result Web Parts
    2. Set Search query to "* IsDocument=1"
    3. Set the layout to "Details List"
    4. Activate items selection with multiple selection
  
  Search Result Web Part #2 :
    5. Add another Search Result Web Parts
    6. Set Search query to "*"
    7. Set the layout to "Cards"
    8. Connect this Web Part to Search Web Part #1 with "NormUniqueID" as source field and "NormUniqueID" as destination field
    9. Set connection selection mode to "Process selected values as filters (default mode) with a "OR" logical operator

**Expected behavior**
When an item is selected on Search Web Part #1 using the selected icon, the Search Web Part #2 result should update.

**Desktop (please complete the following information):**
 - Browser : chrome

**Comment by kasperbolarsen** [comment] 2024-02-09 13:34
I'm looking into this issue

**Comment by kasperbolarsen** [comment] 2024-02-09 16:40
A setup that seems to work:
Result web part 1:
query: * IsHubSite=1
 Layout: List or Card

Result Web part2:
query: isDocument:1
layout: what ever you like
connection:
![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/7c605979-1c60-4e5f-967f-a021ecf2cae5)


So, the issue is related to the Details List only

**Comment by patrikhellgren** [comment] 2024-03-01 09:40
Fixed in #3568 and will be part of the next release.

**Closed** 2024-03-03 12:42 UTC
Labels: bug, help wanted
