### ISSUE TITLE
Allways horizontal scroll when using grouped results

### ISSUE THREAD

**Issue by schoier** [microsoft-search/pnp-modern-search#2971] opened 2023-05-15 07:58 UTC
**Version used**
4.8

**Describe the bug**
When we enable grop by in the search result webpart we get a horizontal scroll, no matter the width of the column used

**To Reproduce**
Detailed steps to reproduce the behavior:
Add a search result webpart.
Enable group by (uncertain of the translation)

![image](https://github.com/microsoft-search/pnp-modern-search/assets/33417064/8e93b5ee-e491-42b6-9fba-271a47078780)

**Desktop (please complete the following information):**
 - Edge

**Comment by sympmarc** [comment] 2023-10-16 14:45
Is this a duplicate of #2790?

**Comment by schoier** [comment] 2023-10-16 15:11
Yes, I think it is. --Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2023-10-16, 16:45 Marc D Anderson ***@***.***> wrote:

   
  Is this a duplicate of #2790?

**Comment by wobba** [comment] 2023-10-16 15:16
Closing as duplicate

**Closed by wobba** 2023-10-16 15:16 UTC
Labels: bug, Needs: Triage, v4
