### ISSUE TITLE
Refiners disappear after selecting one.

### ISSUE THREAD

**Issue by RamaKaryam** [microsoft-search/pnp-modern-search#106] opened 2020-02-21 06:12 UTC
**Version used**
3.9.0.0

**Describe the bug**
In the search refiners webpart, when we click on a refiner, the clicked item along with all other items in all other refiners disappears. The refiner headings are there but the items within disappear.

**To Reproduce**
Add search refiners webpart and configure it so that its template is 'Default Refinement Item' and not expanded by default. Tie the refiner to related search webparts on the page (search box & refiners).

**Expected behavior**
The selected item's checkbox is checked and all other refiners adjust based on the returned result set.

**Screenshots**
Before selecting an item in refiner.
![image](https://user-images.githubusercontent.com/32988250/75008796-d14d7f80-542d-11ea-9349-047965de4b88.png)
After selecting an item in refiner.
![image](https://user-images.githubusercontent.com/32988250/75008840-f17d3e80-542d-11ea-9ffd-b8d4ba3126bc.png)

**Desktop (please complete the following information):**
 I checked in Edge and Chrome.

**Comment by FranckyC** [comment] 2020-02-21 13:22
Hi @RamaKaryam Did you connect the search results and search refiners WP both ways?

**Comment by RamaKaryam** [comment] 2020-02-21 17:50
Yes, checked it now just in case.

**Comment by wobba** [comment] 2020-02-24 07:09
Are you using two RefinableString properties? If you look at the network calls to _api/search, can you see if data is returned when refining or not?

**Comment by schoier** [comment] 2020-03-11 13:55
I'm having the same problems. 
Choices often dissapears after only selecting an item independent of other choices. Usually the first one or two items is OK to choose but not other items further down in the list of choices.
I'm only using RefinableString properties.
I have a site on another tenant with version 3.8.0.0 and I'm not having the same issues there.

**Comment by MikaelRastock** [comment] 2020-03-11 14:40
Hello we are having the same or similar problem problem. Tested on several pages and different browsers. In some cases the refiners dissapear and in other cases the refiners are grayed out. It seems to happen only when the refinable section is expanded when selecting the refiner.

**Comment by MikaelRastock** [comment] 2020-03-12 07:11
An update on this.
I have tested some more and the problem for me only comes when i use a refiner of type Date Range. Date Range (fixed intervals) works for me.

**Comment by wobba** [comment] 2020-03-12 09:23
@MikaelRastock is it intermittent, or always when you use the date filter?

**Comment by MikaelRastock** [comment] 2020-03-13 09:51
I have now tested  a litte bit more and this the procedure that always gives the error:


  *   Have a date column (list or site column) that is mapped to a RefinableDateXX property.
  *   Have some items in the search result scope that do not have any values in the date column.
  *   Use the RefinalbleDateXX column as a refiner in the Search Filters webpart and use the DateRange setting.
  *   Use some other refiners that are not date columns.


If i now try to use a refiner (not the datecolumn)  that will return only results that are blank in the date column, the error occurs.
So it happens when the date-refiner is hidden. It hides the date-refiner correctly but it also hides all the other refiner-items. (The headers are still visible)


Från: Mikael Svenson <notifications@github.com>
Skickat: den 12 mars 2020 10:24
Till: microsoft-search/pnp-modern-search <pnp-modern-search@noreply.github.com>
Kopia: Mikael Råstock <mikael.rastock@mentor365.se>; Mention <mention@noreply.github.com>
Ämne: Re: [microsoft-search/pnp-modern-search] Refiners disappear after selecting one. (#106)


@MikaelRastock<https://github.com/MikaelRastock> is it intermittent, or always when you use the date filter?

**Comment by FranckyC** [comment] 2020-03-13 13:04
Hi @MikaelRastock Thank you for taking the time to write the repro steps. Very appreciated. I will investigate this case and I let you know.

**Comment by FranckyC** [comment] 2020-03-13 17:56
Ok I think I found why. This should be resolved by now. This one was tricky but finally pretty dumb...My fault, probably due to a wrong copy/paste. Apologies guys ! Let me know if it is ok with the latest code on the develop branch.

**Closed by FranckyC** 2020-03-13 17:56 UTC
Labels: working on it

**Comment by MikaelRastock** [comment] 2020-03-13 18:05
Thanks a lot for your effort! I think we might have seen some more minor bugs in the user interface of the refiners, but they might be related to this. I post a new issue if i can reproduce them. 

/Mikael
