### ISSUE TITLE
Display template - "Refinement Item" for File Type.

### ISSUE THREAD

**Issue by ManuhinSPalath** [microsoft-search/pnp-modern-search#1075] opened 2021-06-15 06:51 UTC
Hi Team/ @wobba,

How we can implement the below layout for File Type refiner rather than extension listed.
![image](https://user-images.githubusercontent.com/43960039/122005300-18a21100-cdd3-11eb-9bbf-c9d6e30daee4.png)

Found the below option in classic experience, is it exist in modern web part, if not how we can implement.
![image](https://user-images.githubusercontent.com/43960039/122005555-6a4a9b80-cdd3-11eb-97d5-5ff840b33ffa.png)

Thank you.

**Comment by wobba** [comment] 2021-06-15 07:09
It has to be developed. Duplicate of #972

**Closed by wobba** 2021-06-15 07:09 UTC
